{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/agents","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"code":"[Agent]","type":"codeVoice"},{"type":"text","text":" assigned to the channel"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"agents"},{"text":": [","kind":"text"},{"text":"Agent","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","kind":"typeIdentifier"},{"kind":"text","text":"]"}]}]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"agents","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"agents"},{"text":": [","kind":"text"},{"text":"Agent","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"agents","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState(py)agents","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatstate\/agents"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatstate\/agents"]}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"text":" is a model representation of the current chat session.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatstate","title":"ChatState","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatState"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/agents":{"kind":"symbol","title":"agents","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/agents","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"agents"},{"text":": [","kind":"text"},{"text":"Agent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent"},{"text":"]","kind":"text"}],"abstract":[{"type":"codeVoice","code":"[Agent]"},{"type":"text","text":" assigned to the channel"}],"navigatorTitle":[{"kind":"identifier","text":"agents"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatstate\/agents"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent":{"url":"\/documentation\/chatproviderssdk\/agent","navigatorTitle":[{"text":"Agent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","abstract":[{"text":"The ","type":"text"},{"code":"ZDKAgent","type":"codeVoice"},{"type":"text","text":" model has information about an agent in a chat session,"},{"type":"text","text":" "},{"text":"such as their backend ","type":"text"},{"type":"codeVoice","code":"id"},{"text":" represented as ","type":"text"},{"type":"codeVoice","code":"nick"},{"text":", their display ","type":"text"},{"type":"codeVoice","code":"name"},{"type":"text","text":", their "},{"type":"codeVoice","code":"avatar"},{"text":", and if they’re currently typing.","type":"text"}],"title":"Agent","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Agent","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"agents","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"agents"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKAgent *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"agents","kind":"identifier"}]}]}},{"value":"ZDKChatState","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","value":[{"kind":"identifier","text":"ZDKChatState"}],"op":"replace"},{"op":"replace","value":"agents","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1agents\/title"},{"value":[{"kind":"identifier","text":"agents"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1agents\/fragments"},{"value":"ZDKAgent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/title"},{"value":[{"text":"ZDKAgent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/fragments"}]}]}