{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatSessionStatus"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatSessionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ChatSessionStatus","text":"ChatSessionStatus"}],"role":"symbol","title":"chatSessionStatus","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"chatSessionStatus"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState(py)chatSessionStatus","roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatSessionStatus"},{"text":": ","kind":"text"},{"text":"ChatSessionStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ChatSessionStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The status of the current chat session."}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatstate\/chatsessionstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatstate\/chatsessionstatus"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/chatSessionStatus":{"title":"chatSessionStatus","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatSessionStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ChatSessionStatus","text":"ChatSessionStatus"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatSessionStatus","navigatorTitle":[{"text":"chatSessionStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatstate\/chatsessionstatus","abstract":[{"type":"text","text":"The status of the current chat session."}],"type":"topic","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"text":" is a model representation of the current chat session.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatstate","title":"ChatState","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatState"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus":{"navigatorTitle":[{"kind":"identifier","text":"ChatSessionStatus"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatsessionstatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatSessionStatus","kind":"identifier"}],"title":"ChatSessionStatus","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","abstract":[{"text":"Chat session status describes current state of the session","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"chatSessionStatus","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"chatSessionStatus"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ChatSessionStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","text":"ChatSessionStatus"},{"kind":"text","text":" "},{"text":"chatSessionStatus","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"chatSessionStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1chatSessionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1chatSessionStatus\/fragments","value":[{"kind":"identifier","text":"chatSessionStatus"}]},{"value":"ZDKChatState","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","value":[{"kind":"identifier","text":"ZDKChatState"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/title","op":"replace","value":"ChatSessionStatus"},{"value":[{"text":"ChatSessionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}