{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"initial","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","text":"ChatState","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/initial"},"metadata":{"role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initial"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","text":"ChatState","kind":"typeIdentifier"}],"title":"initial","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState(cpy)initial","symbolKind":"property","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"text":"initial","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatstate\/initial"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatstate\/initial"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"]]},"abstract":[{"text":"Empty chat state","type":"text"}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"text":" is a model representation of the current chat session.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatstate","title":"ChatState","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatState"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/initial":{"url":"\/documentation\/chatproviderssdk\/chatstate\/initial","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/initial","abstract":[{"text":"Empty chat state","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initial"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","text":"ChatState","kind":"typeIdentifier"}],"title":"initial","kind":"symbol","navigatorTitle":[{"text":"initial","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"initial"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"initial","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","text":"ZDKChatState","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"initial"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ZDKChatState","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","value":[{"text":"ZDKChatState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1initial\/title","value":"initial"},{"value":[{"text":"initial","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1initial\/fragments","op":"replace"}]}]}