{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"observeAccount","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","kind":"typeIdentifier","text":"Account","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider"]]},"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeAccount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", ("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken"}],"navigatorTitle":[{"text":"observeAccountWithIdentifier::","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","platforms":[],"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider(im)observeAccountWithIdentifier::","title":"observeAccount(identifier:_:)","role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"extendedModule":"ChatProvidersSDK"},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider\/observeAccount(identifier:_:)-1rpqg","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/accountprovider\/observeaccount(identifier:_:)-1rpqg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/accountprovider\/observeaccount(identifier:_:)-1rpqg"]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","url":"\/documentation\/chatproviderssdk\/accountprovider","navigatorTitle":[{"text":"AccountProvider","kind":"identifier"}],"title":"AccountProvider","kind":"symbol","abstract":[{"code":"ZDKChatAccountProvider","type":"codeVoice"},{"type":"text","text":" gives the ability to observe account updates."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccountProvider","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"abstract":[{"type":"text","text":"Unsubscribe from observers"}],"type":"topic","navigatorTitle":[{"text":"ObservationToken","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ObservationToken","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","title":"ObservationToken","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider/observeAccount(identifier:_:)-1rpqg":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"observeAccount","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", ("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"observeAccountWithIdentifier::","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider\/observeAccount(identifier:_:)-1rpqg","url":"\/documentation\/chatproviderssdk\/accountprovider\/observeaccount(identifier:_:)-1rpqg","title":"observeAccount(identifier:_:)","abstract":[],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","url":"\/documentation\/chatproviderssdk\/account","navigatorTitle":[{"text":"Account","kind":"identifier"}],"title":"Account","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKChatAccount"},{"text":" model stores information about the chat account,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as the current "},{"code":"accountStatus","type":"codeVoice"},{"text":" and the list of ","type":"text"},{"code":"Department","type":"codeVoice"},{"type":"text","text":"s associated with the account"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Account"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"observeAccountWithIdentifier::","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeAccountWithIdentifier::"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","kind":"typeIdentifier","text":"ZDKObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"},{"kind":"text","text":" *) "},{"text":"observeAccountWithIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"text":"void (^)(ZDKChatAccount *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ChatProvidersSDK@objc(cs)ZDKChatAccount)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/title","op":"replace","value":"ZDKChatAccountProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatAccountProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","value":"ZDKObservationToken","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","op":"replace","value":[{"text":"ZDKObservationToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider~1observeAccount(identifier:_:)-1rpqg\/title","value":"observeAccountWithIdentifier::"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider~1observeAccount(identifier:_:)-1rpqg\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeAccountWithIdentifier::"}],"op":"replace"},{"value":"ZDKChatAccount","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatAccount"}]}]}]}