{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider","text":"AccountProvider"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/accountprovider-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chat\/accountprovider-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Account Provider"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccountProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider"}],"title":"accountProvider","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(py)accountProvider","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"accountProvider"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider":{"role":"symbol","title":"AccountProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountProvider"}],"abstract":[{"type":"codeVoice","code":"ZDKChatAccountProvider"},{"type":"text","text":" gives the ability to observe account updates."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccountProvider"}],"url":"\/documentation\/chatproviderssdk\/accountprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/accountProvider-swift.property":{"role":"symbol","title":"accountProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccountProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider"}],"abstract":[{"type":"text","text":"Account Provider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accountProvider"}],"url":"\/documentation\/chatproviderssdk\/chat\/accountprovider-swift.property"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"role":"symbol","title":"Chat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"type":"codeVoice","code":"ChatProviderSDK"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"url":"\/documentation\/chatproviderssdk\/chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accountProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountProvider"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider","text":"ZDKChatAccountProvider"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accountProvider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/title","value":"ZDKChatAccountProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatAccountProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountProvider-swift.property\/title","value":"accountProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountProvider-swift.property\/fragments","value":[{"kind":"identifier","text":"accountProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}