{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders","text":"Providers"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/providers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chat\/providers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/providers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Grouping of Zendesk Chat’s providers"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Providers","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders"}],"title":"providers","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(py)providers","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"providers"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"role":"symbol","title":"Chat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"type":"codeVoice","code":"ChatProviderSDK"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"url":"\/documentation\/chatproviderssdk\/chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/providers":{"role":"symbol","title":"providers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Providers","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders"}],"abstract":[{"type":"text","text":"Grouping of Zendesk Chat’s providers"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/providers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"providers"}],"url":"\/documentation\/chatproviderssdk\/chat\/providers"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers":{"role":"symbol","title":"Providers","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Providers"}],"abstract":[{"type":"codeVoice","code":"ZDKChatProviders"},{"type":"text","text":" is a grouping of all the providers that allow you to, setup for push notifications,"},{"type":"text","text":" "},{"type":"text","text":"handle session updates, handle connection state, and interact with the APIs in other ways."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Providers"}],"url":"\/documentation\/chatproviderssdk\/providers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"providers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"providers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders","text":"ZDKChatProviders"},{"kind":"text","text":" * "},{"kind":"identifier","text":"providers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1providers\/title","value":"providers"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1providers\/fragments","value":[{"kind":"identifier","text":"providers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/title","value":"ZDKChatProviders"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/fragments","value":[{"kind":"identifier","text":"ZDKChatProviders"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}