{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData"]]},"abstract":[{"text":"Returns true if the push notification payload belongs to ","type":"text"},{"type":"codeVoice","code":"Chat"}],"metadata":{"symbolKind":"method","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"text":"isChatPushNotificationWithUserInfo:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isChatPushNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationData(cm)isChatPushNotificationWithUserInfo:","role":"symbol","roleHeading":"Type Method","title":"isChatPushNotification(userInfo:)"},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData\/isChatPushNotification(userInfo:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationdata\/ischatpushnotification(userinfo:)"]},{"paths":["\/documentation\/chatproviderssdk\/pushnotificationdata\/ischatpushnotification(userinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isChatPushNotification","kind":"identifier"},{"kind":"text","text":"("},{"text":"userInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Push notification payload"}]}],"name":"userInfo"}]}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationData":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData","abstract":[{"code":"PushNotificationData","type":"codeVoice"},{"text":" can be used to gather information about Chat related push notifications","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushNotificationData","kind":"identifier"}],"navigatorTitle":[{"text":"PushNotificationData","kind":"identifier"}],"title":"PushNotificationData","url":"\/documentation\/chatproviderssdk\/pushnotificationdata","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationData/isChatPushNotification(userInfo:)":{"abstract":[{"type":"text","text":"Returns true if the push notification payload belongs to "},{"code":"Chat","type":"codeVoice"}],"title":"isChatPushNotification(userInfo:)","navigatorTitle":[{"text":"isChatPushNotificationWithUserInfo:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData\/isChatPushNotification(userInfo:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatPushNotification"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationdata\/ischatpushnotification(userinfo:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"isChatPushNotificationWithUserInfo:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"isChatPushNotificationWithUserInfo:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"isChatPushNotificationWithUserInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"userInfo","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData\/title","value":"ZDKPushNotificationData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData\/fragments","value":[{"text":"ZDKPushNotificationData","kind":"identifier"}]},{"value":"isChatPushNotificationWithUserInfo:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData~1isChatPushNotification(userInfo:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"isChatPushNotificationWithUserInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData~1isChatPushNotification(userInfo:)\/fragments"}]}]}