{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatComment","interfaceLanguage":"swift"},"metadata":{"title":"ChatLogType.chatComment","symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ZDKChatLogTypeChatComment","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatComment","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType@ZDKChatLogTypeChatComment"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/chatcomment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/chatcomment"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatComment"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"]]},"kind":"symbol","abstract":[{"text":"Visitor left a comment about the chat","type":"text"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/chatComment":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"chatComment","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatComment","type":"topic","title":"ChatLogType.chatComment","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeChatComment"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatlogtype\/chatcomment","abstract":[{"text":"Visitor left a comment about the chat","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatlogtype","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLogType"}],"abstract":[{"text":"An enum of the message types that can be in sent\/received in a chat session","type":"text"}],"title":"ChatLogType","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKChatLogTypeChatComment","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKChatLogTypeChatComment","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKChatLogTypeChatComment","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ZDKChatLogTypeChatComment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatComment\/title"},{"value":[{"text":"ZDKChatLogTypeChatComment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatComment\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","value":"ZDKChatLogType","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatLogType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}