{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider\/didreceiveremotenotification(_:in:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider\/didreceiveremotenotification(_:in:)"]}],"sections":[],"metadata":{"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider(im)didReceiveRemoteNotification:in:","extendedModule":"ChatProvidersSDK","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didReceiveRemoteNotification","kind":"identifier"},{"kind":"text","text":"(["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}],"title":"didReceiveRemoteNotification(_:in:)","role":"symbol"},"abstract":[{"text":"Received push notification is processed by Chat SDK.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/didReceiveRemoteNotification(_:in:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"userInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary that contains information related to the remote notification"}]}]},{"name":"application","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}]}]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"inlineContent":[{"type":"text","text":"There are two types of chat notifications:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"chat.msg","type":"codeVoice"},{"text":" - received when a new chat message was sent from an agent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"chat.end"},{"text":" - received when the current chat session ends.","type":"text"}]}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushNotificationsProvider","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKPushNoticiationProvider"},{"type":"text","text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications."}],"type":"topic","kind":"symbol","title":"PushNotificationsProvider","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","navigatorTitle":[{"text":"PushNotificationsProvider","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/didReceiveRemoteNotification(_:in:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didReceiveRemoteNotification","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Received push notification is processed by Chat SDK."}],"type":"topic","kind":"symbol","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/didreceiveremotenotification(_:in:)","navigatorTitle":[{"kind":"identifier","text":"didReceiveRemoteNotification:in:"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/didReceiveRemoteNotification(_:in:)","title":"didReceiveRemoteNotification(_:in:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"didReceiveRemoteNotification:in:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"didReceiveRemoteNotification:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"text":" ","kind":"text"},{"text":"in:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"text":" *) ","kind":"text"},{"text":"application","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKPushNotificationsProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/title"},{"op":"replace","value":[{"text":"ZDKPushNotificationsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1didReceiveRemoteNotification(_:in:)\/title","value":"didReceiveRemoteNotification:in:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1didReceiveRemoteNotification(_:in:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}],"op":"replace"}]}]}