{"abstract":[{"type":"text","text":"Registers device token with Zendesk Chat"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerPushTokenString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"pushTokenString","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"pushTokenString","content":[{"type":"paragraph","inlineContent":[{"text":"device token received in ","type":"text"},{"code":"didRegisterForRemoteNotificationsWithDeviceToken","type":"codeVoice"},{"text":" after registration.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider(im)registerPushTokenString:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerPushTokenString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"text":"registerPushTokenString:","kind":"identifier"}],"role":"symbol","extendedModule":"ChatProvidersSDK","symbolKind":"method","title":"registerPushTokenString(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushTokenString(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider\/registerpushtokenstring(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider\/registerpushtokenstring(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/registerPushTokenString(_:)":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushTokenString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerPushTokenString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"registerPushTokenString(_:)","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/registerpushtokenstring(_:)","abstract":[{"text":"Registers device token with Zendesk Chat","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"registerPushTokenString:","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushNotificationsProvider","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKPushNoticiationProvider"},{"type":"text","text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications."}],"type":"topic","kind":"symbol","title":"PushNotificationsProvider","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","navigatorTitle":[{"text":"PushNotificationsProvider","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"registerPushTokenString:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"registerPushTokenString:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"registerPushTokenString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pushTokenString"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"registerPushTokenString:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1registerPushTokenString(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1registerPushTokenString(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerPushTokenString:"}],"op":"replace"},{"op":"replace","value":"ZDKPushNotificationsProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/fragments","value":[{"kind":"identifier","text":"ZDKPushNotificationsProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}