{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment\/localURL","interfaceLanguage":"swift"},"metadata":{"title":"localURL","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"localURL"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localURL","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachment(py)localURL"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatattachment\/localurl"]},{"paths":["\/documentation\/chatproviderssdk\/chatattachment\/localurl"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"localURL","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment"]]},"kind":"symbol","abstract":[{"type":"text","text":"The local "},{"code":"url","type":"codeVoice"},{"type":"text","text":" where the attachemt is stored"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachment":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAttachment"}],"url":"\/documentation\/chatproviderssdk\/chatattachment","kind":"symbol","title":"ChatAttachment","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","navigatorTitle":[{"text":"ChatAttachment","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatAttachment"},{"type":"text","text":" model, contains information about attachments that were sent or received"},{"text":" ","type":"text"},{"text":"by the visitor.","type":"text"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachment/localURL":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"localURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment\/localURL","type":"topic","title":"localURL","navigatorTitle":[{"kind":"identifier","text":"localURL"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatattachment\/localurl","abstract":[{"type":"text","text":"The local "},{"code":"url","type":"codeVoice"},{"type":"text","text":" where the attachemt is stored"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"localURL","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"localURL"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"localURL"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ZDKChatAttachment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/title"},{"value":[{"text":"ZDKChatAttachment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment~1localURL\/title","value":"localURL","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment~1localURL\/fragments","value":[{"text":"localURL","kind":"identifier"}]}]}]}