{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/attachmentmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/attachmentmessage"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/attachmentMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Chat attachment message"}],"metadata":{"role":"symbol","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType@ZDKChatLogTypeAttachmentMessage","navigatorTitle":[{"text":"ZDKChatLogTypeAttachmentMessage","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"title":"ChatLogType.attachmentMessage","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"attachmentMessage","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"attachmentMessage","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"url":"\/documentation\/chatproviderssdk\/chatlogtype","title":"ChatLogType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatLogType","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/attachmentMessage":{"kind":"symbol","abstract":[{"text":"Chat attachment message","type":"text"}],"navigatorTitle":[{"text":"ZDKChatLogTypeAttachmentMessage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/attachmentMessage","title":"ChatLogType.attachmentMessage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"attachmentMessage","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/attachmentmessage"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatLogTypeAttachmentMessage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ZDKChatLogTypeAttachmentMessage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"ZDKChatLogTypeAttachmentMessage","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","value":"ZDKChatLogType","op":"replace"},{"value":[{"text":"ZDKChatLogType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1attachmentMessage\/title","value":"ZDKChatLogTypeAttachmentMessage"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogTypeAttachmentMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1attachmentMessage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}