{"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"disconnected","kind":"identifier"}],"title":"ConnectionStatus.disconnected","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusDisconnected"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus@ZDKConnectionStatusDisconnected"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"disconnected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/disconnected","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/disconnected"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/disconnected"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ChatSession"},{"type":"text","text":" has disconnected. Can be caused by network connection, or a user ending"},{"type":"text","text":" "},{"type":"text","text":"the session with "},{"type":"codeVoice","code":"ChatSession.disconnect()"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/disconnected":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"disconnected","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/disconnected","title":"ConnectionStatus.disconnected","url":"\/documentation\/chatproviderssdk\/connectionstatus\/disconnected","type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ChatSession"},{"type":"text","text":" has disconnected. Can be caused by network connection, or a user ending"},{"type":"text","text":" "},{"type":"text","text":"the session with "},{"code":"ChatSession.disconnect()","type":"codeVoice"}],"navigatorTitle":[{"text":"ZDKConnectionStatusDisconnected","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"abstract":[{"type":"text","text":"Represents different states of the"},{"type":"codeVoice","code":"ChatSession"}],"navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionStatus","kind":"identifier"}],"title":"ConnectionStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKConnectionStatusDisconnected","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"ZDKConnectionStatusDisconnected"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKConnectionStatusDisconnected"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1disconnected\/title","value":"ZDKConnectionStatusDisconnected"},{"value":[{"text":"ZDKConnectionStatusDisconnected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1disconnected\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title","value":"ZDKConnectionStatus","op":"replace"},{"op":"replace","value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments"}]}]}