{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeConnectionStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus","text":"ConnectionStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(identifier:_:)-85u3e"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(identifier:_:)-85u3e"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-85u3e","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"observeConnectionStatusWithIdentifier::"}],"role":"symbol","title":"observeConnectionStatus(identifier:_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeConnectionStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ConnectionStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"symbolKind":"method","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKConnectionProvider(im)observeConnectionStatusWithIdentifier::","modules":[{"name":"ChatProvidersSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/observeConnectionStatus(identifier:_:)-85u3e":{"role":"symbol","title":"observeConnectionStatus(identifier:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeConnectionStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ConnectionStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-85u3e","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeConnectionStatusWithIdentifier::"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(identifier:_:)-85u3e"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"role":"symbol","title":"ConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionStatus"}],"abstract":[{"type":"text","text":"Represents different states of the"},{"type":"codeVoice","code":"ChatSession"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionStatus"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider":{"role":"symbol","title":"ConnectionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionProvider"}],"abstract":[{"type":"codeVoice","code":"ZDKConnectionProvider"},{"type":"text","text":" gives the ability to observe connection updates."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionProvider"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"role":"symbol","title":"ObservationToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"abstract":[{"type":"text","text":"Unsubscribe from observers"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"url":"\/documentation\/chatproviderssdk\/observationtoken"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"observeConnectionStatusWithIdentifier::"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeConnectionStatusWithIdentifier::"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ZDKObservationToken"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"observeConnectionStatusWithIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum ZDKConnectionStatus)","preciseIdentifier":"c:BFv(#$@M@ChatProvidersSDK@E@ZDKConnectionStatus)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1observeConnectionStatus(identifier:_:)-85u3e\/title","value":"observeConnectionStatusWithIdentifier::"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1observeConnectionStatus(identifier:_:)-85u3e\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeConnectionStatusWithIdentifier::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title","value":"ZDKConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/title","value":"ZDKConnectionProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","value":"ZDKObservationToken"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","value":[{"kind":"identifier","text":"ZDKObservationToken"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}