{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorPathTwo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathtwo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathtwo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This string will be placed in the second line of the visitor path."},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Zendesk Chat SDK v(ChatProvidersSDKVersionNumber)”"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorPathTwo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"visitorPathTwo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration(py)visitorPathTwo","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"visitorPathTwo"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/visitorPathTwo":{"role":"symbol","title":"visitorPathTwo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorPathTwo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"This string will be placed in the second line of the visitor path."},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Zendesk Chat SDK v(ChatProvidersSDKVersionNumber)”"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"visitorPathTwo"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathtwo"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration":{"role":"symbol","title":"ChatAPIConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAPIConfiguration"}],"abstract":[{"type":"text","text":"A set of configurations that are associated with each chat session."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatAPIConfiguration"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"visitorPathTwo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"visitorPathTwo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"visitorPathTwo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathTwo\/title","value":"visitorPathTwo"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathTwo\/fragments","value":[{"kind":"identifier","text":"visitorPathTwo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/title","value":"ZDKChatAPIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatAPIConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}