{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage\/description","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage"]]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatmessage\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatmessage\/description"]}],"abstract":[{"text":"A textual representation of this instance.","type":"text"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChatMessage(py)description","role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"description","roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMessage/description":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/chatproviderssdk\/chatmessage\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","abstract":[{"type":"text","text":"A textual representation of this instance."}],"kind":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMessage":{"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Chat message","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatmessage","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatMessage","kind":"identifier"}],"title":"ChatMessage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage~1description\/title","op":"replace","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage~1description\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/title","op":"replace","value":"ZDKChatMessage"},{"op":"replace","value":[{"text":"ZDKChatMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/fragments"}]}]}