{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSharedSecret"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidsharedsecret"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidsharedsecret"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidSharedSecret","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSharedSecret"}],"title":"AuthenticationErrorCode.invalidSharedSecret","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode@ZDKAuthenticationErrorCodeInvalidSharedSecret","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidSharedSecret"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidSharedSecret":{"role":"symbol","title":"AuthenticationErrorCode.invalidSharedSecret","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSharedSecret"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidSharedSecret","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidSharedSecret"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidsharedsecret"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"role":"symbol","title":"AuthenticationErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationErrorCode"}],"abstract":[{"type":"text","text":"Possible Authentication related error codes"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorCode"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAuthenticationErrorCodeInvalidSharedSecret"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidSharedSecret"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidSharedSecret"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidSharedSecret\/title","value":"ZDKAuthenticationErrorCodeInvalidSharedSecret"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidSharedSecret\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidSharedSecret"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title","value":"ZDKAuthenticationErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}