{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/initializing","interfaceLanguage":"swift"},"metadata":{"title":"ChatSessionStatus.initializing","symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ChatSessionStatusInitializing","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializing"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@E@ChatSessionStatus@ChatSessionStatusInitializing"},"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus\/initializing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus\/initializing"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"initializing","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus"]]},"kind":"symbol","abstract":[{"text":"Initialization status.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Chat hasn’t started yet"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus":{"abstract":[{"type":"text","text":"Chat session status describes current state of the session"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","role":"symbol","title":"ChatSessionStatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatSessionStatus"}],"navigatorTitle":[{"text":"ChatSessionStatus","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatsessionstatus","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/initializing":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"initializing","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/initializing","type":"topic","title":"ChatSessionStatus.initializing","navigatorTitle":[{"kind":"identifier","text":"ChatSessionStatusInitializing"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/initializing","abstract":[{"type":"text","text":"Initialization status."},{"type":"text","text":" "},{"type":"text","text":"Chat hasn’t started yet"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ChatSessionStatusInitializing"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ChatSessionStatusInitializing","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChatSessionStatusInitializing"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/title","value":"ChatSessionStatus","op":"replace"},{"value":[{"text":"ChatSessionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/fragments"},{"value":"ChatSessionStatusInitializing","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1initializing\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1initializing\/fragments","value":[{"text":"ChatSessionStatusInitializing","kind":"identifier"}],"op":"replace"}]}]}