{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bad","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating"]]},"kind":"symbol","abstract":[{"type":"text","text":"bad"}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/bad","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"case","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Case","title":"ZDKRating.bad","navigatorTitle":[{"kind":"identifier","text":"ZDKRatingBad"}],"role":"symbol","externalID":"c:@M@ChatProvidersSDK@E@ZDKRating@ZDKRatingBad","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bad","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/zdkrating\/bad"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/zdkrating\/bad"]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/bad":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/bad","abstract":[{"text":"bad","type":"text"}],"title":"ZDKRating.bad","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating\/bad","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bad","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKRatingBad"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","title":"ZDKRating","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKRating","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKRating","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating","abstract":[{"type":"text","text":"A rating that can be assigned to the chat"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ZDKRatingBad","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKRatingBad"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKRatingBad"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ZDKRatingBad","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1bad\/title"},{"value":[{"text":"ZDKRatingBad","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1bad\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/title","value":"ZDKRating","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/fragments","value":[{"kind":"identifier","text":"ZDKRating"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}