{"abstract":[{"type":"text","text":"Observe connection status updates. Specify a closure how the status should be handled"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(identifier:_:)-1lono"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"observeConnectionStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","kind":"typeIdentifier","text":"ObservableIdentifier"},{"kind":"text","text":" = .uuid(), "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","text":"ConnectionStatus","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"ObservableIdentifier to be exclusive, or unique","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"name":"completion","content":[{"inlineContent":[{"text":"Specify how to handle the ","type":"text"},{"type":"codeVoice","code":"ConnectionStatus"},{"text":" via closure.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ObservationToken"},{"text":" that can cancel the subscription to the ","type":"text"},{"code":"ConnectionStatus","type":"codeVoice"},{"type":"text","text":"."}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"title":"observeConnectionStatus(identifier:_:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"observeConnectionStatus"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ConnectionStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"role":"symbol","externalID":"s:16ChatProvidersSDK18ConnectionProviderC07observeD6Status10identifier_AA16ObservationTokenCAA20ObservableIdentifierO_yAA0dG0OctF"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-1lono","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionProvider"}],"title":"ConnectionProvider","navigatorTitle":[{"text":"ConnectionProvider","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ZDKConnectionProvider"},{"type":"text","text":" gives the ability to observe connection updates."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","url":"\/documentation\/chatproviderssdk\/connectionprovider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/observeConnectionStatus(identifier:_:)-1lono":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-1lono","title":"observeConnectionStatus(identifier:_:)","type":"topic","url":"\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(identifier:_:)-1lono","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"observeConnectionStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"text":", (","kind":"text"},{"kind":"typeIdentifier","text":"ConnectionStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"abstract":[{"type":"text","text":"Observe connection status updates. Specify a closure how the status should be handled"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConnectionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionStatus"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionstatus","abstract":[{"type":"text","text":"Represents different states of the"},{"type":"codeVoice","code":"ChatSession"}],"title":"ConnectionStatus","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"kind":"symbol","abstract":[{"type":"text","text":"Unsubscribe from observers"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"title":"ObservationToken"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservableIdentifier":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ObservableIdentifier","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ObservableIdentifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/observableidentifier","abstract":[{"type":"text","text":"Enum to specify how to identify an object that is subscribe to an observable"}],"title":"ObservableIdentifier","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/title","value":"ZDKConnectionProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/fragments","value":[{"text":"ZDKConnectionProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title","op":"replace","value":"ZDKConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments","value":[{"text":"ZDKConnectionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","value":"ZDKObservationToken","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","value":[{"text":"ZDKObservationToken","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}