{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat\/configuration-swift.type.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/configuration-swift.type.property"]}],"sections":[],"metadata":{"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(cpy)configuration","modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration","text":"ChatAPIConfiguration"}],"symbolKind":"property","roleHeading":"Type Property","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"title":"configuration","role":"symbol"},"abstract":[{"text":"Set configuration to start ","type":"text"},{"type":"codeVoice","code":"Chat"},{"text":" with pre-configured ","type":"text"},{"type":"codeVoice","code":"department"},{"type":"text","text":", "},{"type":"codeVoice","code":"visitorInfo"},{"type":"text","text":" and "},{"code":"tags","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.type.property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatAPIConfiguration","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"Department can be changed only before the ","type":"text"},{"type":"codeVoice","code":"Chat"},{"text":" has started. Changing the department during the ongoing ","type":"text"},{"code":"Chat","type":"codeVoice"},{"text":" is not allowed.","type":"text"}]}],"style":"note","type":"aside"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration":{"type":"topic","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAPIConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"ChatAPIConfiguration"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","abstract":[{"text":"A set of configurations that are associated with each chat session.","type":"text"}],"role":"symbol","title":"ChatAPIConfiguration"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"abstract":[{"code":"Chat","type":"codeVoice"},{"text":" is a singleton class of the ","type":"text"},{"type":"codeVoice","code":"ChatProviderSDK"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chat","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/configuration-swift.type.property":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"text":"ChatAPIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Set configuration to start ","type":"text"},{"code":"Chat","type":"codeVoice"},{"text":" with pre-configured ","type":"text"},{"type":"codeVoice","code":"department"},{"text":", ","type":"text"},{"code":"visitorInfo","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"tags"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/configuration-swift.type.property","title":"configuration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"configuration","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKChatAPIConfiguration","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration"},{"kind":"text","text":" * "},{"text":"configuration","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/title","value":"ZDKChatAPIConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/fragments","value":[{"kind":"identifier","text":"ZDKChatAPIConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat"},{"value":[{"text":"ZDKChat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.type.property\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.type.property\/fragments","value":[{"text":"configuration","kind":"identifier"}]}]}]}