{"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetIdentity"},{"kind":"text","text":"()"}],"symbolKind":"method","navigatorTitle":[{"text":"resetIdentity","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(im)resetIdentity","role":"symbol","title":"resetIdentity()","modules":[{"name":"ChatProvidersSDK"}],"platforms":[]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity()"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat\/resetidentity()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/resetidentity()"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetIdentity","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please use `resetIdentity(_ completion: (() -> Void)?)` instead"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Resets the visitor data to a clean state allowing a new visitor to chat","type":"text"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/resetIdentity()":{"navigatorTitle":[{"text":"resetIdentity","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetIdentity","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/chatproviderssdk\/chat\/resetidentity()","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity()","type":"topic","abstract":[{"text":"Resets the visitor data to a clean state allowing a new visitor to chat","type":"text"}],"title":"resetIdentity()","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"abstract":[{"code":"Chat","type":"codeVoice"},{"text":" is a singleton class of the ","type":"text"},{"type":"codeVoice","code":"ChatProviderSDK"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chat","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"resetIdentity","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resetIdentity","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"resetIdentity","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"resetIdentity","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity()\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"resetIdentity","kind":"identifier"}]},{"value":"ZDKChat","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title"},{"value":[{"text":"ZDKChat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","op":"replace"}]}]}