{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setIdentity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"authenticator","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(pl)ZDKJWTAuthenticator","text":"JWTAuthenticator"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setIdentityWithAuthenticator:"}],"modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(im)setIdentityWithAuthenticator:","title":"setIdentity(authenticator:)"},"abstract":[{"type":"text","text":"Set the authenticated user’s identity"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentity"},{"kind":"text","text":"("},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"text":"JWTAuthenticator","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(pl)ZDKJWTAuthenticator","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"authenticator","content":[{"inlineContent":[{"text":"Instance of the class that conforms to ","type":"text"},{"code":"JWTAuthenticator","type":"codeVoice"},{"text":" protocol","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/setIdentity(authenticator:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat\/setidentity(authenticator:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/setidentity(authenticator:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/setIdentity(authenticator:)":{"navigatorTitle":[{"text":"setIdentityWithAuthenticator:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setIdentity","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"authenticator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(pl)ZDKJWTAuthenticator","text":"JWTAuthenticator"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/setidentity(authenticator:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/setIdentity(authenticator:)","abstract":[{"type":"text","text":"Set the authenticated user’s identity"}],"type":"topic","title":"setIdentity(authenticator:)","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"abstract":[{"code":"Chat","type":"codeVoice"},{"text":" is a singleton class of the ","type":"text"},{"type":"codeVoice","code":"ChatProviderSDK"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chat","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/JWTAuthenticator":{"type":"topic","abstract":[{"text":"Protocol that an object that handles authentication should conform to. Called by the ","type":"text"},{"type":"codeVoice","code":"ChatSDK"},{"type":"text","text":" everytime authentication is required."}],"navigatorTitle":[{"kind":"identifier","text":"JWTAuthenticator"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator","kind":"symbol","url":"\/documentation\/chatproviderssdk\/jwtauthenticator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWTAuthenticator","kind":"identifier"}],"title":"JWTAuthenticator","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"setIdentityWithAuthenticator:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setIdentityWithAuthenticator:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"setIdentityWithAuthenticator:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<ZDKJWTAuthenticator>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ChatProvidersSDK@objc(pl)ZDKJWTAuthenticator"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"authenticator"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1setIdentity(authenticator:)\/title","value":"setIdentityWithAuthenticator:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"setIdentityWithAuthenticator:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1setIdentity(authenticator:)\/fragments","op":"replace"},{"value":"ZDKChat","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/title","value":"ZDKJWTAuthenticator"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/fragments","value":[{"kind":"identifier","text":"ZDKJWTAuthenticator"}],"op":"replace"}]}]}