{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"observeVisitorInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","kind":"typeIdentifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"observeVisitorInfo"},{"text":"((","kind":"text"},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"modules":[{"name":"ChatProvidersSDK"}],"platforms":[],"title":"observeVisitorInfo(_:)","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKProfileProvider(im)observeVisitorInfo:","symbolKind":"method","navigatorTitle":[{"text":"observeVisitorInfo:","kind":"identifier"}]},"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/observeVisitorInfo(_:)":{"title":"observeVisitorInfo(_:)","navigatorTitle":[{"text":"observeVisitorInfo:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeVisitorInfo"},{"text":"((","kind":"text"},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(_:)","abstract":[],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(_:)","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"title":"VisitorInfo","navigatorTitle":[{"text":"VisitorInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","abstract":[{"type":"text","text":"Visitor information that can be seen in the Chat dashboard"},{"text":" ","type":"text"},{"type":"text","text":"Contains "},{"type":"codeVoice","code":"name"},{"text":", ","type":"text"},{"code":"email","type":"codeVoice"},{"type":"text","text":", and "},{"type":"codeVoice","code":"phoneNumber"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VisitorInfo"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"title":"ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"kind":"symbol","abstract":[{"text":"Unsubscribe from observers","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","title":"ProfileProvider","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ProfileProvider","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKProfileProvider"},{"text":" contain APIs to update information about a visitor.","type":"text"},{"type":"text","text":" "},{"text":"Such as name, email, phone number, tags, and notes related to the visitor and their session.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/profileprovider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"observeVisitorInfo:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"observeVisitorInfo:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"ZDKObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"observeVisitorInfo:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(ZDKVisitorInfo *)","preciseIdentifier":"c:BFv(#*$@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo)"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"observeVisitorInfo:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1observeVisitorInfo(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1observeVisitorInfo(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"observeVisitorInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title","value":"ZDKVisitorInfo"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments","op":"replace","value":[{"text":"ZDKVisitorInfo","kind":"identifier"}]},{"value":"ZDKObservationToken","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKObservationToken"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title","op":"replace","value":"ZDKProfileProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","value":[{"text":"ZDKProfileProvider","kind":"identifier"}],"op":"replace"}]}]}