{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/trackVisitorPath(_:completion:)-5dvu1","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Send information about user events to the Zendesk Chat agent dashboard.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackVisitorPath","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"visitorPath","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorPath","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath","text":"VisitorPath","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath","kind":"typeIdentifier","text":"VisitorPath","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorPath"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"VisitorPath"},{"type":"text","text":" event"}],"type":"paragraph"}],"name":"visitorPath"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"Result<VisitorPath, DeliveryStatusError>"},{"type":"text","text":" closure to handle if update sent successfully. Default is "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"completion"}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"While chat is uninitialized, events will be buffered and sent to the server once the app is connected to the chat.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/profileprovider\/trackvisitorpath(_:completion:)-5dvu1"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider"]]},"metadata":{"symbolKind":"method","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","title":"trackVisitorPath(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"trackVisitorPath","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"VisitorPath","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"VisitorPath","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"externalID":"s:16ChatProvidersSDK15ProfileProviderC16trackVisitorPath_10completionyAA0gH0C_ys6ResultOyAgA19DeliveryStatusErrorOGcSgtF","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorPath":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VisitorPath","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorPath","title":"VisitorPath","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"VisitorPath"}],"url":"\/documentation\/chatproviderssdk\/visitorpath","type":"topic","abstract":[{"type":"text","text":"A Custom Update Event that can be seen in the agent dashboard."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/trackVisitorPath(_:completion:)-5dvu1":{"title":"trackVisitorPath(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackVisitorPath"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath","text":"VisitorPath","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath","text":"VisitorPath"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","text":"DeliveryStatusError","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"url":"\/documentation\/chatproviderssdk\/profileprovider\/trackvisitorpath(_:completion:)-5dvu1","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/trackVisitorPath(_:completion:)-5dvu1","abstract":[{"type":"text","text":"Send information about user events to the Zendesk Chat agent dashboard."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","title":"ProfileProvider","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ProfileProvider","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKProfileProvider"},{"text":" contain APIs to update information about a visitor.","type":"text"},{"type":"text","text":" "},{"text":"Such as name, email, phone number, tags, and notes related to the visitor and their session.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/profileprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DeliveryStatusError":{"url":"\/documentation\/chatproviderssdk\/deliverystatuserror","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","type":"topic","title":"DeliveryStatusError","navigatorTitle":[{"kind":"identifier","text":"DeliveryStatusError"}],"kind":"symbol","abstract":[{"type":"text","text":"Delivery status error describes the reason of a delivery failure"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryStatusError"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorPath\/title","value":"ZDKVisitorPath","op":"replace"},{"value":[{"text":"ZDKVisitorPath","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorPath\/fragments"},{"op":"replace","value":"ZDKProfileProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title"},{"op":"replace","value":[{"text":"ZDKProfileProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments"}]}]}