{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus\/offline","interfaceLanguage":"swift"},"metadata":{"title":"ZDKDepartmentStatus.offline","symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKDepartmentStatus@ZDKDepartmentStatusOffline","navigatorTitle":[{"kind":"identifier","text":"ZDKDepartmentStatusOffline"}],"modules":[{"name":"ChatProvidersSDK"}]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/offline"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/offline"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offline"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus"]]},"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus/offline":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus\/offline","type":"topic","title":"ZDKDepartmentStatus.offline","navigatorTitle":[{"kind":"identifier","text":"ZDKDepartmentStatusOffline"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/offline","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKDepartmentStatus","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKDepartmentStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","type":"topic","title":"ZDKDepartmentStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKDepartmentStatusOffline"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKDepartmentStatusOffline"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKDepartmentStatusOffline","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus~1offline\/title","value":"ZDKDepartmentStatusOffline"},{"value":[{"kind":"identifier","text":"ZDKDepartmentStatusOffline"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus~1offline\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/title","op":"replace","value":"ZDKDepartmentStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/fragments","value":[{"text":"ZDKDepartmentStatus","kind":"identifier"}],"op":"replace"}]}]}