{"kind":"symbol","abstract":[{"type":"text","text":"Get information about the state of the current chat."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatprovider\/getchatinfo(_:)-8xt3m"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getChatInfo"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"ChatInfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatInfo"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"completion","content":[{"inlineContent":[{"text":"block that is invoked once the ","type":"text"},{"type":"codeVoice","code":"getChatInfo"},{"type":"text","text":" request finishes."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is ongoing if the given "},{"type":"codeVoice","code":"ChatInfo"},{"text":" model’s ","type":"text"},{"code":"isChatting","type":"codeVoice"},{"text":" flag, is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/getChatInfo(_:)-8xt3m"},"sections":[],"metadata":{"role":"symbol","symbolKind":"method","title":"getChatInfo(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getChatInfo","kind":"identifier"},{"text":"((","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"ChatInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatInfo"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"externalID":"s:16ChatProvidersSDK0A8ProviderC03getA4Infoyyys6ResultOyAA0aF0Cs5Error_pGcF","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Instance Method"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"navigatorTitle":[{"text":"ChatProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatprovider","title":"ChatProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","abstract":[{"text":"The ","type":"text"},{"code":"ZDKChatProvider","type":"codeVoice"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatProvider","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatInfo":{"abstract":[{"type":"codeVoice","code":"ZDKChatInfo"},{"type":"text","text":" contains information about the chat session, such as if there is a chat ongoing."}],"kind":"symbol","type":"topic","role":"symbol","title":"ChatInfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatInfo","url":"\/documentation\/chatproviderssdk\/chatinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatInfo"}],"navigatorTitle":[{"kind":"identifier","text":"ChatInfo"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/getChatInfo(_:)-8xt3m":{"abstract":[{"type":"text","text":"Get information about the state of the current chat."}],"kind":"symbol","type":"topic","role":"symbol","title":"getChatInfo(_:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/getChatInfo(_:)-8xt3m","url":"\/documentation\/chatproviderssdk\/chatprovider\/getchatinfo(_:)-8xt3m","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getChatInfo","kind":"identifier"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"ChatInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKChatProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"text":"ZDKChatProvider","kind":"identifier"}]},{"op":"replace","value":"ZDKChatInfo","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatInfo\/fragments","value":[{"text":"ZDKChatInfo","kind":"identifier"}]}]}]}