{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/attachment","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachmentMessage(py)attachment","title":"attachment","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"attachment"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"attachment","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachment","text":"ChatAttachment"}],"modules":[{"name":"ChatProvidersSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Underlying attachment model"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"attachment","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","text":"ChatAttachment","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachment"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatattachmentmessage\/attachment"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatattachmentmessage\/attachment"]}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachment":{"abstract":[{"text":"The ","type":"text"},{"code":"ZDKChatAttachment","type":"codeVoice"},{"text":" model, contains information about attachments that were sent or received","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"by the visitor."}],"url":"\/documentation\/chatproviderssdk\/chatattachment","kind":"symbol","title":"ChatAttachment","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatAttachment","kind":"identifier"}],"navigatorTitle":[{"text":"ChatAttachment","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage":{"navigatorTitle":[{"kind":"identifier","text":"ChatAttachmentMessage"}],"abstract":[{"type":"text","text":"The Chat Log attachment"}],"url":"\/documentation\/chatproviderssdk\/chatattachmentmessage","role":"symbol","title":"ChatAttachmentMessage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAttachmentMessage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","type":"topic","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage/attachment":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Underlying attachment model"}],"navigatorTitle":[{"text":"attachment","kind":"identifier"}],"title":"attachment","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/attachment","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachment","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatAttachment","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachment"}],"url":"\/documentation\/chatproviderssdk\/chatattachmentmessage\/attachment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"attachment","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"attachment","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","text":"ZDKChatAttachment","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachment"},{"text":" * ","kind":"text"},{"text":"attachment","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/title","value":"ZDKChatAttachment"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/fragments","value":[{"kind":"identifier","text":"ZDKChatAttachment"}],"op":"replace"},{"value":"ZDKChatAttachmentMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/title"},{"op":"replace","value":[{"text":"ZDKChatAttachmentMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1attachment\/title","value":"attachment"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1attachment\/fragments","value":[{"text":"attachment","kind":"identifier"}]}]}]}