{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider\/chatmessagereceivednotification"]},{"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider\/chatmessagereceivednotification"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMessageReceivedNotification","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification"},{"text":".","kind":"text"},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider(cpy)ChatMessageReceivedNotification","navigatorTitle":[{"text":"ChatMessageReceivedNotification","kind":"identifier"}],"roleHeading":"Type Property","title":"ChatMessageReceivedNotification","symbolKind":"property"},"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"NSNotification.Name","type":"codeVoice"},{"text":" associated with the message received push notificiation","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessageReceivedNotification"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Name","preciseIdentifier":"c:@T@NSNotificationName"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/ChatMessageReceivedNotification","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/ChatMessageReceivedNotification":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessageReceivedNotification","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/ChatMessageReceivedNotification","title":"ChatMessageReceivedNotification","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessageReceivedNotification"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/chatmessagereceivednotification","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NSNotification.Name"},{"type":"text","text":" associated with the message received push notificiation"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsProvider"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","title":"PushNotificationsProvider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsProvider"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKPushNoticiationProvider"},{"type":"text","text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ChatMessageReceivedNotification","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"ChatMessageReceivedNotification","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"ChatMessageReceivedNotification"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1ChatMessageReceivedNotification\/title","value":"ChatMessageReceivedNotification"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1ChatMessageReceivedNotification\/fragments","value":[{"text":"ChatMessageReceivedNotification","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/title","value":"ZDKPushNotificationsProvider"},{"value":[{"text":"ZDKPushNotificationsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/fragments","op":"replace"}]}]}