{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/account\/departments"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/account\/departments"]}],"sections":[],"abstract":[{"code":"[Department]","type":"codeVoice"},{"type":"text","text":" in the chat instance"}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"departments","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"departments"},{"kind":"text","text":": ["},{"text":"Department","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment"},{"text":"]?","kind":"text"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount(py)departments","role":"symbol","title":"departments","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"departments","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","text":"Department"},{"kind":"text","text":"]?"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/departments"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Department"}],"title":"Department","abstract":[{"type":"text","text":"Department model contains id associated with the department,"},{"type":"text","text":" "},{"text":"the department name, and the current status of the department.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","type":"topic","navigatorTitle":[{"text":"Department","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/department"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"url":"\/documentation\/chatproviderssdk\/account","title":"Account","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","navigatorTitle":[{"text":"Account","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Account"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"ZDKChatAccount","type":"codeVoice"},{"text":" model stores information about the chat account,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as the current "},{"code":"accountStatus","type":"codeVoice"},{"text":" and the list of ","type":"text"},{"type":"codeVoice","code":"Department"},{"type":"text","text":"s associated with the account"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/departments":{"url":"\/documentation\/chatproviderssdk\/account\/departments","navigatorTitle":[{"kind":"identifier","text":"departments"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departments"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","text":"Department"},{"kind":"text","text":"]?"}],"abstract":[{"type":"codeVoice","code":"[Department]"},{"type":"text","text":" in the chat instance"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/departments","title":"departments","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"departments"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"departments"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<ZDKDepartment *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"departments"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/title","op":"replace","value":"ZDKDepartment"},{"value":[{"text":"ZDKDepartment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/fragments","op":"replace"},{"value":"ZDKChatAccount","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments","value":[{"text":"ZDKChatAccount","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1departments\/title","value":"departments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1departments\/fragments","value":[{"kind":"identifier","text":"departments"}],"op":"replace"}]}]}