{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"accountStatus","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus","text":"AccountStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"departments"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier","text":"Department","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department"},{"kind":"text","text":"]?)"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount(im)initWithAccountStatus:departments:","symbolKind":"init","modules":[{"name":"ChatProvidersSDK"}],"title":"init(accountStatus:departments:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus","text":"AccountStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"departments"},{"kind":"text","text":": ["},{"text":"Department","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithAccountStatus:departments:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/account\/init(accountstatus:departments:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/account\/init(accountstatus:departments:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/init(accountStatus:departments:)"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/init(accountStatus:departments:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accountStatus"},{"kind":"text","text":": "},{"text":"AccountStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"departments","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Department","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment"},{"text":"]?)","kind":"text"}],"title":"init(accountStatus:departments:)","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/init(accountStatus:departments:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithAccountStatus:departments:"}],"url":"\/documentation\/chatproviderssdk\/account\/init(accountstatus:departments:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Department"}],"title":"Department","abstract":[{"type":"text","text":"Department model contains id associated with the department,"},{"type":"text","text":" "},{"text":"the department name, and the current status of the department.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","type":"topic","navigatorTitle":[{"text":"Department","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/department"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"url":"\/documentation\/chatproviderssdk\/account","title":"Account","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","navigatorTitle":[{"text":"Account","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Account"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"ZDKChatAccount","type":"codeVoice"},{"text":" model stores information about the chat account,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as the current "},{"code":"accountStatus","type":"codeVoice"},{"text":" and the list of ","type":"text"},{"type":"codeVoice","code":"Department"},{"type":"text","text":"s associated with the account"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountStatus"}],"abstract":[{"type":"text","text":"Account Status"}],"navigatorTitle":[{"kind":"identifier","text":"AccountStatus"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","url":"\/documentation\/chatproviderssdk\/accountstatus","kind":"symbol","role":"symbol","title":"AccountStatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithAccountStatus:departments:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAccountStatus:departments:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAccountStatus:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus","text":"ZDKChatAccountStatus"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"accountStatus"},{"text":" ","kind":"text"},{"text":"departments:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<ZDKDepartment *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"departments"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1init(accountStatus:departments:)\/title","value":"initWithAccountStatus:departments:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithAccountStatus:departments:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1init(accountStatus:departments:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/title","op":"replace","value":"ZDKDepartment"},{"value":[{"text":"ZDKDepartment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title","value":"ZDKChatAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments","value":[{"kind":"identifier","text":"ZDKChatAccount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/title","value":"ZDKChatAccountStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/fragments","value":[{"kind":"identifier","text":"ZDKChatAccountStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}