{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus@ZDKDeliveryStatusPending","navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatusPending"}],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"case","title":"ZDKDeliveryStatus.pending"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pending"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/pending"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/zdkdeliverystatus\/pending"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/zdkdeliverystatus\/pending"]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKDeliveryStatus"}],"abstract":[{"text":"Delivery Status of the ","type":"text"},{"code":"ChatLog","type":"codeVoice"}],"url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus","title":"ZDKDeliveryStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatus"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/pending":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pending","kind":"identifier"}],"abstract":[],"url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/pending","title":"ZDKDeliveryStatus.pending","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/pending","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"ZDKDeliveryStatusPending","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKDeliveryStatusPending"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKDeliveryStatusPending"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKDeliveryStatusPending","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/title","value":"ZDKDeliveryStatus"},{"value":[{"kind":"identifier","text":"ZDKDeliveryStatus"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/fragments","op":"replace"},{"value":"ZDKDeliveryStatusPending","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1pending\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1pending\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKDeliveryStatusPending"}]}]}]}