{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode"]]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccesstoken"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccesstoken"]}],"sections":[],"metadata":{"externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode@ZDKAuthenticationErrorCodeInvalidAccessToken","modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidAccessToken"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidAccessToken","kind":"identifier"}],"title":"AuthenticationErrorCode.invalidAccessToken","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccessToken"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidAccessToken","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidAccessToken":{"navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidAccessToken","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccessToken","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccesstoken","title":"AuthenticationErrorCode.invalidAccessToken","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidAccessToken","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"kind":"symbol","title":"AuthenticationErrorCode","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationErrorCode","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"AuthenticationErrorCode","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","abstract":[{"type":"text","text":"Possible Authentication related error codes"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKAuthenticationErrorCodeInvalidAccessToken","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeInvalidAccessToken","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidAccessToken"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKAuthenticationErrorCodeInvalidAccessToken","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccessToken\/title"},{"value":[{"text":"ZDKAuthenticationErrorCodeInvalidAccessToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccessToken\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title","op":"replace","value":"ZDKAuthenticationErrorCode"},{"value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCode"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments","op":"replace"}]}]}