{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/tokenHasExpired","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/tokenhasexpired"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/tokenhasexpired"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenHasExpired","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeTokenHasExpired"}],"modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"AuthenticationErrorCode.tokenHasExpired","externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode@ZDKAuthenticationErrorCodeTokenHasExpired"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenHasExpired"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"kind":"symbol","title":"AuthenticationErrorCode","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationErrorCode","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"AuthenticationErrorCode","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","abstract":[{"type":"text","text":"Possible Authentication related error codes"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/tokenHasExpired":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenHasExpired"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeTokenHasExpired"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/tokenHasExpired","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/tokenhasexpired","title":"AuthenticationErrorCode.tokenHasExpired","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKAuthenticationErrorCodeTokenHasExpired"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeTokenHasExpired"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeTokenHasExpired"}]}],"kind":"declarations"}},{"value":"ZDKAuthenticationErrorCode","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCode"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1tokenHasExpired\/title","value":"ZDKAuthenticationErrorCodeTokenHasExpired","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1tokenHasExpired\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeTokenHasExpired","kind":"identifier"}]}]}]}