{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat\/configuration-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/configuration-swift.property"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration","kind":"typeIdentifier","text":"ChatAPIConfiguration"}],"modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"title":"configuration","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(py)configuration"},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.property","interfaceLanguage":"swift"},"abstract":[{"text":"Set configuration to start ","type":"text"},{"type":"codeVoice","code":"Chat"},{"type":"text","text":" with pre-configured "},{"code":"department","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"visitorInfo"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"tags"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","kind":"typeIdentifier","text":"ChatAPIConfiguration","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Department can be changed only before the "},{"type":"codeVoice","code":"Chat"},{"text":" has started. Changing the department during the ongoing ","type":"text"},{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is not allowed."}]}],"name":"Note","style":"note"}],"kind":"content"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"type":"codeVoice","code":"ChatProviderSDK"},{"type":"text","text":"."}],"type":"topic","title":"Chat","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration":{"role":"symbol","title":"ChatAPIConfiguration","abstract":[{"text":"A set of configurations that are associated with each chat session.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatAPIConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatAPIConfiguration"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/configuration-swift.property":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chat\/configuration-swift.property","abstract":[{"type":"text","text":"Set configuration to start "},{"type":"codeVoice","code":"Chat"},{"type":"text","text":" with pre-configured "},{"type":"codeVoice","code":"department"},{"text":", ","type":"text"},{"type":"codeVoice","code":"visitorInfo"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"tags"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.property","type":"topic","title":"configuration","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration","text":"ChatAPIConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"configuration","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration","text":"ZDKChatAPIConfiguration","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"configuration","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat","op":"replace"},{"value":[{"text":"ZDKChat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/title","op":"replace","value":"ZDKChatAPIConfiguration"},{"value":[{"kind":"identifier","text":"ZDKChatAPIConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/fragments"},{"value":"configuration","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.property\/title","op":"replace"},{"value":[{"kind":"identifier","text":"configuration"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.property\/fragments","op":"replace"}]}]}