{"kind":"symbol","abstract":[{"type":"text","text":"Whether a user is authenticated."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.property"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasIdentity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.property"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"hasIdentity"}],"title":"hasIdentity","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(py)hasIdentity","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasIdentity"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"type":"codeVoice","code":"ChatProviderSDK"},{"type":"text","text":"."}],"type":"topic","title":"Chat","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/hasIdentity-swift.property":{"abstract":[{"text":"Whether a user is authenticated.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","title":"hasIdentity","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.property","url":"\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasIdentity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"hasIdentity","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hasIdentity","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"hasIdentity"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"hasIdentity","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat"},{"value":[{"text":"ZDKChat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.property\/title","value":"hasIdentity","op":"replace"},{"value":[{"text":"hasIdentity","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.property\/fragments","op":"replace"}]}]}