{"abstract":[{"text":"Message came from an automated trigger","type":"text"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"trigger","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatParticipant@ZDKChatParticipantTrigger","navigatorTitle":[{"text":"ZDKChatParticipantTrigger","kind":"identifier"}],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"case","title":"ChatParticipant.trigger"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trigger"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatparticipant\/trigger"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatparticipant\/trigger"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/trigger"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/trigger":{"kind":"symbol","abstract":[{"text":"Message came from an automated trigger","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trigger"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatParticipantTrigger"}],"role":"symbol","type":"topic","title":"ChatParticipant.trigger","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/trigger","url":"\/documentation\/chatproviderssdk\/chatparticipant\/trigger"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant":{"title":"ChatParticipant","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatParticipant","kind":"identifier"}],"abstract":[{"text":"Who sent the message can be user\/agent\/trigger","type":"text"}],"navigatorTitle":[{"text":"ChatParticipant","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant","type":"topic","url":"\/documentation\/chatproviderssdk\/chatparticipant","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKChatParticipantTrigger"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatParticipantTrigger"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKChatParticipantTrigger","kind":"identifier"}]}],"kind":"declarations"}},{"value":"ZDKChatParticipantTrigger","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1trigger\/title"},{"value":[{"kind":"identifier","text":"ZDKChatParticipantTrigger"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1trigger\/fragments","op":"replace"},{"value":"ZDKChatParticipant","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/fragments","value":[{"text":"ZDKChatParticipant","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}