{"metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders(py)pushNotificationsProvider","navigatorTitle":[{"text":"pushNotificationsProvider","kind":"identifier"}],"title":"pushNotificationsProvider","modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushNotificationsProvider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider","text":"PushNotificationsProvider","kind":"typeIdentifier"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/pushNotificationsProvider","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"pushNotificationsProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider","text":"PushNotificationsProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/providers\/pushnotificationsprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/providers\/pushnotificationsprovider"]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers":{"kind":"symbol","url":"\/documentation\/chatproviderssdk\/providers","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Providers"}],"abstract":[{"type":"codeVoice","code":"ZDKChatProviders"},{"type":"text","text":" is a grouping of all the providers that allow you to, setup for push notifications,"},{"text":" ","type":"text"},{"text":"handle session updates, handle connection state, and interact with the APIs in other ways.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Providers"}],"title":"Providers"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider":{"abstract":[{"type":"text","text":"The "},{"code":"ZDKPushNoticiationProvider","type":"codeVoice"},{"type":"text","text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsProvider"}],"navigatorTitle":[{"text":"PushNotificationsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","role":"symbol","kind":"symbol","type":"topic","title":"PushNotificationsProvider","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers/pushNotificationsProvider":{"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"pushNotificationsProvider","kind":"identifier"}],"title":"pushNotificationsProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/pushNotificationsProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"pushNotificationsProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider","text":"PushNotificationsProvider","kind":"typeIdentifier"}],"url":"\/documentation\/chatproviderssdk\/providers\/pushnotificationsprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"pushNotificationsProvider","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"pushNotificationsProvider","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","text":"ZDKPushNotificationsProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"pushNotificationsProvider","kind":"identifier"}]}]}},{"value":"ZDKChatProviders","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatProviders"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/title","value":"ZDKPushNotificationsProvider","op":"replace"},{"op":"replace","value":[{"text":"ZDKPushNotificationsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/fragments"},{"op":"replace","value":"pushNotificationsProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1pushNotificationsProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1pushNotificationsProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"pushNotificationsProvider"}]}]}]}