{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatState"},{"kind":"text","text":": "},{"text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to observe updates of "},{"code":"ChatState","type":"codeVoice"},{"text":", please use the ","type":"text"},{"code":"observeChatState","type":"codeVoice"},{"text":" function.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/chatState"},"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatprovider\/chatstate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatprovider\/chatstate"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"chatState","kind":"identifier"},{"kind":"text","text":": "},{"text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"chatState"}],"modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider(py)chatState","title":"chatState"},"abstract":[{"type":"text","text":"Current chat state. Defaults to "},{"type":"codeVoice","code":"ChatState.initial"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatprovider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/chatState":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatState"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/chatState","title":"chatState","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/chatstate","navigatorTitle":[{"kind":"identifier","text":"chatState"}],"role":"symbol","abstract":[{"type":"text","text":"Current chat state. Defaults to "},{"type":"codeVoice","code":"ChatState.initial"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","title":"ChatState","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatState"}],"type":"topic","abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"text":" is a model representation of the current chat session.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"chatState"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"chatState","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"ZDKChatState","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"chatState","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKChatProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","op":"replace","value":[{"text":"ZDKChatProvider","kind":"identifier"}]},{"op":"replace","value":"chatState","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1chatState\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1chatState\/fragments","value":[{"text":"chatState","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKChatState","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title"},{"value":[{"kind":"identifier","text":"ZDKChatState"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}