{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"kind":"symbol","metadata":{"title":"sendOfflineForm(_:completion:)","platforms":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendOfflineForm"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","text":"OfflineForm","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","kind":"typeIdentifier","text":"OfflineForm"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"sendOfflineForm:completion:","kind":"identifier"}],"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChatProvider(im)sendOfflineForm:completion:","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendofflineform(_:completion:)-3ds3o"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendofflineform(_:completion:)-3ds3o"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendOfflineForm"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"offlineForm","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"OfflineForm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","kind":"typeIdentifier","text":"OfflineForm"},{"kind":"text","text":"?, "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-3ds3o"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendOfflineForm(_:completion:)-3ds3o":{"type":"topic","title":"sendOfflineForm(_:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendOfflineForm","kind":"identifier"},{"text":"(","kind":"text"},{"text":"OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"OfflineForm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"sendOfflineForm:completion:","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendofflineform(_:completion:)-3ds3o","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-3ds3o"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/OfflineForm":{"navigatorTitle":[{"text":"OfflineForm","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/offlineform","title":"OfflineForm","abstract":[{"text":"Offline form is formed from the given fields:","type":"text"},{"text":" ","type":"text"},{"text":"visitor info - name, email, phone","type":"text"},{"type":"text","text":" "},{"type":"text","text":"department - department id"},{"text":" ","type":"text"},{"type":"text","text":"message - visitor’s message"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineForm","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatprovider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendOfflineForm:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"sendOfflineForm:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendOfflineForm:"},{"text":"(","kind":"text"},{"text":"ZDKOfflineForm","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"offlineForm"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm#*$objc(cs)NSError)","text":"void (^)(ZDKOfflineForm *, NSError *)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendOfflineForm(_:completion:)-3ds3o\/title","value":"sendOfflineForm:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendOfflineForm(_:completion:)-3ds3o\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendOfflineForm:completion:"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/title","value":"ZDKOfflineForm","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/fragments","op":"replace","value":[{"text":"ZDKOfflineForm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","value":"ZDKChatProvider","op":"replace"},{"value":[{"text":"ZDKChatProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","op":"replace"}]}]}