{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings"]]},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings(im)initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileSizeLimit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":", ","kind":"text"},{"text":"isFileSendingEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"supportedFileTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"title":"init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileSizeLimit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"text":", ","kind":"text"},{"text":"isFileSendingEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"supportedFileTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatsettings\/init(filesizelimit:isfilesendingenabled:supportedfiletypes:)"]},{"paths":["\/documentation\/chatproviderssdk\/chatsettings\/init(filesizelimit:isfilesendingenabled:supportedfiletypes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fileSizeLimit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isFileSendingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"supportedFileTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"type":"topic","title":"init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)","abstract":[],"url":"\/documentation\/chatproviderssdk\/chatsettings\/init(filesizelimit:isfilesendingenabled:supportedfiletypes:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)","navigatorTitle":[{"kind":"identifier","text":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatSettings","kind":"identifier"}],"type":"topic","title":"ChatSettings","abstract":[{"type":"text","text":"The "},{"code":"ZDKChatSettings","type":"codeVoice"},{"type":"text","text":" model stores information about the chat account’s settings,"},{"type":"text","text":" "},{"type":"text","text":"such as the "},{"type":"codeVoice","code":"fileSizeLimit"},{"text":", whether attachments are enabled, and the list of accepted file extensions.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatsettings","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","navigatorTitle":[{"text":"ChatSettings","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithFileSizeLimit:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"text":") ","kind":"text"},{"text":"fileSizeLimit","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFileSendingEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isFileSendingEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"supportedFileTypes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"text":"supportedFileTypes","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:"}]},{"op":"replace","value":"ZDKChatSettings","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title"},{"value":[{"text":"ZDKChatSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments"}]}]}