{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatsettings\/supportedfiletypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatsettings\/supportedfiletypes"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/supportedFileTypes","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Lists array of supported file types - png, jpg, jpeg"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"supportedFileTypes"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings(py)supportedFileTypes","navigatorTitle":[{"kind":"identifier","text":"supportedFileTypes"}],"symbolKind":"property","title":"supportedFileTypes","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"supportedFileTypes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/supportedFileTypes":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportedFileTypes"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"type":"topic","title":"supportedFileTypes","abstract":[{"type":"text","text":"Lists array of supported file types - png, jpg, jpeg"}],"url":"\/documentation\/chatproviderssdk\/chatsettings\/supportedfiletypes","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/supportedFileTypes","navigatorTitle":[{"text":"supportedFileTypes","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatSettings","kind":"identifier"}],"type":"topic","title":"ChatSettings","abstract":[{"type":"text","text":"The "},{"code":"ZDKChatSettings","type":"codeVoice"},{"type":"text","text":" model stores information about the chat account’s settings,"},{"type":"text","text":" "},{"type":"text","text":"such as the "},{"type":"codeVoice","code":"fileSizeLimit"},{"text":", whether attachments are enabled, and the list of accepted file extensions.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatsettings","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","navigatorTitle":[{"text":"ChatSettings","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"supportedFileTypes","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"supportedFileTypes","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"supportedFileTypes","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"supportedFileTypes","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1supportedFileTypes\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1supportedFileTypes\/fragments","op":"replace","value":[{"text":"supportedFileTypes","kind":"identifier"}]},{"op":"replace","value":"ZDKChatSettings","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title"},{"value":[{"text":"ZDKChatSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}