{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"away"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@ChatProvidersSDK@E@ZDKDepartmentStatus@ZDKDepartmentStatusAway","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","navigatorTitle":[{"text":"ZDKDepartmentStatusAway","kind":"identifier"}],"symbolKind":"case","title":"ZDKDepartmentStatus.away","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"away","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus\/away","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/away"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/away"]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus/away":{"url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/away","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"away","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKDepartmentStatusAway"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus\/away","title":"ZDKDepartmentStatus.away","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus":{"abstract":[],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKDepartmentStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ZDKDepartmentStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","title":"ZDKDepartmentStatus","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKDepartmentStatusAway","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKDepartmentStatusAway"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKDepartmentStatusAway"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKDepartmentStatusAway","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus~1away\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus~1away\/fragments","value":[{"text":"ZDKDepartmentStatusAway","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/title","value":"ZDKDepartmentStatus"},{"op":"replace","value":[{"text":"ZDKDepartmentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}