{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathone"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathOne","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration"]]},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visitorPathOne"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration(py)visitorPathOne","navigatorTitle":[{"kind":"identifier","text":"visitorPathOne"}],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"property","title":"visitorPathOne"},"abstract":[{"text":"This string will be placed in the first line of the visitor path.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Direct Path” if not specified."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visitorPathOne","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration":{"role":"symbol","title":"ChatAPIConfiguration","abstract":[{"text":"A set of configurations that are associated with each chat session.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatAPIConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatAPIConfiguration"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/visitorPathOne":{"title":"visitorPathOne","type":"topic","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathone","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathOne","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visitorPathOne"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"visitorPathOne","kind":"identifier"}],"abstract":[{"type":"text","text":"This string will be placed in the first line of the visitor path."},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Direct Path” if not specified."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"visitorPathOne","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"visitorPathOne","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"visitorPathOne"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/title","value":"ZDKChatAPIConfiguration"},{"value":[{"kind":"identifier","text":"ZDKChatAPIConfiguration"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathOne\/title","op":"replace","value":"visitorPathOne"},{"value":[{"kind":"identifier","text":"visitorPathOne"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathOne\/fragments"}]}]}