{"variants":[{"paths":["\/documentation\/chatproviderssdk\/offlineform\/init(visitorinfo:departmentid:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/offlineform\/init(visitorinfo:departmentid:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm\/init(visitorInfo:departmentId:message:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithVisitorInfo:departmentId:message:"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"visitorInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"departmentId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm(im)initWithVisitorInfo:departmentId:message:","role":"symbol","symbolKind":"init","title":"init(visitorInfo:departmentId:message:)","modules":[{"name":"ChatProvidersSDK"}]},"abstract":[{"text":"Offline form initiatlizer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"visitorInfo"},{"text":": ","kind":"text"},{"text":"VisitorInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"kind":"text","text":"?, "},{"text":"departmentId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"visitor info","type":"text"}],"type":"paragraph"}],"name":"visitorInfo"},{"name":"departmentId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Department Name"}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"text":"Message","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","name":"Warning","style":"warning","content":[{"inlineContent":[{"type":"text","text":"Make sure the email field is filled in the "},{"type":"codeVoice","code":"VisitorInfo"},{"type":"text","text":", or the form will fail to send"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/OfflineForm/init(visitorInfo:departmentId:message:)":{"navigatorTitle":[{"text":"initWithVisitorInfo:departmentId:message:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm\/init(visitorInfo:departmentId:message:)","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/offlineform\/init(visitorinfo:departmentid:message:)","title":"init(visitorInfo:departmentId:message:)","abstract":[{"type":"text","text":"Offline form initiatlizer."}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"visitorInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier","text":"VisitorInfo"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"departmentId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/OfflineForm":{"navigatorTitle":[{"text":"OfflineForm","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/offlineform","title":"OfflineForm","abstract":[{"text":"Offline form is formed from the given fields:","type":"text"},{"text":" ","type":"text"},{"text":"visitor info - name, email, phone","type":"text"},{"type":"text","text":" "},{"type":"text","text":"department - department id"},{"text":" ","type":"text"},{"type":"text","text":"message - visitor’s message"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineForm","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"type":"topic","navigatorTitle":[{"text":"VisitorInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Visitor information that can be seen in the Chat dashboard","type":"text"},{"text":" ","type":"text"},{"text":"Contains ","type":"text"},{"type":"codeVoice","code":"name"},{"text":", ","type":"text"},{"code":"email","type":"codeVoice"},{"type":"text","text":", and "},{"type":"codeVoice","code":"phoneNumber"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"VisitorInfo","kind":"identifier"}],"title":"VisitorInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithVisitorInfo:departmentId:message:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithVisitorInfo:departmentId:message:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithVisitorInfo:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","kind":"typeIdentifier","text":"ZDKVisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"visitorInfo"},{"text":" ","kind":"text"},{"text":"departmentId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"departmentId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"message:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithVisitorInfo:departmentId:message:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm~1init(visitorInfo:departmentId:message:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithVisitorInfo:departmentId:message:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm~1init(visitorInfo:departmentId:message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/title","value":"ZDKOfflineForm"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/fragments","value":[{"text":"ZDKOfflineForm","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKVisitorInfo","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKVisitorInfo"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments"}]}]}