{"variants":[{"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/reconnecting"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/reconnecting"]}],"abstract":[{"type":"text","text":"The "},{"code":"ChatSession","type":"codeVoice"},{"type":"text","text":" is trying to reconnect to a chat that was already in session."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/reconnecting"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusReconnecting"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus@ZDKConnectionStatusReconnecting","title":"ConnectionStatus.reconnecting","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reconnecting","kind":"identifier"}],"roleHeading":"Case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reconnecting"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"abstract":[{"text":"Represents different states of the","type":"text"},{"type":"codeVoice","code":"ChatSession"}],"title":"ConnectionStatus","type":"topic","navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConnectionStatus","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/reconnecting":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/reconnecting","role":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKConnectionStatusReconnecting","kind":"identifier"}],"title":"ConnectionStatus.reconnecting","abstract":[{"type":"text","text":"The "},{"code":"ChatSession","type":"codeVoice"},{"type":"text","text":" is trying to reconnect to a chat that was already in session."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reconnecting"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/reconnecting"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKConnectionStatusReconnecting","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConnectionStatusReconnecting"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKConnectionStatusReconnecting"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title","value":"ZDKConnectionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments","op":"replace","value":[{"text":"ZDKConnectionStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1reconnecting\/title","value":"ZDKConnectionStatusReconnecting"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1reconnecting\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionStatusReconnecting"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}