{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","text":"ObservableIdentifier"},{"kind":"text","text":" = .uuid(), "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","text":"ChatState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservationToken"},{"type":"text","text":" that can cancel the subscription  to the "},{"type":"codeVoice","code":"ChatState"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ObservableIdentifier to be exclusive, or unique"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"block that executes everytime there is an update to the "},{"type":"codeVoice","code":"ChatState"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The conversation thread can be accessed through the "},{"type":"codeVoice","code":"logs"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(identifier:_:)-4bipl"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-4bipl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Observe changes of the current chat’s state"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"title":"observeChatState(identifier:_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:16ChatProvidersSDK0A8ProviderC07observeA5State10identifier_AA16ObservationTokenCAA20ObservableIdentifierO_yAA0aF0CctF","modules":[{"name":"ChatProvidersSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"role":"symbol","title":"ObservationToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"abstract":[{"type":"text","text":"Unsubscribe from observers"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"url":"\/documentation\/chatproviderssdk\/observationtoken"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"role":"symbol","title":"ChatState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatState"}],"abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"type":"text","text":" is a model representation of the current chat session."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatState"}],"url":"\/documentation\/chatproviderssdk\/chatstate"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservableIdentifier":{"role":"symbol","title":"ObservableIdentifier","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableIdentifier"}],"abstract":[{"type":"text","text":"Enum to specify how to identify an object that is subscribe to an observable"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ObservableIdentifier"}],"url":"\/documentation\/chatproviderssdk\/observableidentifier"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"role":"symbol","title":"ChatProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatProvider"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}],"url":"\/documentation\/chatproviderssdk\/chatprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/observeChatState(identifier:_:)-4bipl":{"role":"symbol","title":"observeChatState(identifier:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"abstract":[{"type":"text","text":"Observe changes of the current chat’s state"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-4bipl","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(identifier:_:)-4bipl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","value":"ZDKObservationToken"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","value":[{"kind":"identifier","text":"ZDKObservationToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","value":"ZDKChatState"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","value":[{"kind":"identifier","text":"ZDKChatState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","value":"ZDKChatProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}