{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/visitorinfo\/initial"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/visitorinfo\/initial"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo\/initial","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Empty chat state"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"}],"title":"initial","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo(cpy)initial","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"initial"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo/initial":{"role":"symbol","title":"initial","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"}],"abstract":[{"type":"text","text":"Empty chat state"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo\/initial","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initial"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo\/initial"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"role":"symbol","title":"VisitorInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisitorInfo"}],"abstract":[{"type":"text","text":"Visitor information that can be seen in the Chat dashboard"},{"type":"text","text":" "},{"type":"text","text":"Contains "},{"type":"codeVoice","code":"name"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", and "},{"type":"codeVoice","code":"phoneNumber"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VisitorInfo"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"initial"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"initial"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"ZDKVisitorInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"initial"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo~1initial\/title","value":"initial"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo~1initial\/fragments","value":[{"kind":"identifier","text":"initial"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title","value":"ZDKVisitorInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments","value":[{"kind":"identifier","text":"ZDKVisitorInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}