{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The completion is declared as follows: ("},{"type":"codeVoice","code":"JWT Token"},{"text":", ","type":"text"},{"code":"Error","type":"codeVoice"},{"type":"text","text":")"}],"type":"paragraph"}]}]}],"abstract":[{"text":"This function is called on behalf of ChatSDK every-time a new ","type":"text"},{"code":"JWT","type":"codeVoice"},{"type":"text","text":" token is required to authenticate your user."},{"type":"text","text":" "},{"type":"text","text":"Implement this function to generate the "},{"type":"codeVoice","code":"JWT"},{"type":"text","text":" token that Zendesk Chat can understand."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" with the successful "},{"code":"JWT","type":"codeVoice"},{"type":"text","text":" response or the error that might occur."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator\/getToken(_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/jwtauthenticator\/gettoken(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/jwtauthenticator\/gettoken(_:)"]}],"metadata":{"externalID":"c:@M@ChatProvidersSDK@objc(pl)ZDKJWTAuthenticator(im)getToken:","symbolKind":"method","modules":[{"name":"ChatProvidersSDK"}],"required":true,"roleHeading":"Instance Method","navigatorTitle":[{"text":"getToken:","kind":"identifier"}],"title":"getToken(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getToken"},{"kind":"text","text":"(("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/JWTAuthenticator":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator","kind":"symbol","url":"\/documentation\/chatproviderssdk\/jwtauthenticator","navigatorTitle":[{"text":"JWTAuthenticator","kind":"identifier"}],"abstract":[{"text":"Protocol that an object that handles authentication should conform to. Called by the ","type":"text"},{"code":"ChatSDK","type":"codeVoice"},{"type":"text","text":" everytime authentication is required."}],"title":"JWTAuthenticator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JWTAuthenticator"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/JWTAuthenticator/getToken(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getToken","kind":"identifier"},{"text":"((","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"required":true,"url":"\/documentation\/chatproviderssdk\/jwtauthenticator\/gettoken(_:)","abstract":[{"type":"text","text":"This function is called on behalf of ChatSDK every-time a new "},{"type":"codeVoice","code":"JWT"},{"type":"text","text":" token is required to authenticate your user."},{"text":" ","type":"text"},{"text":"Implement this function to generate the ","type":"text"},{"code":"JWT","type":"codeVoice"},{"type":"text","text":" token that Zendesk Chat can understand."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"completion"},{"text":" with the successful ","type":"text"},{"code":"JWT","type":"codeVoice"},{"type":"text","text":" response or the error that might occur."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator\/getToken(_:)","navigatorTitle":[{"text":"getToken:","kind":"identifier"}],"role":"symbol","type":"topic","title":"getToken(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getToken:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getToken:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getToken:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSString#*$objc(cs)NSError)","text":"void (^)(NSString *, NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/title","op":"replace","value":"ZDKJWTAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/fragments","value":[{"text":"ZDKJWTAuthenticator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator~1getToken(_:)\/title","value":"getToken:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"getToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator~1getToken(_:)\/fragments","op":"replace"}]}]}