{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatlog\/deliverystatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlog\/deliverystatus"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"deliveryStatus"}],"title":"deliveryStatus","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","extendedModule":"ChatProvidersSDK","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryStatus"},{"text":": ","kind":"text"},{"text":"ZDKDeliveryStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus"}],"platforms":[],"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChatLog(py)deliveryStatus"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/deliveryStatus"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deliveryStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus","text":"ZDKDeliveryStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus":{"kind":"symbol","type":"topic","title":"ZDKDeliveryStatus","url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus","abstract":[{"text":"Delivery Status of the ","type":"text"},{"type":"codeVoice","code":"ChatLog"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatus"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeliveryStatus"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Base class for chat log events that may occur in a chat session"}],"title":"ChatLog","url":"\/documentation\/chatproviderssdk\/chatlog","role":"symbol","navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/deliveryStatus":{"kind":"symbol","type":"topic","title":"deliveryStatus","url":"\/documentation\/chatproviderssdk\/chatlog\/deliverystatus","abstract":[],"role":"symbol","navigatorTitle":[{"text":"deliveryStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/deliveryStatus","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deliveryStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus","kind":"typeIdentifier","text":"ZDKDeliveryStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"deliveryStatus"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"deliveryStatus","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKDeliveryStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deliveryStatus"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/title","op":"replace","value":"ZDKDeliveryStatus"},{"value":[{"text":"ZDKDeliveryStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/fragments"},{"value":"ZDKChatLog","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","op":"replace","value":[{"text":"ZDKChatLog","kind":"identifier"}]},{"value":"deliveryStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1deliveryStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1deliveryStatus\/fragments","value":[{"text":"deliveryStatus","kind":"identifier"}]}]}]}