{"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatattachment\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatattachment\/name"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment\/name"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachment(py)name","navigatorTitle":[{"kind":"identifier","text":"name"}],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"property","title":"name"},"sections":[],"abstract":[{"code":"Name","type":"codeVoice"},{"type":"text","text":" of the attachment"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachment":{"abstract":[{"text":"The ","type":"text"},{"code":"ZDKChatAttachment","type":"codeVoice"},{"text":" model, contains information about attachments that were sent or received","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"by the visitor."}],"url":"\/documentation\/chatproviderssdk\/chatattachment","kind":"symbol","title":"ChatAttachment","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatAttachment","kind":"identifier"}],"navigatorTitle":[{"text":"ChatAttachment","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachment/name":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment\/name","type":"topic","navigatorTitle":[{"text":"name","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"Name"},{"type":"text","text":" of the attachment"}],"url":"\/documentation\/chatproviderssdk\/chatattachment\/name","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"name"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"name"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"name","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKChatAttachment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/fragments","op":"replace","value":[{"text":"ZDKChatAttachment","kind":"identifier"}]},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment~1name\/title"},{"value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment~1name\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}