{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/offlineform\/visitorinfo"]},{"paths":["\/documentation\/chatproviderssdk\/offlineform\/visitorinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm\/visitorInfo","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VisitorInfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"codeVoice","code":"VisitorInfo"}],"metadata":{"title":"visitorInfo","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorInfo"},{"text":": ","kind":"text"},{"text":"VisitorInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"visitorInfo","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm(py)visitorInfo","symbolKind":"property","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/OfflineForm":{"url":"\/documentation\/chatproviderssdk\/offlineform","title":"OfflineForm","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","navigatorTitle":[{"text":"OfflineForm","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineForm"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Offline form is formed from the given fields:"},{"type":"text","text":" "},{"text":"visitor info - name, email, phone","type":"text"},{"type":"text","text":" "},{"text":"department - department id","type":"text"},{"type":"text","text":" "},{"type":"text","text":"message - visitor’s message"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"title":"VisitorInfo","navigatorTitle":[{"text":"VisitorInfo","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","abstract":[{"type":"text","text":"Visitor information that can be seen in the Chat dashboard"},{"text":" ","type":"text"},{"type":"text","text":"Contains "},{"type":"codeVoice","code":"name"},{"text":", ","type":"text"},{"code":"email","type":"codeVoice"},{"type":"text","text":", and "},{"type":"codeVoice","code":"phoneNumber"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VisitorInfo"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/OfflineForm/visitorInfo":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm\/visitorInfo","title":"visitorInfo","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"visitorInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"visitorInfo","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/offlineform\/visitorinfo","abstract":[{"code":"VisitorInfo","type":"codeVoice"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"visitorInfo","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"visitorInfo"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ZDKVisitorInfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":" * ","kind":"text"},{"text":"visitorInfo","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/title","op":"replace","value":"ZDKOfflineForm"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/fragments","value":[{"text":"ZDKOfflineForm","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title","value":"ZDKVisitorInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments","value":[{"text":"ZDKVisitorInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm~1visitorInfo\/title","op":"replace","value":"visitorInfo"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm~1visitorInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"visitorInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}