{"abstract":[{"type":"text","text":"The "},{"code":"ChatSession","type":"codeVoice"},{"text":" has connected to the backend and is ready to send\/receive messages.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"connected","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKConnectionStatusConnected","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus@ZDKConnectionStatusConnected","role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"ConnectionStatus.connected","roleHeading":"Case","symbolKind":"case"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connected","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connected","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"]]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/connected"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/connected"]}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/connected":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connected","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ChatSession"},{"type":"text","text":" has connected to the backend and is ready to send\/receive messages."}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/connected","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connected","title":"ConnectionStatus.connected"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"title":"ConnectionStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","type":"topic","abstract":[{"text":"Represents different states of the","type":"text"},{"code":"ChatSession","type":"codeVoice"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConnectionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionStatus"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKConnectionStatusConnected","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKConnectionStatusConnected","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKConnectionStatusConnected","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ZDKConnectionStatusConnected","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1connected\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1connected\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}],"op":"replace"},{"value":"ZDKConnectionStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title"},{"value":[{"kind":"identifier","text":"ZDKConnectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments"}]}]}