{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider","text":"ConnectionProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/providers\/connectionprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/providers\/connectionprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/connectionProvider","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider"}],"title":"connectionProvider","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders(py)connectionProvider","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"connectionProvider"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers/connectionProvider":{"role":"symbol","title":"connectionProvider","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConnectionProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/connectionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"connectionProvider"}],"url":"\/documentation\/chatproviderssdk\/providers\/connectionprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers":{"role":"symbol","title":"Providers","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Providers"}],"abstract":[{"type":"codeVoice","code":"ZDKChatProviders"},{"type":"text","text":" is a grouping of all the providers that allow you to, setup for push notifications,"},{"type":"text","text":" "},{"type":"text","text":"handle session updates, handle connection state, and interact with the APIs in other ways."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Providers"}],"url":"\/documentation\/chatproviderssdk\/providers"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider":{"role":"symbol","title":"ConnectionProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionProvider"}],"abstract":[{"type":"codeVoice","code":"ZDKConnectionProvider"},{"type":"text","text":" gives the ability to observe connection updates."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionProvider"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"connectionProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"connectionProvider"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider","text":"ZDKConnectionProvider"},{"kind":"text","text":" * "},{"kind":"identifier","text":"connectionProvider"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1connectionProvider\/title","value":"connectionProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1connectionProvider\/fragments","value":[{"kind":"identifier","text":"connectionProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/title","value":"ZDKChatProviders"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/fragments","value":[{"kind":"identifier","text":"ZDKChatProviders"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/title","value":"ZDKConnectionProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}