{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.type.property"},"variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.type.property"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasIdentity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Whether a user is authenticated."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasIdentity","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"hasIdentity","kind":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(cpy)hasIdentity","title":"hasIdentity"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chat","navigatorTitle":[{"text":"Chat","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","title":"Chat","abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/hasIdentity-swift.type.property":{"abstract":[{"text":"Whether a user is authenticated.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.type.property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hasIdentity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.type.property","title":"hasIdentity","navigatorTitle":[{"text":"hasIdentity","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","value":"hasIdentity","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"hasIdentity"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hasIdentity"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}],"op":"replace"},{"value":"hasIdentity","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.type.property\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.type.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"hasIdentity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}