{"variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/notificationchatended"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chat\/notificationchatended"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"This notification is called when ","type":"text"},{"code":"Chat","type":"codeVoice"},{"type":"text","text":" session did end"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationChatEnded","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"title":"NotificationChatEnded","roleHeading":"Type Property","navigatorTitle":[{"text":"NotificationChatEnded","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"NotificationChatEnded","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}],"role":"symbol","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(cpy)NotificationChatEnded"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationChatEnded"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier","text":"NSNotification"},{"kind":"text","text":"."},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chat","navigatorTitle":[{"text":"Chat","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","title":"Chat","abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/NotificationChatEnded":{"abstract":[{"text":"This notification is called when ","type":"text"},{"code":"Chat","type":"codeVoice"},{"type":"text","text":" session did end"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationChatEnded","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"NotificationChatEnded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/notificationchatended","title":"NotificationChatEnded","navigatorTitle":[{"kind":"identifier","text":"NotificationChatEnded"}],"role":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"NotificationChatEnded","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"NotificationChatEnded"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"NotificationChatEnded","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat","op":"replace"},{"op":"replace","value":[{"text":"ZDKChat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments"},{"op":"replace","value":"NotificationChatEnded","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationChatEnded\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationChatEnded\/fragments","value":[{"text":"NotificationChatEnded","kind":"identifier"}]}]}]}