{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKAuthenticationErrorCode) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationErrorCode","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"],"kind":"relationships"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationErrorCode","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorCode"}],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"enum","title":"AuthenticationErrorCode"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/externalUserIdHasChanged","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalServerError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccessToken","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccountKey","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidEmail","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidSharedSecret","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/networkError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/tokenHasExpired"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/RawRepresentable-Implementations"]}],"abstract":[{"type":"text","text":"Possible Authentication related error codes"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/tokenHasExpired":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/tokenHasExpired","type":"topic","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeTokenHasExpired","kind":"identifier"}],"abstract":[],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/tokenhasexpired","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenHasExpired"}],"title":"AuthenticationErrorCode.tokenHasExpired"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidAccountKey":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidAccountKey","kind":"identifier"}],"abstract":[],"title":"AuthenticationErrorCode.invalidAccountKey","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidAccountKey","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccountKey","kind":"symbol","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccountkey","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/networkError":{"role":"symbol","title":"AuthenticationErrorCode.networkError","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/networkError","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeNetworkError","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/networkerror","kind":"symbol","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidSharedSecret":{"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidsharedsecret","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidSharedSecret"}],"role":"symbol","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidSharedSecret","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidSharedSecret","title":"AuthenticationErrorCode.invalidSharedSecret","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/Equatable-Implementations":{"abstract":[],"kind":"article","type":"topic","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/externalUserIdHasChanged":{"abstract":[],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/externaluseridhaschanged","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/externalUserIdHasChanged","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged","kind":"identifier"}],"title":"AuthenticationErrorCode.externalUserIdHasChanged","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"externalUserIdHasChanged","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"role":"symbol","title":"AuthenticationErrorCode","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationErrorCode"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorCode"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","kind":"symbol","abstract":[{"type":"text","text":"Possible Authentication related error codes"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/internalError":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/internalerror","type":"topic","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInternalError","kind":"identifier"}],"title":"AuthenticationErrorCode.internalError","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalError","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/internalServerError":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalServerError","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInternalServerError"}],"abstract":[],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/internalservererror","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerError"}],"title":"AuthenticationErrorCode.internalServerError"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/init(rawValue:)":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"title":"init(rawValue:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidName":{"abstract":[],"type":"topic","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidname","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidName","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidName","kind":"identifier"}],"title":"AuthenticationErrorCode.invalidName","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidName","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidEmail":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidEmail","type":"topic","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidEmail","kind":"identifier"}],"abstract":[],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidemail","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidEmail","kind":"identifier"}],"title":"AuthenticationErrorCode.invalidEmail"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/RawRepresentable-Implementations":{"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/rawrepresentable-implementations","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidAccessToken":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccessToken","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidAccessToken","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidAccessToken","kind":"identifier"}],"title":"AuthenticationErrorCode.invalidAccessToken","role":"symbol","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccesstoken"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"ZDKAuthenticationErrorCode","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ZDKAuthenticationErrorCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"ZDKAuthenticationErrorCode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/externalUserIdHasChanged","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalServerError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccessToken","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccountKey","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidEmail","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidSharedSecret","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/networkError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/tokenHasExpired"],"title":"Enumeration Cases"}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKAuthenticationErrorCode","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1tokenHasExpired\/title","value":"ZDKAuthenticationErrorCodeTokenHasExpired"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1tokenHasExpired\/fragments","op":"replace","value":[{"text":"ZDKAuthenticationErrorCodeTokenHasExpired","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccountKey\/title","value":"ZDKAuthenticationErrorCodeInvalidAccountKey"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccountKey\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeInvalidAccountKey","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1networkError\/title","value":"ZDKAuthenticationErrorCodeNetworkError"},{"value":[{"text":"ZDKAuthenticationErrorCodeNetworkError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1networkError\/fragments"},{"op":"replace","value":"ZDKAuthenticationErrorCodeInvalidSharedSecret","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidSharedSecret\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidSharedSecret\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeInvalidSharedSecret","kind":"identifier"}],"op":"replace"},{"value":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1externalUserIdHasChanged\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1externalUserIdHasChanged\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged","kind":"identifier"}],"op":"replace"},{"value":"ZDKAuthenticationErrorCode","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments","op":"replace","value":[{"text":"ZDKAuthenticationErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1internalError\/title","op":"replace","value":"ZDKAuthenticationErrorCodeInternalError"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1internalError\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInternalError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1internalServerError\/title","op":"replace","value":"ZDKAuthenticationErrorCodeInternalServerError"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1internalServerError\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInternalServerError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidName\/title","value":"ZDKAuthenticationErrorCodeInvalidName","op":"replace"},{"value":[{"text":"ZDKAuthenticationErrorCodeInvalidName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidName\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidEmail\/title","op":"replace","value":"ZDKAuthenticationErrorCodeInvalidEmail"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidEmail\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeInvalidEmail","kind":"identifier"}],"op":"replace"},{"value":"ZDKAuthenticationErrorCodeInvalidAccessToken","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccessToken\/title"},{"value":[{"text":"ZDKAuthenticationErrorCodeInvalidAccessToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccessToken\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}