{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKChatState) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatState"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"Can gather information about the "},{"type":"codeVoice","code":"agents"},{"type":"text","text":" in the session, the visitor’s "},{"type":"codeVoice","code":"queuePosition"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"what "},{"type":"codeVoice","code":"status"},{"type":"text","text":" the chat is in, and the list of "},{"type":"codeVoice","code":"logs"},{"type":"text","text":" in the session"}],"type":"paragraph"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"text":" is a model representation of the current chat session.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-8f7ix"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/agents","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatId","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatSessionStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/comment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/department","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/isChatting","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/logs","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/queuePosition","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/rating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/ratingValue"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/isEqual(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/log(withId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/initial"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatstate"]},{"paths":["\/documentation\/chatproviderssdk\/chatstate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"ChatState","kind":"identifier"}],"symbolKind":"class","title":"ChatState","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Class","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"type":"text","text":" is a model representation of the current chat session."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatState"}],"type":"topic","title":"ChatState","url":"\/documentation\/chatproviderssdk\/chatstate","role":"symbol","navigatorTitle":[{"text":"ChatState","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-8f7ix":{"role":"symbol","type":"topic","abstract":[],"title":"init(agents:isChatting:chatId:department:logs:queue:comment:rating:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-8f7ix","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"agents","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","text":"Agent","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"isChatting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"chatId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"department"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier","text":"Department"},{"text":"?, ","kind":"text"},{"text":"logs","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ChatLog","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog"},{"kind":"text","text":"], "},{"text":"queue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"comment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rating"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK6RatingO","text":"Rating","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/chatproviderssdk\/chatstate\/init(agents:ischatting:chatid:department:logs:queue:comment:rating:)-8f7ix"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/description":{"kind":"symbol","abstract":[],"type":"topic","role":"symbol","title":"description","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/description","url":"\/documentation\/chatproviderssdk\/chatstate\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/queuePosition":{"kind":"symbol","abstract":[{"type":"text","text":"Queue position"}],"type":"topic","role":"symbol","title":"queuePosition","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/queuePosition","url":"\/documentation\/chatproviderssdk\/chatstate\/queueposition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"queuePosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QueuePosition","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKQueuePosition","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"queuePosition"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/isChatting":{"abstract":[{"type":"text","text":"Whether the chat session is active. If "},{"type":"codeVoice","code":"false"},{"type":"text","text":" then the chat has ended."}],"kind":"symbol","type":"topic","role":"symbol","title":"isChatting","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/isChatting","url":"\/documentation\/chatproviderssdk\/chatstate\/ischatting","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatting"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isChatting","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/logs":{"kind":"symbol","abstract":[{"type":"text","text":"Array of ChatLogs that have occured in the chat. eg. Member join\/leave, attachments"}],"type":"topic","role":"symbol","title":"logs","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/logs","url":"\/documentation\/chatproviderssdk\/chatstate\/logs","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logs","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","kind":"typeIdentifier","text":"ChatLog"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"logs"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/debugDescription":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/debugDescription","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","title":"debugDescription","url":"\/documentation\/chatproviderssdk\/chatstate\/debugdescription","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}]},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/rating":{"kind":"symbol","abstract":[{"type":"text","text":"The chat rating"}],"type":"topic","role":"symbol","title":"rating","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/rating","url":"\/documentation\/chatproviderssdk\/chatstate\/rating","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rating"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK6RatingO","text":"Rating","kind":"typeIdentifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/initial":{"kind":"symbol","abstract":[{"text":"Empty chat state","type":"text"}],"type":"topic","role":"symbol","title":"initial","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/initial","url":"\/documentation\/chatproviderssdk\/chatstate\/initial","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","text":"ChatState"}],"navigatorTitle":[{"kind":"identifier","text":"initial"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"text":"Agent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isChatting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"chatId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"department","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier","text":"Department"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"logs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatLog","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog"},{"kind":"text","text":"], "},{"text":"queue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"comment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rating","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"text":")","kind":"text"}],"abstract":[],"title":"init(agents:isChatting:chatId:department:logs:queue:comment:rating:)","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd","kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatstate\/init(agents:ischatting:chatid:department:logs:queue:comment:rating:)-2metd","navigatorTitle":[{"kind":"identifier","text":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/department":{"kind":"symbol","abstract":[{"type":"text","text":"Selected department"}],"type":"topic","role":"symbol","title":"department","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/department","url":"\/documentation\/chatproviderssdk\/chatstate\/department","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"department"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier","text":"Department"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"department","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/chatSessionStatus":{"kind":"symbol","abstract":[{"type":"text","text":"The status of the current chat session."}],"type":"topic","role":"symbol","title":"chatSessionStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatSessionStatus","url":"\/documentation\/chatproviderssdk\/chatstate\/chatsessionstatus","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatSessionStatus"},{"kind":"text","text":": "},{"text":"ChatSessionStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ChatSessionStatus","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"chatSessionStatus"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/chatId":{"kind":"symbol","abstract":[{"type":"text","text":"Chat session id"}],"type":"topic","role":"symbol","title":"chatId","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatId","url":"\/documentation\/chatproviderssdk\/chatstate\/chatid","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"chatId"}]},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/agents":{"kind":"symbol","abstract":[{"code":"[Agent]","type":"codeVoice"},{"type":"text","text":" assigned to the channel"}],"type":"topic","role":"symbol","title":"agents","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/agents","url":"\/documentation\/chatproviderssdk\/chatstate\/agents","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"agents"},{"kind":"text","text":": ["},{"text":"Agent","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"agents","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/isEqual(_:)":{"kind":"symbol","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"type":"topic","role":"symbol","title":"isEqual(_:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/isEqual(_:)","url":"\/documentation\/chatproviderssdk\/chatstate\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/comment":{"kind":"symbol","abstract":[{"type":"text","text":"The chat comment"}],"type":"topic","role":"symbol","title":"comment","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/comment","url":"\/documentation\/chatproviderssdk\/chatstate\/comment","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"comment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"comment","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/log(withId:)":{"title":"log(withId:)","url":"\/documentation\/chatproviderssdk\/chatstate\/log(withid:)","abstract":[{"type":"text","text":"Returns log with given message id"}],"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","text":"ChatLog"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/log(withId:)","navigatorTitle":[{"kind":"identifier","text":"logWithId:"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/ratingValue":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/ratingValue","type":"topic","navigatorTitle":[{"text":"ratingValue","kind":"identifier"}],"abstract":[{"text":"The chat rating","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatstate\/ratingvalue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ratingValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating","text":"ZDKRating","kind":"typeIdentifier"}],"title":"ratingValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatState"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"ZDKChatState"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKChatState"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/agents","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatId","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/chatSessionStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/comment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/department","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/isChatting","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/logs","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/queuePosition","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/ratingValue"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/isEqual(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/log(withId:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/initial"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKChatState","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","value":"ZDKChatState","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatState"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","value":"queuePosition","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1queuePosition\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1queuePosition\/fragments","value":[{"text":"queuePosition","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1isChatting\/title","value":"isChatting"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1isChatting\/fragments","value":[{"kind":"identifier","text":"isChatting"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1logs\/title","value":"logs","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1logs\/fragments","value":[{"kind":"identifier","text":"logs"}]},{"value":"debugDescription","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1debugDescription\/title"},{"value":[{"text":"debugDescription","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1debugDescription\/fragments"},{"value":"initial","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1initial\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1initial\/fragments","value":[{"text":"initial","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd\/title","value":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"department","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1department\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1department\/fragments","op":"replace","value":[{"kind":"identifier","text":"department"}]},{"value":"chatSessionStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1chatSessionStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1chatSessionStatus\/fragments","value":[{"kind":"identifier","text":"chatSessionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1chatId\/title","value":"chatId"},{"value":[{"text":"chatId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1chatId\/fragments"},{"value":"agents","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1agents\/title"},{"op":"replace","value":[{"kind":"identifier","text":"agents"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1agents\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1isEqual(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1comment\/title","value":"comment"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1comment\/fragments","value":[{"text":"comment","kind":"identifier"}],"op":"replace"},{"value":"logWithId:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1log(withId:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logWithId:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1log(withId:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1ratingValue\/title","value":"ratingValue","op":"replace"},{"value":[{"text":"ratingValue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1ratingValue\/fragments"}]}]}