{"abstract":[{"type":"text","text":"The "},{"code":"ZDKProfileProvider","type":"codeVoice"},{"type":"text","text":" contain APIs to update information about a visitor."},{"text":" ","type":"text"},{"type":"text","text":"Such as name, email, phone number, tags, and notes related to the visitor and their session."}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKProfileProvider) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProfileProvider"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/profileprovider"]},{"paths":["\/documentation\/chatproviderssdk\/profileprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/visitorInfo"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/addTags(_:completion:)-49cts","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/addTags(_:completion:)-939r","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/appendNote(_:completion:)-4ft0p","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/appendNote(_:completion:)-uzaf","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(identifier:_:)-1i9ex","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(identifier:_:)-54w36","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/removeTags(_:completion:)-4n2ur","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/removeTags(_:completion:)-4toas","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setNote(_:completion:)-7gtkz","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setNote(_:completion:)-iwf6","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setVisitorInfo(_:completion:)-6i2jp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setVisitorInfo(_:completion:)-9b7v0","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/trackVisitorPath(_:completion:)-5dvu1","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/trackVisitorPath(_:completion:)-65dht"]}],"metadata":{"title":"ProfileProvider","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileProvider"}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"ProfileProvider","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ChatProvidersSDK"}]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/setVisitorInfo(_:completion:)-9b7v0":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setVisitorInfo(_:completion:)-9b7v0","role":"symbol","url":"\/documentation\/chatproviderssdk\/profileprovider\/setvisitorinfo(_:completion:)-9b7v0","title":"setVisitorInfo(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setVisitorInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"kind":"symbol","abstract":[{"type":"text","text":"Update Visitor Information using "},{"code":"VisitorInfo","type":"codeVoice"},{"type":"text","text":" model."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/addTags(_:completion:)-939r":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/addTags(_:completion:)-939r","role":"symbol","url":"\/documentation\/chatproviderssdk\/profileprovider\/addtags(_:completion:)-939r","title":"addTags(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addTags"},{"text":"([","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","kind":"typeIdentifier","text":"DeliveryStatusError"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Add a list of tags to the visitor profile."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/trackVisitorPath(_:completion:)-65dht":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/trackVisitorPath(_:completion:)-65dht","type":"topic","navigatorTitle":[{"text":"trackVisitorPath:completion:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/chatproviderssdk\/profileprovider\/trackvisitorpath(_:completion:)-65dht","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackVisitorPath"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"VisitorPath","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath","kind":"typeIdentifier","text":"VisitorPath"},{"kind":"text","text":"?, "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"title":"trackVisitorPath(_:completion:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/visitorInfo":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/visitorInfo","navigatorTitle":[{"text":"visitorInfo","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/profileprovider\/visitorinfo","title":"visitorInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"visitorInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Current "},{"code":"VisitorInfo","type":"codeVoice"},{"text":" model. Defaults to ","type":"text"},{"type":"codeVoice","code":"VisitorInfo.initial"},{"type":"text","text":"."}]},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/setVisitorInfo(_:completion:)-6i2jp":{"abstract":[],"title":"setVisitorInfo(_:completion:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"setVisitorInfo:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setVisitorInfo(_:completion:)-6i2jp","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setVisitorInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"VisitorInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"url":"\/documentation\/chatproviderssdk\/profileprovider\/setvisitorinfo(_:completion:)-6i2jp"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/removeTags(_:completion:)-4n2ur":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeTags:completion:"}],"title":"removeTags(_:completion:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/removeTags(_:completion:)-4n2ur","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTags"},{"kind":"text","text":"(["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ((["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"url":"\/documentation\/chatproviderssdk\/profileprovider\/removetags(_:completion:)-4n2ur"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/observeVisitorInfo(_:)":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(_:)","url":"\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(_:)","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"observeVisitorInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeVisitorInfo","kind":"identifier"},{"text":"((","kind":"text"},{"text":"VisitorInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"title":"observeVisitorInfo(_:)","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"role":"symbol","type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKProfileProvider"},{"text":" contain APIs to update information about a visitor.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Such as name, email, phone number, tags, and notes related to the visitor and their session."}],"navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"title":"ProfileProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ProfileProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/profileprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/trackVisitorPath(_:completion:)-5dvu1":{"abstract":[{"text":"Send information about user events to the Zendesk Chat agent dashboard.","type":"text"}],"title":"trackVisitorPath(_:completion:)","url":"\/documentation\/chatproviderssdk\/profileprovider\/trackvisitorpath(_:completion:)-5dvu1","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/trackVisitorPath(_:completion:)-5dvu1","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackVisitorPath","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath","kind":"typeIdentifier","text":"VisitorPath"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"VisitorPath","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorPath"},{"text":", ","kind":"text"},{"text":"DeliveryStatusError","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?)","kind":"text"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/setNote(_:completion:)-7gtkz":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"setNote(_:completion:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setNote(_:completion:)-7gtkz","url":"\/documentation\/chatproviderssdk\/profileprovider\/setnote(_:completion:)-7gtkz","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setNote"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"setNote:completion:","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/appendNote(_:completion:)-uzaf":{"abstract":[{"type":"text","text":"Append notes to the visitor profile."}],"type":"topic","url":"\/documentation\/chatproviderssdk\/profileprovider\/appendnote(_:completion:)-uzaf","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/appendNote(_:completion:)-uzaf","title":"appendNote(_:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"appendNote","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","kind":"typeIdentifier","text":"DeliveryStatusError"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/setNote(_:completion:)-iwf6":{"title":"setNote(_:completion:)","url":"\/documentation\/chatproviderssdk\/profileprovider\/setnote(_:completion:)-iwf6","abstract":[{"type":"text","text":"Set visitor note, this will overwrite previous notes"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setNote(_:completion:)-iwf6","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNote","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/appendNote(_:completion:)-4ft0p":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendNote"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/appendNote(_:completion:)-4ft0p","url":"\/documentation\/chatproviderssdk\/profileprovider\/appendnote(_:completion:)-4ft0p","navigatorTitle":[{"kind":"identifier","text":"appendNote:completion:"}],"title":"appendNote(_:completion:)","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/removeTags(_:completion:)-4toas":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/removeTags(_:completion:)-4toas","type":"topic","abstract":[{"type":"text","text":"Remove a list of tags from the"}],"url":"\/documentation\/chatproviderssdk\/profileprovider\/removetags(_:completion:)-4toas","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTags"},{"text":"([","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<[","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"text":"DeliveryStatusError","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"title":"removeTags(_:completion:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/observeVisitorInfo(identifier:_:)-1i9ex":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(identifier:_:)-1i9ex","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(identifier:_:)-1i9ex","navigatorTitle":[{"kind":"identifier","text":"observeVisitorInfoWithIdentifier::"}],"title":"observeVisitorInfo(identifier:_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"observeVisitorInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", ("},{"text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}]},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/addTags(_:completion:)-49cts":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/addTags(_:completion:)-49cts","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addTags:completion:"}],"abstract":[],"url":"\/documentation\/chatproviderssdk\/profileprovider\/addtags(_:completion:)-49cts","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addTags","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (([","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"title":"addTags(_:completion:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/observeVisitorInfo(identifier:_:)-54w36":{"title":"observeVisitorInfo(identifier:_:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Observe changes of the current "},{"code":"VisitorInfo","type":"codeVoice"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(identifier:_:)-54w36","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"observeVisitorInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", ("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","kind":"typeIdentifier","text":"ObservationToken"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(identifier:_:)-54w36"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKProfileProvider","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKProfileProvider"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKProfileProvider","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/visitorInfo"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/addTags(_:completion:)-49cts","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/appendNote(_:completion:)-4ft0p","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(identifier:_:)-1i9ex","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/removeTags(_:completion:)-4n2ur","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setNote(_:completion:)-7gtkz","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setVisitorInfo(_:completion:)-6i2jp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/trackVisitorPath(_:completion:)-65dht"]}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKProfileProvider"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"op":"replace"},{"value":"trackVisitorPath:completion:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1trackVisitorPath(_:completion:)-65dht\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"trackVisitorPath:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1trackVisitorPath(_:completion:)-65dht\/fragments","op":"replace"},{"value":"visitorInfo","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1visitorInfo\/title"},{"value":[{"kind":"identifier","text":"visitorInfo"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1visitorInfo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1setVisitorInfo(_:completion:)-6i2jp\/title","value":"setVisitorInfo:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1setVisitorInfo(_:completion:)-6i2jp\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setVisitorInfo:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1removeTags(_:completion:)-4n2ur\/title","value":"removeTags:completion:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1removeTags(_:completion:)-4n2ur\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeTags:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1observeVisitorInfo(_:)\/title","value":"observeVisitorInfo:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1observeVisitorInfo(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"observeVisitorInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title","op":"replace","value":"ZDKProfileProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","value":[{"kind":"identifier","text":"ZDKProfileProvider"}]},{"op":"replace","value":"setNote:completion:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1setNote(_:completion:)-7gtkz\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1setNote(_:completion:)-7gtkz\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setNote:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1appendNote(_:completion:)-4ft0p\/title","value":"appendNote:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"appendNote:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1appendNote(_:completion:)-4ft0p\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1observeVisitorInfo(identifier:_:)-1i9ex\/title","value":"observeVisitorInfoWithIdentifier::"},{"value":[{"kind":"text","text":"- "},{"text":"observeVisitorInfoWithIdentifier::","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1observeVisitorInfo(identifier:_:)-1i9ex\/fragments"},{"value":"addTags:completion:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1addTags(_:completion:)-49cts\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1addTags(_:completion:)-49cts\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addTags:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}