{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/profileprovider\/visitorinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/profileprovider\/visitorinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/visitorInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"VisitorInfo"},{"type":"text","text":" model. Defaults to "},{"type":"codeVoice","code":"VisitorInfo.initial"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"}],"title":"visitorInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider(py)visitorInfo","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"visitorInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/visitorInfo":{"role":"symbol","title":"visitorInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"}],"abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"VisitorInfo"},{"type":"text","text":" model. Defaults to "},{"type":"codeVoice","code":"VisitorInfo.initial"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/visitorInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"visitorInfo"}],"url":"\/documentation\/chatproviderssdk\/profileprovider\/visitorinfo"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"role":"symbol","title":"ProfileProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileProvider"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKProfileProvider"},{"type":"text","text":" contain APIs to update information about a visitor."},{"type":"text","text":" "},{"type":"text","text":"Such as name, email, phone number, tags, and notes related to the visitor and their session."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"url":"\/documentation\/chatproviderssdk\/profileprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"role":"symbol","title":"VisitorInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisitorInfo"}],"abstract":[{"type":"text","text":"Visitor information that can be seen in the Chat dashboard"},{"type":"text","text":" "},{"type":"text","text":"Contains "},{"type":"codeVoice","code":"name"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"type":"text","text":", and "},{"type":"codeVoice","code":"phoneNumber"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VisitorInfo"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"visitorInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"visitorInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"ZDKVisitorInfo"},{"kind":"text","text":" * "},{"kind":"identifier","text":"visitorInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1visitorInfo\/title","value":"visitorInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1visitorInfo\/fragments","value":[{"kind":"identifier","text":"visitorInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title","value":"ZDKProfileProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","value":[{"kind":"identifier","text":"ZDKProfileProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title","value":"ZDKVisitorInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments","value":[{"kind":"identifier","text":"ZDKVisitorInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}