{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/offline","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/online"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/description"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKChatAccountStatus) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AccountStatus","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"metadata":{"navigatorTitle":[{"text":"AccountStatus","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountStatus"}],"title":"AccountStatus","roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/accountstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/accountstatus"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Account Status"}],"references":{"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus/description":{"kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/accountstatus\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/description","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus/Equatable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/chatproviderssdk\/accountstatus\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/Equatable-Implementations"},"doc://com.zendesk.ChatProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus/init(rawValue:)":{"kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/accountstatus\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","role":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/init(rawValue:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus/offline":{"navigatorTitle":[{"kind":"identifier","text":"ZDKChatAccountStatusOffline"}],"kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/accountstatus\/offline","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"offline","kind":"identifier"}],"title":"AccountStatus.offline","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/offline","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus/RawRepresentable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/chatproviderssdk\/accountstatus\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/RawRepresentable-Implementations","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus/online":{"navigatorTitle":[{"kind":"identifier","text":"ZDKChatAccountStatusOnline"}],"kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/accountstatus\/online","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"online"}],"title":"AccountStatus.online","role":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/online"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus":{"abstract":[{"type":"text","text":"Account Status"}],"navigatorTitle":[{"text":"AccountStatus","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/accountstatus","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccountStatus","kind":"identifier"}],"title":"AccountStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"ZDKChatAccountStatus","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatAccountStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKChatAccountStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/offline","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/online"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKChatAccountStatus"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus~1offline\/title","value":"ZDKChatAccountStatusOffline","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus~1offline\/fragments","value":[{"text":"ZDKChatAccountStatusOffline","kind":"identifier"}],"op":"replace"},{"value":"ZDKChatAccountStatusOnline","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus~1online\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatAccountStatusOnline"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus~1online\/fragments"},{"value":"ZDKChatAccountStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatAccountStatus"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/fragments"}]}]}