{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chaterror"]},{"paths":["\/documentation\/chatproviderssdk\/chaterror"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Potential errors returned from the ChatProviderSDK"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/chatIsNotInitialized","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/disconnected"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/errorCode","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/errorUserInfo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/localizedDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/recoverySuggestion"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/errorDomain-22s3e"],"title":"Type Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/CustomNSError-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/LocalizedError-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/RawRepresentable-Implementations"],"generated":true}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"title":"ChatError","modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@E@ChatError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum"},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/10Foundation13CustomNSErrorP","doc:\/\/com.zendesk.ChatProvidersSDK\/10Foundation14LocalizedErrorP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/s5ErrorP","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY","doc:\/\/com.zendesk.ChatProvidersSDK\/s8SendableP"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"chatIsNotInitialized"},{"type":"text","text":" "},{"type":"text","text":"Will be thrown if the Chat instance isn’t initialized before initializing "},{"type":"codeVoice","code":"ChatEngine"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"disconnected","type":"codeVoice"},{"text":" ","type":"text"},{"text":"Will be emitted when a request is attempted to be sent, but the connection state is disconnected.","type":"text"}]}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/chatproviderssdk\/chaterror\/init(rawvalue:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/init(rawValue:)","title":"init(rawValue:)","type":"topic","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s8SendableP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/localizedDescription":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/localizedDescription","abstract":[{"type":"text","text":"Retrieve the localized description for this error."}],"title":"localizedDescription","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/chatproviderssdk\/chaterror\/localizeddescription","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/CustomNSError-Implementations":{"url":"\/documentation\/chatproviderssdk\/chaterror\/customnserror-implementations","type":"topic","title":"CustomNSError Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/CustomNSError-Implementations","kind":"article"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/disconnected":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/disconnected","url":"\/documentation\/chatproviderssdk\/chaterror\/disconnected","title":"ChatError.disconnected","type":"topic","abstract":[{"text":"Chat is disconnected","type":"text"}],"navigatorTitle":[{"text":"ChatErrorDisconnected","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/s5ErrorP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/errorUserInfo":{"url":"\/documentation\/chatproviderssdk\/chaterror\/erroruserinfo","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/errorUserInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorUserInfo"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"kind":"symbol","title":"errorUserInfo","type":"topic","abstract":[{"type":"text","text":"The user-info dictionary."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/errorDomain-22s3e":{"abstract":[{"text":"The domain of the error.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/errorDomain-22s3e","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/chatproviderssdk\/chaterror\/errordomain-22s3e","title":"errorDomain","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/LocalizedError-Implementations":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/LocalizedError-Implementations","url":"\/documentation\/chatproviderssdk\/chaterror\/localizederror-implementations","role":"collectionGroup","type":"topic","title":"LocalizedError Implementations","kind":"article"},"doc://com.zendesk.ChatProvidersSDK/10Foundation13CustomNSErrorP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/10Foundation13CustomNSErrorP","title":"Foundation.CustomNSError","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/Equatable-Implementations":{"url":"\/documentation\/chatproviderssdk\/chaterror\/equatable-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","kind":"article"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/recoverySuggestion":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/recoverySuggestion","url":"\/documentation\/chatproviderssdk\/chaterror\/recoverysuggestion","title":"recoverySuggestion","type":"topic","abstract":[{"text":"A localized message describing how one might recover from the failure.","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/chatIsNotInitialized":{"url":"\/documentation\/chatproviderssdk\/chaterror\/chatisnotinitialized","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/chatIsNotInitialized","abstract":[{"text":"Chat was not initialized","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"chatIsNotInitialized","kind":"identifier"}],"title":"ChatError.chatIsNotInitialized","kind":"symbol","navigatorTitle":[{"text":"ChatErrorChatIsNotInitialized","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError":{"url":"\/documentation\/chatproviderssdk\/chaterror","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"title":"ChatError","type":"topic","abstract":[{"type":"text","text":"Potential errors returned from the ChatProviderSDK"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/errorCode":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/errorCode","title":"errorCode","url":"\/documentation\/chatproviderssdk\/chaterror\/errorcode","type":"topic","abstract":[{"type":"text","text":"The error code within the given domain."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/RawRepresentable-Implementations":{"url":"\/documentation\/chatproviderssdk\/chaterror\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ChatError","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ChatError"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/chatIsNotInitialized","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/disconnected"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"ChatErrorDisconnected","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError~1disconnected\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError~1disconnected\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatErrorDisconnected"}]},{"op":"replace","value":"ChatErrorChatIsNotInitialized","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError~1chatIsNotInitialized\/title"},{"value":[{"text":"ChatErrorChatIsNotInitialized","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError~1chatIsNotInitialized\/fragments"},{"value":"ChatError","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError\/title","op":"replace"},{"value":[{"text":"ChatError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}