{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@ChatProvidersSDK@objc(pl)ZDKJWTAuthenticator","navigatorTitle":[{"kind":"identifier","text":"JWTAuthenticator"}],"symbolKind":"protocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWTAuthenticator","kind":"identifier"}],"title":"JWTAuthenticator","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Protocol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKJWTAuthenticator) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JWTAuthenticator","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/jwtauthenticator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/jwtauthenticator"]}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol that an object that handles authentication should conform to. Called by the "},{"type":"codeVoice","code":"ChatSDK"},{"type":"text","text":" everytime authentication is required."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator\/getToken(_:)"],"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/JWTAuthenticator/getToken(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getToken"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"getToken:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This function is called on behalf of ChatSDK every-time a new ","type":"text"},{"code":"JWT","type":"codeVoice"},{"text":" token is required to authenticate your user.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Implement this function to generate the "},{"type":"codeVoice","code":"JWT"},{"text":" token that Zendesk Chat can understand.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Call "},{"code":"completion","type":"codeVoice"},{"type":"text","text":" with the successful "},{"type":"codeVoice","code":"JWT"},{"text":" response or the error that might occur.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator\/getToken(_:)","type":"topic","required":true,"title":"getToken(_:)","url":"\/documentation\/chatproviderssdk\/jwtauthenticator\/gettoken(_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/JWTAuthenticator":{"url":"\/documentation\/chatproviderssdk\/jwtauthenticator","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator","abstract":[{"type":"text","text":"Protocol that an object that handles authentication should conform to. Called by the "},{"type":"codeVoice","code":"ChatSDK"},{"type":"text","text":" everytime authentication is required."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"JWTAuthenticator","kind":"identifier"}],"title":"JWTAuthenticator","kind":"symbol","navigatorTitle":[{"text":"JWTAuthenticator","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"ZDKJWTAuthenticator","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKJWTAuthenticator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKJWTAuthenticator"}]},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator\/getToken(_:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKJWTAuthenticator","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"getToken:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator~1getToken(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getToken:"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator~1getToken(_:)\/fragments","op":"replace"},{"value":"ZDKJWTAuthenticator","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/title"},{"value":[{"text":"ZDKJWTAuthenticator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/fragments"}]}]}