{"abstract":[{"type":"codeVoice","code":"ZDKSettingsProvider"},{"type":"text","text":" gives the ability to observe settings updates."}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/settings"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-1534y","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-9o16i"],"title":"Instance Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"metadata":{"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","navigatorTitle":[{"text":"SettingsProvider","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"ChatProvidersSDK"}],"title":"SettingsProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsProvider"}],"roleHeading":"Class","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKSettingsProvider) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SettingsProvider","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/settingsprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/settingsprovider"]}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider/observeChatSettings(identifier:_:)-1534y":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(identifier:_:)-1534y","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-1534y","abstract":[{"text":"Observe chat settings model","type":"text"}],"title":"observeChatSettings(identifier:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"observeChatSettingsWithIdentifier::","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"observeChatSettings","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","text":"ChatSettings"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken"}]},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider/settings":{"abstract":[{"type":"text","text":"Current "},{"type":"codeVoice","code":"Settings"},{"text":" model. Defaults to ","type":"text"},{"type":"codeVoice","code":"ChatSettings.initial"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/settings","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"settings","kind":"identifier"},{"kind":"text","text":": "},{"text":"ChatSettings","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"settings"}],"url":"\/documentation\/chatproviderssdk\/settingsprovider\/settings","kind":"symbol","type":"topic","title":"settings"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SettingsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","title":"SettingsProvider","url":"\/documentation\/chatproviderssdk\/settingsprovider","type":"topic","abstract":[{"type":"codeVoice","code":"ZDKSettingsProvider"},{"type":"text","text":" gives the ability to observe settings updates."}],"navigatorTitle":[{"kind":"identifier","text":"SettingsProvider"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider/observeChatSettings(_:)":{"abstract":[{"type":"text","text":"Observe chat settings model"}],"navigatorTitle":[{"text":"observeChatSettings:","kind":"identifier"}],"title":"observeChatSettings(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"observeChatSettings","kind":"identifier"},{"text":"((","kind":"text"},{"text":"ChatSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(_:)","url":"\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider/observeChatSettings(identifier:_:)-9o16i":{"abstract":[{"type":"text","text":"Observe chat settings model"}],"type":"topic","title":"observeChatSettings(identifier:_:)","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-9o16i","url":"\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(identifier:_:)-9o16i","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeChatSettings","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ChatSettings","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}]},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ZDKSettingsProvider","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKSettingsProvider"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ZDKSettingsProvider"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/settings"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-1534y"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKSettingsProvider"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace"},{"op":"replace","value":"observeChatSettingsWithIdentifier::","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(identifier:_:)-1534y\/title"},{"value":[{"kind":"text","text":"- "},{"text":"observeChatSettingsWithIdentifier::","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(identifier:_:)-1534y\/fragments","op":"replace"},{"op":"replace","value":"settings","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1settings\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1settings\/fragments","value":[{"text":"settings","kind":"identifier"}]},{"value":"ZDKSettingsProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/title","op":"replace"},{"op":"replace","value":[{"text":"ZDKSettingsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(_:)\/title","value":"observeChatSettings:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"observeChatSettings:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}