{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/accountProvider"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider","text":"AccountProvider","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/providers\/accountprovider"]},{"paths":["\/documentation\/chatproviderssdk\/providers\/accountprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider","text":"AccountProvider"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders(py)accountProvider","title":"accountProvider","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"accountProvider"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"ChatProvidersSDK"}]},"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider":{"url":"\/documentation\/chatproviderssdk\/accountprovider","role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"codeVoice","code":"ZDKChatAccountProvider"},{"type":"text","text":" gives the ability to observe account updates."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","title":"AccountProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountProvider"}],"navigatorTitle":[{"kind":"identifier","text":"AccountProvider"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers":{"kind":"symbol","title":"Providers","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Providers"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/providers","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Providers"}],"abstract":[{"type":"codeVoice","code":"ZDKChatProviders"},{"type":"text","text":" is a grouping of all the providers that allow you to, setup for push notifications,"},{"type":"text","text":" "},{"type":"text","text":"handle session updates, handle connection state, and interact with the APIs in other ways."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers/accountProvider":{"title":"accountProvider","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/chatproviderssdk\/providers\/accountprovider","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AccountProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/accountProvider","navigatorTitle":[{"kind":"identifier","text":"accountProvider"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"accountProvider","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"accountProvider","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider","text":"ZDKChatAccountProvider","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"accountProvider"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/title","op":"replace","value":"ZDKChatAccountProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/fragments","op":"replace","value":[{"text":"ZDKChatAccountProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/title","value":"ZDKChatProviders"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/fragments","value":[{"kind":"identifier","text":"ZDKChatProviders"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1accountProvider\/title","op":"replace","value":"accountProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1accountProvider\/fragments","value":[{"text":"accountProvider","kind":"identifier"}],"op":"replace"}]}]}