{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreachable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/unreachable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/unreachable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/unreachable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The internet connectivity appears to be offline"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreachable"}],"title":"ConnectionStatus.unreachable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus@ZDKConnectionStatusUnreachable","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusUnreachable"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"role":"symbol","title":"ConnectionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionStatus"}],"abstract":[{"type":"text","text":"Represents different states of the"},{"type":"codeVoice","code":"ChatSession"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionStatus"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/unreachable":{"role":"symbol","title":"ConnectionStatus.unreachable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreachable"}],"abstract":[{"type":"text","text":"The internet connectivity appears to be offline"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/unreachable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusUnreachable"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/unreachable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKConnectionStatusUnreachable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionStatusUnreachable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKConnectionStatusUnreachable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title","value":"ZDKConnectionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1unreachable\/title","value":"ZDKConnectionStatusUnreachable"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1unreachable\/fragments","value":[{"kind":"identifier","text":"ZDKConnectionStatusUnreachable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}