{"sections":[],"abstract":[{"type":"text","text":"Observe chat settings model"}],"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"method","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKSettingsProvider(im)observeChatSettingsWithIdentifier::","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatSettings"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", ("},{"text":"ChatSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"extendedModule":"ChatProvidersSDK","roleHeading":"Instance Method","navigatorTitle":[{"text":"observeChatSettingsWithIdentifier::","kind":"identifier"}],"title":"observeChatSettings(identifier:_:)","platforms":[]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-1534y","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatSettings"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"ChatSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Specify how to handle the ","type":"text"},{"code":"ChatSettings","type":"codeVoice"},{"type":"text","text":" via closure."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservationToken"},{"type":"text","text":" that can cancel the subscription to the "},{"code":"ChatSettings","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(identifier:_:)-1534y"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(identifier:_:)-1534y"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider/observeChatSettings(identifier:_:)-1534y":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatSettings"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","text":"ChatSettings"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-1534y","title":"observeChatSettings(identifier:_:)","abstract":[{"type":"text","text":"Observe chat settings model"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(identifier:_:)-1534y","navigatorTitle":[{"text":"observeChatSettingsWithIdentifier::","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider":{"role":"symbol","abstract":[{"type":"codeVoice","code":"ZDKSettingsProvider"},{"text":" gives the ability to observe settings updates.","type":"text"}],"title":"SettingsProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SettingsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","type":"topic","navigatorTitle":[{"text":"SettingsProvider","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/settingsprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","type":"topic","navigatorTitle":[{"text":"ChatSettings","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"code":"ZDKChatSettings","type":"codeVoice"},{"type":"text","text":" model stores information about the chat account’s settings,"},{"type":"text","text":" "},{"type":"text","text":"such as the "},{"type":"codeVoice","code":"fileSizeLimit"},{"type":"text","text":", whether attachments are enabled, and the list of accepted file extensions."}],"url":"\/documentation\/chatproviderssdk\/chatsettings","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatSettings","kind":"identifier"}],"title":"ChatSettings"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ObservationToken","kind":"identifier"}],"abstract":[{"type":"text","text":"Unsubscribe from observers"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","navigatorTitle":[{"text":"ObservationToken","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/observationtoken","title":"ObservationToken"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"observeChatSettingsWithIdentifier::","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"observeChatSettingsWithIdentifier::","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"ZDKObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"observeChatSettingsWithIdentifier:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@ChatProvidersSDK@objc(cs)ZDKChatSettings)","kind":"typeIdentifier","text":"void (^)(ZDKChatSettings *)"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(identifier:_:)-1534y\/title","value":"observeChatSettingsWithIdentifier::"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(identifier:_:)-1534y\/fragments","value":[{"kind":"text","text":"- "},{"text":"observeChatSettingsWithIdentifier::","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/title","value":"ZDKSettingsProvider","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKSettingsProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title","value":"ZDKChatSettings"},{"value":[{"kind":"identifier","text":"ZDKChatSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","op":"replace","value":"ZDKObservationToken"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","value":[{"kind":"identifier","text":"ZDKObservationToken"}],"op":"replace"}]}]}