{"abstract":[{"text":"Base protocol representation of a ","type":"text"},{"code":"ChatLog","type":"codeVoice"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest"],"type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ChatLogProtocol","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:s23CustomStringConvertibleP","text":"CustomStringConvertible","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Hashable","kind":"typeIdentifier","preciseIdentifier":"s:SH"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatlogprotocol"]}],"sections":[],"metadata":{"roleHeading":"Protocol","title":"ChatLogProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLogProtocol"}],"externalID":"s:16ChatProvidersSDK0A11LogProtocolP","navigatorTitle":[{"text":"ChatLogProtocol","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/createdTimestamp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/displayName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/id","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/lastModifiedTimestamp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/nick","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/participant","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/status","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/type"],"title":"Instance Properties"}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMessage":{"abstract":[{"type":"text","text":"Chat message"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatmessage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"type":"topic","navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"title":"ChatMessage","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMemberLeave":{"abstract":[{"type":"text","text":"Chat Member Leave event"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatMemberLeave","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatmemberleave","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","navigatorTitle":[{"text":"ChatMemberLeave","kind":"identifier"}],"title":"ChatMemberLeave","type":"topic","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/displayName":{"abstract":[{"text":"Display Name","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/displayName","title":"displayName","role":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/displayname","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/nick":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/nick","required":true,"title":"nick","abstract":[{"type":"text","text":"Identifier associated with the sender. Used to distinguish "},{"code":"sender","type":"codeVoice"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/nick","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nick"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Base class for chat log events that may occur in a chat session"}],"title":"ChatLog","url":"\/documentation\/chatproviderssdk\/chatlog","role":"symbol","navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol":{"navigatorTitle":[{"kind":"identifier","text":"ChatLogProtocol"}],"url":"\/documentation\/chatproviderssdk\/chatlogprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatLogProtocol","kind":"identifier"}],"abstract":[{"text":"Base protocol representation of a ","type":"text"},{"code":"ChatLog","type":"codeVoice"}],"type":"topic","title":"ChatLogProtocol","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/createdTimestamp":{"title":"createdTimestamp","url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/createdtimestamp","abstract":[{"text":"Timestamp of when the message was sent","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/createdTimestamp","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"createdTimestamp","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"required":true,"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/participant":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/participant","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"participant","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatParticipant","text":"ChatParticipant","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/participant","required":true,"abstract":[{"text":"Who sent the message can be ","type":"text"},{"code":"user","type":"codeVoice"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"agent"},{"text":"\/","type":"text"},{"type":"codeVoice","code":"trigger"}],"title":"participant"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage":{"title":"ChatAttachmentMessage","navigatorTitle":[{"text":"ChatAttachmentMessage","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAttachmentMessage"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","abstract":[{"type":"text","text":"The Chat Log attachment"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatattachmentmessage","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatOptionsMessage":{"url":"\/documentation\/chatproviderssdk\/chatoptionsmessage","navigatorTitle":[{"text":"ChatOptionsMessage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","role":"symbol","kind":"symbol","title":"ChatOptionsMessage","abstract":[{"type":"text","text":"Questions from agent with multiple options that a user can respond with"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatOptionsMessage","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatComment":{"url":"\/documentation\/chatproviderssdk\/chatcomment","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","type":"topic","title":"ChatComment","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatComment","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatComment"}],"abstract":[{"text":"Chat comment in relation to a Chat rating.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/id":{"url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/id","type":"topic","abstract":[{"type":"text","text":"ID"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"required":true,"title":"id","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/id","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/type":{"url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/type","required":true,"abstract":[{"text":"The type of event the log is","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatLogType","kind":"typeIdentifier","text":"ChatLogType"}],"kind":"symbol","title":"type","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/type"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMemberJoin":{"role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatmemberjoin","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMemberJoin","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","navigatorTitle":[{"kind":"identifier","text":"ChatMemberJoin"}],"abstract":[{"text":"Chat Member Join event","type":"text"}],"title":"ChatMemberJoin"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatRatingRequest":{"abstract":[{"type":"text","text":"Chat Rating Request (sent by the agent)"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatRatingRequest","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest","navigatorTitle":[{"text":"ChatRatingRequest","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatratingrequest","type":"topic","title":"ChatRatingRequest"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatRating":{"abstract":[{"type":"text","text":"A Chat rating left by the user after an agent requested it. Can be "},{"type":"codeVoice","code":"none"},{"type":"text","text":", "},{"code":"good","type":"codeVoice"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"bad"}],"navigatorTitle":[{"text":"ChatRating","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","kind":"symbol","title":"ChatRating","url":"\/documentation\/chatproviderssdk\/chatrating","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatRating"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/status":{"abstract":[{"text":"Delivery status of the message","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DeliveryStatus","preciseIdentifier":"s:16ChatProvidersSDK14DeliveryStatusO"}],"required":true,"title":"status","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/status","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol/lastModifiedTimestamp":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol\/lastModifiedTimestamp","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatlogprotocol\/lastmodifiedtimestamp","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastModifiedTimestamp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"lastModifiedTimestamp","abstract":[{"text":"Timestamp of when the message was modified","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"ZDKChatMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/title"},{"value":[{"text":"ZDKChatMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/fragments"},{"value":"ZDKChatMemberLeave","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberLeave\/title"},{"value":[{"text":"ZDKChatMemberLeave","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberLeave\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title","value":"ZDKChatLog","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatLog"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/title","op":"replace","value":"ZDKChatAttachmentMessage"},{"op":"replace","value":[{"text":"ZDKChatAttachmentMessage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatOptionsMessage\/title","op":"replace","value":"ZDKChatOptionsMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatOptionsMessage\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatOptionsMessage"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatComment\/title","value":"ZDKChatComment","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatComment\/fragments","value":[{"kind":"identifier","text":"ZDKChatComment"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberJoin\/title","value":"ZDKChatMemberJoin","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatMemberJoin"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberJoin\/fragments","op":"replace"},{"op":"replace","value":"ZDKRatingRequest","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRatingRequest\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRatingRequest\/fragments","value":[{"text":"ZDKRatingRequest","kind":"identifier"}],"op":"replace"},{"value":"ZDKChatRating","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRating\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRating\/fragments","op":"replace","value":[{"text":"ZDKChatRating","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}