{"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/configuring","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ended","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ending","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/initializing","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/started"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/CustomStringConvertible-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatSessionStatus"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus"},"abstract":[{"text":"Chat session status describes current state of the session","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSessionStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ChatSessionStatus"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"ChatSessionStatus","role":"symbol","externalID":"c:@M@ChatProvidersSDK@E@ChatSessionStatus"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/ending":{"kind":"symbol","type":"topic","role":"symbol","title":"ChatSessionStatus.ending","navigatorTitle":[{"text":"ChatSessionStatusEnding","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ending","abstract":[{"type":"text","text":"Chat is ending"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ending"}],"url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/ending"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus":{"title":"ChatSessionStatus","role":"symbol","abstract":[{"type":"text","text":"Chat session status describes current state of the session"}],"url":"\/documentation\/chatproviderssdk\/chatsessionstatus","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatSessionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ChatSessionStatus","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/started":{"title":"ChatSessionStatus.started","role":"symbol","abstract":[{"type":"text","text":"Chat is ready to send & receive messages"}],"url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/started","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/started","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"started","kind":"identifier"}],"navigatorTitle":[{"text":"ChatSessionStatusStarted","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/RawRepresentable-Implementations","abstract":[],"kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/Equatable-Implementations":{"type":"topic","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/equatable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://com.zendesk.ChatProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/configuring":{"abstract":[{"text":"Initialization status.","type":"text"},{"type":"text","text":" "},{"text":"Chat hasn’t started yet","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/configuring","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/configuring","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuring"}],"navigatorTitle":[{"text":"ChatSessionStatusConfiguring","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"ChatSessionStatus.configuring"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/init(rawValue:)":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/init(rawvalue:)","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/initializing":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializing"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/initializing","navigatorTitle":[{"text":"ChatSessionStatusInitializing","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Initialization status.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Chat hasn’t started yet"}],"title":"ChatSessionStatus.initializing","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/initializing","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/ended":{"title":"ChatSessionStatus.ended","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ended"}],"navigatorTitle":[{"text":"ChatSessionStatusEnded","kind":"identifier"}],"abstract":[{"type":"text","text":"Chat session has ended"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ended","type":"topic","kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/ended"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/CustomStringConvertible-Implementations":{"type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/customstringconvertible-implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ChatSessionStatus","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatSessionStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ChatSessionStatus","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/configuring","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ended","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ending","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/initializing","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/started"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatSessionStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ending\/title","value":"ChatSessionStatusEnding","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ending\/fragments","value":[{"text":"ChatSessionStatusEnding","kind":"identifier"}],"op":"replace"},{"value":"ChatSessionStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/fragments","value":[{"text":"ChatSessionStatus","kind":"identifier"}]},{"value":"ChatSessionStatusStarted","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1started\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1started\/fragments","value":[{"kind":"identifier","text":"ChatSessionStatusStarted"}]},{"value":"ChatSessionStatusConfiguring","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1configuring\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1configuring\/fragments","value":[{"text":"ChatSessionStatusConfiguring","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ChatSessionStatusInitializing","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1initializing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ChatSessionStatusInitializing"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1initializing\/fragments"},{"value":"ChatSessionStatusEnded","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ended\/title"},{"value":[{"text":"ChatSessionStatusEnded","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ended\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}