{"variants":[{"paths":["\/documentation\/chatproviderssdk\/connectionprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/connectionprovider"]}],"sections":[],"metadata":{"role":"symbol","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConnectionProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ConnectionProvider","kind":"identifier"}],"title":"ConnectionProvider","modules":[{"name":"ChatProvidersSDK"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"code":"ZDKConnectionProvider","type":"codeVoice"},{"text":" gives the ability to observe connection updates.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/status"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/connect()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/disconnect()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-1lono","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-85u3e","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/setReachability(reachability:)"],"title":"Instance Methods"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKConnectionProvider) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionProvider"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/connect()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"connect","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/connect()","kind":"symbol","navigatorTitle":[{"text":"connect","kind":"identifier"}],"abstract":[{"type":"text","text":"Connect to the session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/connect()","type":"topic","role":"symbol","title":"connect()"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/observeConnectionStatus(identifier:_:)-1lono":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-1lono","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Observe connection status updates. Specify a closure how the status should be handled"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeConnectionStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","kind":"typeIdentifier","text":"ObservableIdentifier"},{"kind":"text","text":", ("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus","text":"ConnectionStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","kind":"typeIdentifier"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(identifier:_:)-1lono","title":"observeConnectionStatus(identifier:_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/observeConnectionStatus(identifier:_:)-85u3e":{"title":"observeConnectionStatus(identifier:_:)","navigatorTitle":[{"kind":"identifier","text":"observeConnectionStatusWithIdentifier::"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"observeConnectionStatus"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", (","kind":"text"},{"text":"ConnectionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(identifier:_:)-85u3e","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-85u3e"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/setReachability(reachability:)":{"title":"setReachability(reachability:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setReachability","kind":"identifier"},{"kind":"text","text":"("},{"text":"reachability","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:16ChatProvidersSDK20ReachabilityProtocolP","text":"ReachabilityProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/setreachability(reachability:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/setReachability(reachability:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/status":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/status","navigatorTitle":[{"kind":"identifier","text":"status"}],"type":"topic","role":"symbol","abstract":[{"text":"The current status of the Connection","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConnectionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/status","title":"status"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/observeConnectionStatus(_:)":{"title":"observeConnectionStatus(_:)","navigatorTitle":[{"text":"observeConnectionStatus:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"observeConnectionStatus","kind":"identifier"},{"kind":"text","text":"(("},{"text":"ConnectionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/observeconnectionstatus(_:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider/disconnect()":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/disconnect()","navigatorTitle":[{"kind":"identifier","text":"disconnect"}],"type":"topic","role":"symbol","abstract":[{"text":"Disconnect from the current session, closes the socket connection.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Please note, this won’t end the chat session with agent"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disconnect","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/chatproviderssdk\/connectionprovider\/disconnect()","title":"disconnect()"},"doc://com.zendesk.ChatProvidersSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider":{"abstract":[{"code":"ZDKConnectionProvider","type":"codeVoice"},{"text":" gives the ability to observe connection updates.","type":"text"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionprovider","title":"ConnectionProvider","type":"topic","navigatorTitle":[{"text":"ConnectionProvider","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ZDKConnectionProvider","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKConnectionProvider","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ZDKConnectionProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/status"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/connect()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/disconnect()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider\/observeConnectionStatus(identifier:_:)-85u3e"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKConnectionProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1connect()\/title","op":"replace","value":"connect"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1connect()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"connect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1observeConnectionStatus(identifier:_:)-85u3e\/title","value":"observeConnectionStatusWithIdentifier::"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1observeConnectionStatus(identifier:_:)-85u3e\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeConnectionStatusWithIdentifier::"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1status\/title","value":"status","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1status\/fragments","op":"replace","value":[{"kind":"identifier","text":"status"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1observeConnectionStatus(_:)\/title","op":"replace","value":"observeConnectionStatus:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"observeConnectionStatus:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1observeConnectionStatus(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1disconnect()\/title","value":"disconnect"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider~1disconnect()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"disconnect"}],"op":"replace"},{"value":"ZDKConnectionProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/title"},{"value":[{"text":"ZDKConnectionProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/fragments","op":"replace"}]}]}