{"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Enumeration","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogLevel","symbolKind":"enum","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogLevel"}],"role":"symbol","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/debug","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/error","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/info","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/verbose","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/warning"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/loglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/loglevel"]}],"abstract":[{"type":"text","text":"Log level enum (Based on Android log vals)."}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatLogLevel) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LogLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"name":"Author","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Zendesk"}]}],"type":"aside"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","url":"\/documentation\/chatproviderssdk\/loglevel\/equatable-implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/Equatable-Implementations","role":"collectionGroup"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/info":{"title":"LogLevel.info","navigatorTitle":[{"text":"ZDKChatLogLevelInfo","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"url":"\/documentation\/chatproviderssdk\/loglevel\/info","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/info","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/chatproviderssdk\/loglevel\/init(rawvalue:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/init(rawValue:)","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/debug":{"navigatorTitle":[{"text":"ZDKChatLogLevelDebug","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/loglevel\/debug","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/debug","role":"symbol","title":"LogLevel.debug"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/error":{"title":"LogLevel.error","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogLevelError"}],"url":"\/documentation\/chatproviderssdk\/loglevel\/error","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/RawRepresentable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/RawRepresentable-Implementations","url":"\/documentation\/chatproviderssdk\/loglevel\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/verbose":{"title":"LogLevel.verbose","navigatorTitle":[{"text":"ZDKChatLogLevelVerbose","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"verbose","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/loglevel\/verbose","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/verbose","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel":{"abstract":[{"text":"Log level enum (Based on Android log vals).","type":"text"}],"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"title":"LogLevel","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel","role":"symbol","url":"\/documentation\/chatproviderssdk\/loglevel","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/warning":{"title":"LogLevel.warning","navigatorTitle":[{"text":"ZDKChatLogLevelWarning","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"url":"\/documentation\/chatproviderssdk\/loglevel\/warning","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/warning","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"ZDKChatLogLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKChatLogLevel","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatLogLevel"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/debug","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/error","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/info","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/verbose","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/warning"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKChatLogLevel","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1info\/title","op":"replace","value":"ZDKChatLogLevelInfo"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1info\/fragments","value":[{"text":"ZDKChatLogLevelInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1debug\/title","value":"ZDKChatLogLevelDebug"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1debug\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogLevelDebug"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1error\/title","value":"ZDKChatLogLevelError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1error\/fragments","value":[{"text":"ZDKChatLogLevelError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1verbose\/title","value":"ZDKChatLogLevelVerbose","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"ZDKChatLogLevelVerbose"}],"op":"replace"},{"value":"ZDKChatLogLevel","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel\/title","op":"replace"},{"value":[{"text":"ZDKChatLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel\/fragments"},{"value":"ZDKChatLogLevelWarning","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1warning\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1warning\/fragments","value":[{"text":"ZDKChatLogLevelWarning","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}