{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/init(id:cancellationClosure:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/id"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/asBehaviour()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/cancel()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/isEqual(_:)"],"title":"Instance Methods"}],"abstract":[{"text":"Unsubscribe from observers","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ObservationToken","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Class","title":"ObservationToken","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","navigatorTitle":[{"text":"ObservationToken","kind":"identifier"}],"symbolKind":"class","role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/observationtoken"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/observationtoken"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/s12IdentifiableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKObservationToken) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ObservationToken"}],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken/id":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","text":"ObservableIdentifier","kind":"typeIdentifier"}],"title":"id","type":"topic","url":"\/documentation\/chatproviderssdk\/observationtoken\/id","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/id","role":"symbol","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken/asBehaviour()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"asBehaviour","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK16ObserveBehaviourC","text":"ObserveBehaviour","kind":"typeIdentifier"}],"title":"asBehaviour()","type":"topic","url":"\/documentation\/chatproviderssdk\/observationtoken\/asbehaviour()","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/asBehaviour()","role":"symbol","abstract":[{"type":"text","text":"Maps the "},{"code":"ObservationToken","type":"codeVoice"},{"type":"text","text":" into an "},{"type":"codeVoice","code":"ObserveBehaviour"}]},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"title":"ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"kind":"symbol","abstract":[{"text":"Unsubscribe from observers","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken/isEqual(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEqual(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/chatproviderssdk\/observationtoken\/isequal(_:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/isEqual(_:)","role":"symbol","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken/init(id:cancellationClosure:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cancellationClosure"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(id:cancellationClosure:)","type":"topic","url":"\/documentation\/chatproviderssdk\/observationtoken\/init(id:cancellationclosure:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/init(id:cancellationClosure:)","role":"symbol","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/s12IdentifiableP":{"title":"Swift.Identifiable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s12IdentifiableP","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken/cancel()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"},{"text":"()","kind":"text"}],"title":"cancel()","type":"topic","navigatorTitle":[{"text":"cancel","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/observationtoken\/cancel()","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/cancel()","role":"symbol","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"ZDKObservationToken","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKObservationToken"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKObservationToken","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/cancel()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKObservationToken"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKObservationToken","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title"},{"value":[{"text":"ZDKObservationToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken~1cancel()\/title","value":"cancel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken~1cancel()\/fragments","value":[{"kind":"text","text":"- "},{"text":"cancel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}