{"abstract":[{"text":"The ","type":"text"},{"code":"ZDKPushNoticiationProvider","type":"codeVoice"},{"text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/pushnotificationsprovider"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKPushNotificationsProvider) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsProvider"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"inlineContent":[{"text":"There are two types of chat notifications:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"chat.msg"},{"type":"text","text":" - received when a new chat message was sent from an agent"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"chat.end"},{"type":"text","text":" - received when the current chat session ends."}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Class","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsProvider"}],"title":"PushNotificationsProvider","role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsProvider"}]},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/didReceiveRemoteNotification(_:in:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/isChatPushNotification(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushToken(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushTokenString(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/unregisterPushToken()"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/ChatMessageReceivedNotification"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/Loggable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/Loggable-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/Loggable-Implementations","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/loggable-implementations","title":"Loggable Implementations"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Loggable":{"type":"topic","abstract":[{"text":"Protocol that conforms","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Loggable"}],"navigatorTitle":[{"text":"Loggable","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","url":"\/documentation\/chatproviderssdk\/loggable","title":"Loggable"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/registerPushToken(_:)":{"type":"topic","abstract":[{"type":"text","text":"Registers device token with Zendesk Chat"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerPushToken"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"registerPushToken:"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushToken(_:)","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/registerpushtoken(_:)","title":"registerPushToken(_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/isChatPushNotification(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatPushNotification"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/isChatPushNotification(_:)","title":"isChatPushNotification(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isChatPushNotification:"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/ischatpushnotification(_:)","type":"topic","abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"true"},{"type":"text","text":" if received push notification belongs to Chat SDK"}]},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/ChatMessageReceivedNotification":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessageReceivedNotification","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNotification","text":"NSNotification","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/ChatMessageReceivedNotification","title":"ChatMessageReceivedNotification","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessageReceivedNotification"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/chatmessagereceivednotification","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"NSNotification.Name"},{"type":"text","text":" associated with the message received push notificiation"}]},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/registerPushTokenString(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerPushTokenString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushTokenString(_:)","title":"registerPushTokenString(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerPushTokenString:"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/registerpushtokenstring(_:)","type":"topic","abstract":[{"type":"text","text":"Registers device token with Zendesk Chat"}]},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationsProvider"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","title":"PushNotificationsProvider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushNotificationsProvider"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider","type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKPushNoticiationProvider"},{"type":"text","text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/unregisterPushToken()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterPushToken"},{"kind":"text","text":"()"}],"role":"symbol","title":"unregisterPushToken()","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/unregisterPushToken()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterPushToken"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/unregisterpushtoken()","type":"topic","abstract":[{"type":"text","text":"Unregisters for Push notifications"}]},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider/didReceiveRemoteNotification(_:in:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveRemoteNotification"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"didReceiveRemoteNotification(_:in:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/didReceiveRemoteNotification(_:in:)","kind":"symbol","navigatorTitle":[{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider\/didreceiveremotenotification(_:in:)","type":"topic","abstract":[{"type":"text","text":"Received push notification is processed by Chat SDK."}]},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"ZDKPushNotificationsProvider","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKPushNotificationsProvider"}]},{"op":"replace","value":[{"kind":"identifier","text":"ZDKPushNotificationsProvider"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/didReceiveRemoteNotification(_:in:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/isChatPushNotification(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushToken(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/registerPushTokenString(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/unregisterPushToken()"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider\/ChatMessageReceivedNotification"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"]}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ZDKPushNotificationsProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"registerPushToken:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1registerPushToken(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"registerPushToken:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1registerPushToken(_:)\/fragments"},{"value":"isChatPushNotification:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1isChatPushNotification(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1isChatPushNotification(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isChatPushNotification:","kind":"identifier"}]},{"value":"ChatMessageReceivedNotification","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1ChatMessageReceivedNotification\/title"},{"value":[{"text":"ChatMessageReceivedNotification","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1ChatMessageReceivedNotification\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1registerPushTokenString(_:)\/title","value":"registerPushTokenString:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerPushTokenString:"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1registerPushTokenString(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/title","value":"ZDKPushNotificationsProvider","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKPushNotificationsProvider"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1unregisterPushToken()\/title","value":"unregisterPushToken"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1unregisterPushToken()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unregisterPushToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1didReceiveRemoteNotification(_:in:)\/title","value":"didReceiveRemoteNotification:in:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider~1didReceiveRemoteNotification(_:in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveRemoteNotification:in:"}]}]}]}