{"metadata":{"title":"ChatError.chatIsNotInitialized","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatErrorChatIsNotInitialized"}],"symbolKind":"case","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"chatIsNotInitialized","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@E@ChatError@ChatErrorChatIsNotInitialized"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/chatIsNotInitialized"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatIsNotInitialized"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chaterror\/chatisnotinitialized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chaterror\/chatisnotinitialized"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Chat was not initialized"}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError":{"navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError","url":"\/documentation\/chatproviderssdk\/chaterror","type":"topic","title":"ChatError","abstract":[{"type":"text","text":"Potential errors returned from the ChatProviderSDK"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError/chatIsNotInitialized":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError\/chatIsNotInitialized","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatIsNotInitialized","kind":"identifier"}],"type":"topic","role":"symbol","title":"ChatError.chatIsNotInitialized","url":"\/documentation\/chatproviderssdk\/chaterror\/chatisnotinitialized","abstract":[{"text":"Chat was not initialized","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatErrorChatIsNotInitialized"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ChatErrorChatIsNotInitialized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ChatErrorChatIsNotInitialized","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ChatErrorChatIsNotInitialized"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError\/title","value":"ChatError"},{"value":[{"text":"ChatError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError\/fragments"},{"op":"replace","value":"ChatErrorChatIsNotInitialized","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError~1chatIsNotInitialized\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError~1chatIsNotInitialized\/fragments","op":"replace","value":[{"text":"ChatErrorChatIsNotInitialized","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}