{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatRatingRequest"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/chatratingrequest"]},{"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/chatratingrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"ChatLogType.chatRatingRequest","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"chatRatingRequest","kind":"identifier"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType@ZDKChatLogTypeChatRatingRequest","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeChatRatingRequest"}],"roleHeading":"Case","modules":[{"name":"ChatProvidersSDK"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Agent requested a rating"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRatingRequest","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/chatRatingRequest":{"title":"ChatLogType.chatRatingRequest","kind":"symbol","abstract":[{"type":"text","text":"Agent requested a rating"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatRatingRequest"}],"role":"symbol","navigatorTitle":[{"text":"ZDKChatLogTypeChatRatingRequest","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatlogtype\/chatratingrequest","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRatingRequest"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"title":"ChatLogType","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLogType"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ZDKChatLogTypeChatRatingRequest","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatLogTypeChatRatingRequest"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKChatLogTypeChatRatingRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRatingRequest\/title","value":"ZDKChatLogTypeChatRatingRequest"},{"value":[{"kind":"identifier","text":"ZDKChatLogTypeChatRatingRequest"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRatingRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","value":"ZDKChatLogType"},{"value":[{"kind":"identifier","text":"ZDKChatLogType"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}