{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"memberJoin"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Member joined the channel"}],"metadata":{"externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType@ZDKChatLogTypeMemberJoin","title":"ChatLogType.memberJoin","navigatorTitle":[{"text":"ZDKChatLogTypeMemberJoin","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memberJoin","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/memberjoin"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/memberjoin"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberJoin","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/memberJoin":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberJoin","type":"topic","url":"\/documentation\/chatproviderssdk\/chatlogtype\/memberjoin","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeMemberJoin"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"memberJoin","kind":"identifier"}],"kind":"symbol","title":"ChatLogType.memberJoin","role":"symbol","abstract":[{"text":"Member joined the channel","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"title":"ChatLogType","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLogType"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"ZDKChatLogTypeMemberJoin","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKChatLogTypeMemberJoin","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKChatLogTypeMemberJoin","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberJoin\/title","value":"ZDKChatLogTypeMemberJoin"},{"value":[{"kind":"identifier","text":"ZDKChatLogTypeMemberJoin"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberJoin\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","op":"replace","value":"ZDKChatLogType"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogType"}]}]}]}