{"abstract":[{"text":"Member left the channel","type":"text"}],"metadata":{"symbolKind":"case","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType@ZDKChatLogTypeMemberLeave","navigatorTitle":[{"text":"ZDKChatLogTypeMemberLeave","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberLeave"}],"modules":[{"name":"ChatProvidersSDK"}],"title":"ChatLogType.memberLeave","role":"symbol","roleHeading":"Case"},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/memberleave"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/memberleave"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberLeave","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"memberLeave"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"title":"ChatLogType","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLogType"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/memberLeave":{"type":"topic","abstract":[{"type":"text","text":"Member left the channel"}],"role":"symbol","navigatorTitle":[{"text":"ZDKChatLogTypeMemberLeave","kind":"identifier"}],"title":"ChatLogType.memberLeave","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"memberLeave","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberLeave","url":"\/documentation\/chatproviderssdk\/chatlogtype\/memberleave"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"ZDKChatLogTypeMemberLeave","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogTypeMemberLeave"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKChatLogTypeMemberLeave"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKChatLogType","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","value":[{"text":"ZDKChatLogType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberLeave\/title","value":"ZDKChatLogTypeMemberLeave"},{"value":[{"kind":"identifier","text":"ZDKChatLogTypeMemberLeave"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberLeave\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}