{"abstract":[{"text":"Visitor left a rating","type":"text"}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/chatrating"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/chatrating"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatRating"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"chatRating","kind":"identifier"}],"title":"ChatLogType.chatRating","symbolKind":"case","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType@ZDKChatLogTypeChatRating","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeChatRating"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRating","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"url":"\/documentation\/chatproviderssdk\/chatlogtype","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatLogType","kind":"identifier"}],"title":"ChatLogType","kind":"symbol","navigatorTitle":[{"text":"ChatLogType","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/chatRating":{"url":"\/documentation\/chatproviderssdk\/chatlogtype\/chatrating","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRating","abstract":[{"text":"Visitor left a rating","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"chatRating","kind":"identifier"}],"title":"ChatLogType.chatRating","kind":"symbol","navigatorTitle":[{"text":"ZDKChatLogTypeChatRating","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatLogTypeChatRating"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatLogTypeChatRating"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKChatLogTypeChatRating","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","value":"ZDKChatLogType"},{"value":[{"text":"ZDKChatLogType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","op":"replace"},{"value":"ZDKChatLogTypeChatRating","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRating\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogTypeChatRating"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRating\/fragments"}]}]}