{"abstract":[{"text":"Multiple-choice option message","type":"text"}],"metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionsMessage"}],"title":"ChatLogType.optionsMessage","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType@ZDKChatLogTypeOptionsMessage","symbolKind":"case","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeOptionsMessage"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"optionsMessage","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/optionsMessage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType"]]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/optionsmessage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype\/optionsmessage"]}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/optionsMessage":{"url":"\/documentation\/chatproviderssdk\/chatlogtype\/optionsmessage","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/optionsMessage","abstract":[{"text":"Multiple-choice option message","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"optionsMessage","kind":"identifier"}],"title":"ChatLogType.optionsMessage","kind":"symbol","navigatorTitle":[{"text":"ZDKChatLogTypeOptionsMessage","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"url":"\/documentation\/chatproviderssdk\/chatlogtype","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatLogType","kind":"identifier"}],"title":"ChatLogType","kind":"symbol","navigatorTitle":[{"text":"ChatLogType","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatLogTypeOptionsMessage"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKChatLogTypeOptionsMessage","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKChatLogTypeOptionsMessage"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1optionsMessage\/title","value":"ZDKChatLogTypeOptionsMessage"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogTypeOptionsMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1optionsMessage\/fragments"},{"value":"ZDKChatLogType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","op":"replace","value":[{"text":"ZDKChatLogType","kind":"identifier"}]}]}]}