{"sections":[],"metadata":{"symbolKind":"case","title":"ChatSessionStatus.ending","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ending","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@E@ChatSessionStatus@ChatSessionStatusEnding","navigatorTitle":[{"text":"ChatSessionStatusEnding","kind":"identifier"}],"roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus\/ending"]},{"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus\/ending"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Chat is ending","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ending"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ending","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSessionStatus"}],"title":"ChatSessionStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","abstract":[{"type":"text","text":"Chat session status describes current state of the session"}],"kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatsessionstatus","role":"symbol","navigatorTitle":[{"text":"ChatSessionStatus","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/ending":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Chat is ending"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"ending","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/ending","kind":"symbol","title":"ChatSessionStatus.ending","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ending","navigatorTitle":[{"kind":"identifier","text":"ChatSessionStatusEnding"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ChatSessionStatusEnding","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatSessionStatusEnding"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ChatSessionStatusEnding","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/title","op":"replace","value":"ChatSessionStatus"},{"value":[{"text":"ChatSessionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/fragments","op":"replace"},{"value":"ChatSessionStatusEnding","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ending\/title"},{"value":[{"kind":"identifier","text":"ChatSessionStatusEnding"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ending\/fragments","op":"replace"}]}]}