{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/providers\/chatprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/providers\/chatprovider"]}],"sections":[],"metadata":{"roleHeading":"Instance Property","title":"chatProvider","navigatorTitle":[{"text":"chatProvider","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders(py)chatProvider","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatProvider"},{"kind":"text","text":": "},{"text":"ChatProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider"}],"symbolKind":"property","modules":[{"name":"ChatProvidersSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/chatProvider","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"chatProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatprovider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers/chatProvider":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider","kind":"typeIdentifier","text":"ChatProvider"}],"title":"chatProvider","abstract":[],"url":"\/documentation\/chatproviderssdk\/providers\/chatprovider","navigatorTitle":[{"kind":"identifier","text":"chatProvider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/chatProvider","kind":"symbol","type":"topic","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","url":"\/documentation\/chatproviderssdk\/providers","navigatorTitle":[{"kind":"identifier","text":"Providers"}],"title":"Providers","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Providers","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ZDKChatProviders"},{"type":"text","text":" is a grouping of all the providers that allow you to, setup for push notifications,"},{"text":" ","type":"text"},{"text":"handle session updates, handle connection state, and interact with the APIs in other ways.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"chatProvider"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"chatProvider","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"ZDKChatProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"},{"text":" * ","kind":"text"},{"text":"chatProvider","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ZDKChatProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatProvider"}]},{"value":"chatProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1chatProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1chatProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"chatProvider"}]},{"value":"ZDKChatProviders","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/fragments","value":[{"kind":"identifier","text":"ZDKChatProviders"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}