{"variants":[{"paths":["\/documentation\/chatproviderssdk\/providers\/settingsprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/providers\/settingsprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/settingsProvider","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","text":"SettingsProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders(py)settingsProvider","title":"settingsProvider","modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"settingsProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SettingsProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"settingsProvider","kind":"identifier"}],"roleHeading":"Instance Property"},"kind":"symbol","sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","url":"\/documentation\/chatproviderssdk\/settingsprovider","navigatorTitle":[{"kind":"identifier","text":"SettingsProvider"}],"title":"SettingsProvider","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SettingsProvider","kind":"identifier"}],"abstract":[{"code":"ZDKSettingsProvider","type":"codeVoice"},{"type":"text","text":" gives the ability to observe settings updates."}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers/settingsProvider":{"type":"topic","url":"\/documentation\/chatproviderssdk\/providers\/settingsprovider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers\/settingsProvider","navigatorTitle":[{"kind":"identifier","text":"settingsProvider"}],"title":"settingsProvider","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"settingsProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SettingsProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider"}],"kind":"symbol","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","url":"\/documentation\/chatproviderssdk\/providers","navigatorTitle":[{"kind":"identifier","text":"Providers"}],"title":"Providers","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Providers","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ZDKChatProviders"},{"type":"text","text":" is a grouping of all the providers that allow you to, setup for push notifications,"},{"text":" ","type":"text"},{"text":"handle session updates, handle connection state, and interact with the APIs in other ways.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"settingsProvider","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"settingsProvider"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","text":"ZDKSettingsProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider"},{"kind":"text","text":" * "},{"kind":"identifier","text":"settingsProvider"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/title","value":"ZDKSettingsProvider","op":"replace"},{"op":"replace","value":[{"text":"ZDKSettingsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1settingsProvider\/title","op":"replace","value":"settingsProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers~1settingsProvider\/fragments","op":"replace","value":[{"text":"settingsProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/title","value":"ZDKChatProviders"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/fragments","value":[{"text":"ZDKChatProviders","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}