{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isFileSendingEnabled"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings(py)isFileSendingEnabled","navigatorTitle":[{"text":"isFileSendingEnabled","kind":"identifier"}],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"isFileSendingEnabled","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFileSendingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFileSendingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatsettings\/isfilesendingenabled"]},{"paths":["\/documentation\/chatproviderssdk\/chatsettings\/isfilesendingenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"if true, sending the attachments is available"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"navigatorTitle":[{"kind":"identifier","text":"ChatSettings"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatSettings"},{"text":" model stores information about the chat account’s settings,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"such as the "},{"code":"fileSizeLimit","type":"codeVoice"},{"text":", whether attachments are enabled, and the list of accepted file extensions.","type":"text"}],"role":"symbol","title":"ChatSettings","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSettings"}],"url":"\/documentation\/chatproviderssdk\/chatsettings","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/isFileSendingEnabled":{"navigatorTitle":[{"text":"isFileSendingEnabled","kind":"identifier"}],"abstract":[{"type":"text","text":"if true, sending the attachments is available"}],"role":"symbol","title":"isFileSendingEnabled","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isFileSendingEnabled","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFileSendingEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/chatproviderssdk\/chatsettings\/isfilesendingenabled","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"isFileSendingEnabled","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isFileSendingEnabled","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFileSendingEnabled"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title","value":"ZDKChatSettings"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatSettings"}]},{"op":"replace","value":"isFileSendingEnabled","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1isFileSendingEnabled\/title"},{"value":[{"text":"isFileSendingEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1isFileSendingEnabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}