{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setVisitorInfo(_:completion:)-9b7v0"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setVisitorInfo"},{"text":"(","kind":"text"},{"text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"VisitorInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","kind":"typeIdentifier","text":"DeliveryStatusError"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"title":"setVisitorInfo(_:completion:)","symbolKind":"method","role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"externalID":"s:16ChatProvidersSDK15ProfileProviderC14setVisitorInfo_10completionyAA0gH0C_ys6ResultOyAgA19DeliveryStatusErrorOGcSgtF","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider"]]},"abstract":[{"text":"Update Visitor Information using ","type":"text"},{"code":"VisitorInfo","type":"codeVoice"},{"type":"text","text":" model."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setVisitorInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"visitorInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"kind":"text","text":", "},{"text":"DeliveryStatusError","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")? = nil)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"visitorInfo","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"VisitorInfo"},{"text":" model containing ","type":"text"},{"code":"name","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"email"},{"type":"text","text":", and "},{"code":"phoneNumber","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"Result<VisitorInfo, DeliveryStatusError>","type":"codeVoice"},{"type":"text","text":" closure to handle if update sent successfully. Default is "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}]}],"name":"completion"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/profileprovider\/setvisitorinfo(_:completion:)-9b7v0"]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DeliveryStatusError":{"navigatorTitle":[{"kind":"identifier","text":"DeliveryStatusError"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/deliverystatuserror","title":"DeliveryStatusError","abstract":[{"text":"Delivery status error describes the reason of a delivery failure","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeliveryStatusError","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"type":"topic","navigatorTitle":[{"text":"VisitorInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Visitor information that can be seen in the Chat dashboard","type":"text"},{"text":" ","type":"text"},{"text":"Contains ","type":"text"},{"type":"codeVoice","code":"name"},{"text":", ","type":"text"},{"code":"email","type":"codeVoice"},{"type":"text","text":", and "},{"type":"codeVoice","code":"phoneNumber"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"VisitorInfo","kind":"identifier"}],"title":"VisitorInfo"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileProvider"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/profileprovider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","abstract":[{"type":"text","text":"The "},{"code":"ZDKProfileProvider","type":"codeVoice"},{"type":"text","text":" contain APIs to update information about a visitor."},{"text":" ","type":"text"},{"text":"Such as name, email, phone number, tags, and notes related to the visitor and their session.","type":"text"}],"type":"topic","title":"ProfileProvider","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/setVisitorInfo(_:completion:)-9b7v0":{"type":"topic","url":"\/documentation\/chatproviderssdk\/profileprovider\/setvisitorinfo(_:completion:)-9b7v0","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/setVisitorInfo(_:completion:)-9b7v0","kind":"symbol","title":"setVisitorInfo(_:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVisitorInfo"},{"kind":"text","text":"("},{"text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"VisitorInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Update Visitor Information using "},{"type":"codeVoice","code":"VisitorInfo"},{"type":"text","text":" model."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title","value":"ZDKVisitorInfo","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKVisitorInfo"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title","value":"ZDKProfileProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","value":[{"kind":"identifier","text":"ZDKProfileProvider"}]}]}]}