{"kind":"symbol","metadata":{"title":"LogLevel.error","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogLevelError"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogLevel@ZDKChatLogLevelError","symbolKind":"case","modules":[{"name":"ChatProvidersSDK"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/error","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/chatproviderssdk\/loglevel\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/loglevel\/error"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel/error":{"title":"LogLevel.error","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogLevelError"}],"url":"\/documentation\/chatproviderssdk\/loglevel\/error","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel\/error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel":{"abstract":[{"text":"Log level enum (Based on Android log vals).","type":"text"}],"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"title":"LogLevel","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel","role":"symbol","url":"\/documentation\/chatproviderssdk\/loglevel","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ZDKChatLogLevelError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatLogLevelError"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKChatLogLevelError","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"ZDKChatLogLevelError","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1error\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogLevelError"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel~1error\/fragments"},{"value":"ZDKChatLogLevel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel\/fragments","value":[{"text":"ZDKChatLogLevel","kind":"identifier"}],"op":"replace"}]}]}