{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/zdkdeliverystatus\/delivered"]},{"paths":["\/documentation\/chatproviderssdk\/zdkdeliverystatus\/delivered"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","title":"ZDKDeliveryStatus.delivered","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"ZDKDeliveryStatusDelivered","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus@ZDKDeliveryStatusDelivered","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delivered"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/delivered"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"delivered","kind":"identifier"}]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/delivered":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/delivered","url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/delivered","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"ZDKDeliveryStatusDelivered","kind":"identifier"}],"title":"ZDKDeliveryStatus.delivered","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"delivered","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Delivery Status of the "},{"type":"codeVoice","code":"ChatLog"}],"navigatorTitle":[{"text":"ZDKDeliveryStatus","kind":"identifier"}],"title":"ZDKDeliveryStatus","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeliveryStatus"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKDeliveryStatusDelivered","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKDeliveryStatusDelivered"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKDeliveryStatusDelivered","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"ZDKDeliveryStatusDelivered","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1delivered\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKDeliveryStatusDelivered"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1delivered\/fragments"},{"value":"ZDKDeliveryStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/fragments","value":[{"text":"ZDKDeliveryStatus","kind":"identifier"}]}]}]}