{"abstract":[{"type":"text","text":"Connection Provider"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionProvider"},{"text":": ","kind":"text"},{"text":"ConnectionProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.type.property","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"connectionProvider"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"connectionProvider","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConnectionProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider"},{"text":"?","kind":"text"}],"modules":[{"name":"ChatProvidersSDK"}],"title":"connectionProvider","symbolKind":"property","roleHeading":"Type Property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(cpy)connectionProvider"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat\/connectionprovider-swift.type.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/connectionprovider-swift.type.property"]}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/connectionProvider-swift.type.property":{"navigatorTitle":[{"kind":"identifier","text":"connectionProvider"}],"url":"\/documentation\/chatproviderssdk\/chat\/connectionprovider-swift.type.property","title":"connectionProvider","abstract":[{"type":"text","text":"Connection Provider"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"connectionProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider","kind":"typeIdentifier","text":"ConnectionProvider"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.type.property","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionProvider"}],"title":"ConnectionProvider","navigatorTitle":[{"text":"ConnectionProvider","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ZDKConnectionProvider"},{"type":"text","text":" gives the ability to observe connection updates."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","url":"\/documentation\/chatproviderssdk\/connectionprovider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Chat","kind":"identifier"}],"navigatorTitle":[{"text":"Chat","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/chatproviderssdk\/chat","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","role":"symbol","title":"Chat"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"connectionProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"connectionProvider"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","text":"ZDKConnectionProvider"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"connectionProvider"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1connectionProvider-swift.type.property\/title","op":"replace","value":"connectionProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1connectionProvider-swift.type.property\/fragments","value":[{"text":"connectionProvider","kind":"identifier"}]},{"op":"replace","value":"ZDKConnectionProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/title"},{"value":[{"text":"ZDKConnectionProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}