{"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/didreceiveremotenotification(_:in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chat\/didreceiveremotenotification(_:in:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/didReceiveRemoteNotification(_:in:)"},"metadata":{"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChat(cm)didReceiveRemoteNotification:in:","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didReceiveRemoteNotification"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":")"}],"modules":[{"name":"ChatProvidersSDK"}],"title":"didReceiveRemoteNotification(_:in:)","role":"symbol","roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didReceiveRemoteNotification","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"in","kind":"externalParam"},{"kind":"text","text":" "},{"text":"application","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"userInfo","content":[{"inlineContent":[{"type":"text","text":"A dictionary that contains information related to the remote notification"}],"type":"paragraph"}]},{"name":"application","content":[{"inlineContent":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are currently two types of supported Push Notifications:"}]},{"items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"New chat message"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This event happens, when there’s new message typed by an agent."},{"text":" ","type":"text"},{"type":"text","text":"In order to respond to this event, you can observe the notification with name"},{"text":" ","type":"text"},{"code":"PushNotificationsProvider.ChatMessageReceivedNotification","type":"codeVoice"},{"type":"text","text":" in "},{"type":"codeVoice","code":"NotificationCenter"},{"type":"text","text":"."}]}]}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"Chat has ended"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When this event is received, the Chat will be ended and the chat session will be disconnected"},{"type":"text","text":" "},{"text":"In order to respond to this event, you can observe the notification with name","type":"text"},{"type":"text","text":" "},{"code":"Chat.NotificationChatEnded","type":"codeVoice"},{"text":" in ","type":"text"},{"type":"codeVoice","code":"NotificationCenter"},{"type":"text","text":"."}]}]}]}]}],"type":"unorderedList"}]}],"sections":[],"abstract":[{"text":"Pass the received remote notification to ","type":"text"},{"code":"didReceiveRemoteNotification","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"If the push notification belongs to Zendesk Chat, the push notification will be processed accordingly","type":"text"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/didReceiveRemoteNotification(_:in:)":{"type":"topic","abstract":[{"type":"text","text":"Pass the received remote notification to "},{"code":"didReceiveRemoteNotification","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the push notification belongs to Zendesk Chat, the push notification will be processed accordingly"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didReceiveRemoteNotification","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/didReceiveRemoteNotification(_:in:)","title":"didReceiveRemoteNotification(_:in:)","role":"symbol","navigatorTitle":[{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chat\/didreceiveremotenotification(_:in:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Chat","kind":"identifier"}],"navigatorTitle":[{"text":"Chat","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/chatproviderssdk\/chat","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","role":"symbol","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"didReceiveRemoteNotification:in:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"didReceiveRemoteNotification:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userInfo"},{"text":" ","kind":"text"},{"text":"in:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"application"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"didReceiveRemoteNotification:in:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1didReceiveRemoteNotification(_:in:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1didReceiveRemoteNotification(_:in:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}]},{"op":"replace","value":"ZDKChat","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title"},{"value":[{"kind":"identifier","text":"ZDKChat"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments"}]}]}