{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/notificationauthenticationfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/notificationauthenticationfailed"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationAuthenticationFailed","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"This notification is called when the user authentication failed."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationAuthenticationFailed"},{"kind":"text","text":": "},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier","text":"Name"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"metadata":{"roleHeading":"Type Property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(cpy)NotificationAuthenticationFailed","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","navigatorTitle":[{"text":"NotificationAuthenticationFailed","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationAuthenticationFailed"},{"kind":"text","text":": "},{"text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"symbolKind":"property","title":"NotificationAuthenticationFailed"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Chat","kind":"identifier"}],"navigatorTitle":[{"text":"Chat","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/chatproviderssdk\/chat","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","role":"symbol","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/NotificationAuthenticationFailed":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationAuthenticationFailed","title":"NotificationAuthenticationFailed","navigatorTitle":[{"text":"NotificationAuthenticationFailed","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chat\/notificationauthenticationfailed","abstract":[{"type":"text","text":"This notification is called when the user authentication failed."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationAuthenticationFailed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":"."},{"text":"Name","preciseIdentifier":"c:@T@NSNotificationName","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"NotificationAuthenticationFailed","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"NotificationAuthenticationFailed","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"NotificationAuthenticationFailed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKChat","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"text":"ZDKChat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationAuthenticationFailed\/title","value":"NotificationAuthenticationFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationAuthenticationFailed\/fragments","value":[{"text":"NotificationAuthenticationFailed","kind":"identifier"}]}]}]}