{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/settingsprovider-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/settingsprovider-swift.type.property"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.type.property"},"sections":[],"abstract":[{"type":"text","text":"Settings Provider"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"settingsProvider","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","text":"SettingsProvider"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"metadata":{"roleHeading":"Type Property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(cpy)settingsProvider","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","navigatorTitle":[{"text":"settingsProvider","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"settingsProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","text":"SettingsProvider"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"settingsProvider"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/settingsProvider-swift.type.property":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.type.property","title":"settingsProvider","navigatorTitle":[{"text":"settingsProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chat\/settingsprovider-swift.type.property","abstract":[{"text":"Settings Provider","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"settingsProvider"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","text":"SettingsProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SettingsProvider"}],"type":"topic","abstract":[{"type":"codeVoice","code":"ZDKSettingsProvider"},{"text":" gives the ability to observe settings updates.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","kind":"symbol","navigatorTitle":[{"text":"SettingsProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/settingsprovider","role":"symbol","title":"SettingsProvider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Chat","kind":"identifier"}],"navigatorTitle":[{"text":"Chat","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/chatproviderssdk\/chat","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","role":"symbol","title":"Chat"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"settingsProvider"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"settingsProvider"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"ZDKSettingsProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"settingsProvider","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"settingsProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1settingsProvider-swift.type.property\/title"},{"value":[{"text":"settingsProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1settingsProvider-swift.type.property\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/title","value":"ZDKSettingsProvider","op":"replace"},{"op":"replace","value":[{"text":"ZDKSettingsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}