{"metadata":{"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"ConnectionStatus.failed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKConnectionStatusFailed","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus@ZDKConnectionStatusFailed","roleHeading":"Case"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/failed","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/connectionstatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Failed to reconnect to the web-socket","type":"text"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/failed":{"type":"topic","abstract":[{"text":"Failed to reconnect to the web-socket","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/failed","title":"ConnectionStatus.failed","role":"symbol","navigatorTitle":[{"text":"ZDKConnectionStatusFailed","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/failed"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConnectionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionStatus"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionstatus","abstract":[{"type":"text","text":"Represents different states of the"},{"type":"codeVoice","code":"ChatSession"}],"title":"ConnectionStatus","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKConnectionStatusFailed"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKConnectionStatusFailed","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKConnectionStatusFailed","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKConnectionStatusFailed","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1failed\/title"},{"value":[{"text":"ZDKConnectionStatusFailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1failed\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title","value":"ZDKConnectionStatus"},{"value":[{"kind":"identifier","text":"ZDKConnectionStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments"}]}]}