{"sections":[],"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"profileProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ProfileProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider"},{"kind":"text","text":"?"}],"title":"profileProvider","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(cpy)profileProvider","symbolKind":"property","navigatorTitle":[{"text":"profileProvider","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.type.property","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"profileProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","text":"ProfileProvider"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/chat\/profileprovider-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/profileprovider-swift.type.property"]}],"abstract":[{"text":"Profile Provider","type":"text"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"url":"\/documentation\/chatproviderssdk\/profileprovider","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","abstract":[{"text":"The ","type":"text"},{"code":"ZDKProfileProvider","type":"codeVoice"},{"text":" contain APIs to update information about a visitor.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Such as name, email, phone number, tags, and notes related to the visitor and their session."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProfileProvider","kind":"identifier"}],"title":"ProfileProvider","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","abstract":[{"type":"codeVoice","code":"Chat"},{"text":" is a singleton class of the ","type":"text"},{"code":"ChatProviderSDK","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat","type":"topic","title":"Chat","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Chat","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/profileProvider-swift.type.property":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"profileProvider"},{"text":": ","kind":"text"},{"text":"ProfileProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/profileprovider-swift.type.property","title":"profileProvider","type":"topic","abstract":[{"text":"Profile Provider","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"profileProvider"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"profileProvider"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"profileProvider"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider","text":"ZDKProfileProvider","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"profileProvider"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title","value":"ZDKProfileProvider"},{"value":[{"text":"ZDKProfileProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","op":"replace"},{"value":"ZDKChat","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"text":"ZDKChat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1profileProvider-swift.type.property\/title","op":"replace","value":"profileProvider"},{"value":[{"kind":"identifier","text":"profileProvider"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1profileProvider-swift.type.property\/fragments","op":"replace"}]}]}