{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat\/resetidentity(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chat\/resetidentity(_:)"]}],"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetIdentity","kind":"identifier"},{"text":"((() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"resetIdentity:","kind":"identifier"}],"symbolKind":"method","title":"resetIdentity(_:)","modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat(im)resetIdentity:","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Resets the visitor data to a clean state allowing a new visitor to chat"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetIdentity","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any ongoing chat will be ended, and locally stored information about the visitor will be cleared, including the registered push token."},{"text":" ","type":"text"},{"type":"text","text":"Make sure to re-register for push notifications as needed."}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity(_:)"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/resetIdentity(_:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetIdentity"},{"kind":"text","text":"((() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity(_:)","title":"resetIdentity(_:)","url":"\/documentation\/chatproviderssdk\/chat\/resetidentity(_:)","type":"topic","abstract":[{"type":"text","text":"Resets the visitor data to a clean state allowing a new visitor to chat"}],"navigatorTitle":[{"text":"resetIdentity:","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","abstract":[{"type":"codeVoice","code":"Chat"},{"text":" is a singleton class of the ","type":"text"},{"code":"ChatProviderSDK","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat","type":"topic","title":"Chat","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Chat","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"resetIdentity:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetIdentity:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"resetIdentity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFv()"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity(_:)\/title","value":"resetIdentity:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resetIdentity:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}