{"metadata":{"symbolKind":"method","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Instance Method","extendedModule":"ChatProvidersSDK","platforms":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"observeChatState","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ("},{"text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"title":"observeChatState(identifier:_:)","role":"symbol","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChatProvider(im)observeChatStateWithIdentifier::","navigatorTitle":[{"kind":"identifier","text":"observeChatStateWithIdentifier::"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"text":"ObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(identifier:_:)-3wak7"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(identifier:_:)-3wak7"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-3wak7"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"title":"ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"kind":"symbol","abstract":[{"text":"Unsubscribe from observers","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/observeChatState(identifier:_:)-3wak7":{"url":"\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(identifier:_:)-3wak7","abstract":[],"kind":"symbol","type":"topic","title":"observeChatState(identifier:_:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-3wak7","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", (","kind":"text"},{"text":"ChatState","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"navigatorTitle":[{"kind":"identifier","text":"observeChatStateWithIdentifier::"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"navigatorTitle":[{"text":"ChatState","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatstate","abstract":[{"code":"ZDKChatState","type":"codeVoice"},{"text":" is a model representation of the current chat session.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"ChatState","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatprovider","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"observeChatStateWithIdentifier::","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"observeChatStateWithIdentifier::","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"ZDKObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"observeChatStateWithIdentifier:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"identifier","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":":"},{"kind":"text","text":"("},{"text":"void (^)(ZDKChatState *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@ChatProvidersSDK@objc(cs)ZDKChatState)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKObservationToken","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","value":[{"text":"ZDKObservationToken","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"observeChatStateWithIdentifier::","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1observeChatState(identifier:_:)-3wak7\/title"},{"value":[{"kind":"text","text":"- "},{"text":"observeChatStateWithIdentifier::","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1observeChatState(identifier:_:)-3wak7\/fragments","op":"replace"},{"value":"ZDKChatState","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatState"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","op":"replace"},{"value":"ZDKChatProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatProvider"}]}]}]}