{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendchatrating(_:completion:)-7hhpe"]},{"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendchatrating(_:completion:)-7hhpe"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Instance Method","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChatProvider(im)sendChatRating:completion:","role":"symbol","platforms":[],"title":"sendChatRating(_:completion:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendChatRating"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating","text":"ZDKRating","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating","text":"ZDKRating"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"sendChatRating:completion:","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendChatRating","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rating"},{"text":": ","kind":"text"},{"text":"ZDKRating","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatRating(_:completion:)-7hhpe"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating":{"title":"ZDKRating","url":"\/documentation\/chatproviderssdk\/zdkrating","navigatorTitle":[{"text":"ZDKRating","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRating"}],"kind":"symbol","abstract":[{"text":"A rating that can be assigned to the chat","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendChatRating(_:completion:)-7hhpe":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendChatRating","kind":"identifier"},{"kind":"text","text":"("},{"text":"ZDKRating","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating","text":"ZDKRating","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendchatrating(_:completion:)-7hhpe","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatRating(_:completion:)-7hhpe","kind":"symbol","navigatorTitle":[{"text":"sendChatRating:completion:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"title":"sendChatRating(_:completion:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatprovider","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"sendChatRating:completion:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendChatRating:completion:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendChatRating:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating"},{"text":") ","kind":"text"},{"text":"rating","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#$@M@ChatProvidersSDK@E@ZDKRating#*$objc(cs)NSError)","text":"void (^)(enum ZDKRating, NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"ZDKRating","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/title"},{"value":[{"text":"ZDKRating","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/fragments","op":"replace"},{"value":"sendChatRating:completion:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendChatRating(_:completion:)-7hhpe\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendChatRating(_:completion:)-7hhpe\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendChatRating:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","value":"ZDKChatProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatProvider"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}