{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendTyping"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isTyping"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"isTyping"}],"type":"paragraph"}],"name":"isTyping"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", the visitor typing indicator will appear in agent dashboard, else it will be hidden."}]}]}],"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"sendTypingWithIsTyping:"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider(im)sendTypingWithIsTyping:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendTyping"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isTyping"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"sendTyping(isTyping:)","modules":[{"name":"ChatProvidersSDK"}]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendTyping(isTyping:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Let’s the agent know when the visitor is typing."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendtyping(istyping:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendtyping(istyping:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatprovider","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendTyping(isTyping:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendTyping(isTyping:)","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendtyping(istyping:)","abstract":[{"text":"Let’s the agent know when the visitor is typing.","type":"text"}],"kind":"symbol","title":"sendTyping(isTyping:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendTyping"},{"text":"(","kind":"text"},{"text":"isTyping","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sendTypingWithIsTyping:"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"sendTypingWithIsTyping:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendTypingWithIsTyping:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sendTypingWithIsTyping:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isTyping","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKChatProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatProvider"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments"},{"value":"sendTypingWithIsTyping:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendTyping(isTyping:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendTyping(isTyping:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendTypingWithIsTyping:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}