{"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-1si17","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendOfflineForm"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"offlineForm"},{"kind":"text","text":": "},{"text":"OfflineForm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","text":"OfflineForm"},{"text":", ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","text":"DeliveryStatusError","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"offlineForm","content":[{"inlineContent":[{"type":"text","text":""},{"code":"OfflineForm","type":"codeVoice"},{"type":"text","text":" model"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"block that executes everytime there is an update to the ","type":"text"},{"code":"ChatState","type":"codeVoice"}]}]}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"name":"Warning","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Make sure the email field is filled in the "},{"type":"codeVoice","code":"VisitorInfo"},{"text":", or the form will fail to send","type":"text"}],"type":"paragraph"}],"style":"warning"}],"kind":"content"}],"abstract":[{"type":"text","text":"Sends an offline form from the current visitor."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendofflineform(_:completion:)-1si17"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"sendOfflineForm(_:completion:)","roleHeading":"Instance Method","externalID":"s:16ChatProvidersSDK0A8ProviderC15sendOfflineForm_10completionyAA0fG0C_ys6ResultOyAgA19DeliveryStatusErrorOGcSgtF","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendOfflineForm","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"OfflineForm","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","text":"DeliveryStatusError"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatprovider","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DeliveryStatusError":{"url":"\/documentation\/chatproviderssdk\/deliverystatuserror","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","type":"topic","title":"DeliveryStatusError","navigatorTitle":[{"kind":"identifier","text":"DeliveryStatusError"}],"kind":"symbol","abstract":[{"type":"text","text":"Delivery status error describes the reason of a delivery failure"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryStatusError"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendOfflineForm(_:completion:)-1si17":{"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendofflineform(_:completion:)-1si17","type":"topic","role":"symbol","abstract":[{"text":"Sends an offline form from the current visitor.","type":"text"}],"kind":"symbol","title":"sendOfflineForm(_:completion:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-1si17","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendOfflineForm","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:s6ResultO","text":"Result","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm","text":"OfflineForm"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","text":"DeliveryStatusError","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/OfflineForm":{"url":"\/documentation\/chatproviderssdk\/offlineform","title":"OfflineForm","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","navigatorTitle":[{"text":"OfflineForm","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineForm"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Offline form is formed from the given fields:"},{"type":"text","text":" "},{"text":"visitor info - name, email, phone","type":"text"},{"type":"text","text":" "},{"text":"department - department id","type":"text"},{"type":"text","text":" "},{"type":"text","text":"message - visitor’s message"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","value":"ZDKChatProvider"},{"value":[{"text":"ZDKChatProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","op":"replace"},{"value":"ZDKOfflineForm","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKOfflineForm"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}