{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendFile(url:onProgress:completion:)-6mbcj"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"]]},"abstract":[{"type":"text","text":"Send an attachment message."}],"sections":[],"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Instance Method","externalID":"s:16ChatProvidersSDK0A8ProviderC8sendFile3url10onProgress10completiony10Foundation3URLV_ySdcSgys6ResultOyAA0A17AttachmentMessageCAA19DeliveryStatusErrorOGcSgtF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendFile","kind":"identifier"},{"kind":"text","text":"("},{"text":"url","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onProgress","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ((","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"ChatAttachmentMessage","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachmentMessage"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"symbolKind":"method","role":"symbol","title":"sendFile(url:onProgress:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatprovider\/sendfile(url:onprogress:completion:)-6mbcj"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendFile","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"onProgress"},{"kind":"text","text":": (("},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachmentMessage","kind":"typeIdentifier","text":"ChatAttachmentMessage","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"DeliveryStatusError","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"url","content":[{"inlineContent":[{"type":"text","text":"The file "},{"type":"codeVoice","code":"URL"},{"text":" of the attachment to send","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Handle file upload progress"}],"type":"paragraph"}],"name":"onProgress"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"Result<ChatAttachment, DeliveryStatusError>","type":"codeVoice"},{"type":"text","text":" closure to handle whether the file sent successfully,"}]}],"name":"completion"}],"kind":"parameters"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendFile(url:onProgress:completion:)-6mbcj":{"abstract":[{"type":"text","text":"Send an attachment message."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendFile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"url","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"onProgress","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachmentMessage","text":"ChatAttachmentMessage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO","kind":"typeIdentifier","text":"DeliveryStatusError"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"sendFile(url:onProgress:completion:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendFile(url:onProgress:completion:)-6mbcj","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendfile(url:onprogress:completion:)-6mbcj","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage":{"title":"ChatAttachmentMessage","navigatorTitle":[{"text":"ChatAttachmentMessage","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAttachmentMessage"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","abstract":[{"type":"text","text":"The Chat Log attachment"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatattachmentmessage","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DeliveryStatusError":{"url":"\/documentation\/chatproviderssdk\/deliverystatuserror","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","type":"topic","title":"DeliveryStatusError","navigatorTitle":[{"kind":"identifier","text":"DeliveryStatusError"}],"kind":"symbol","abstract":[{"type":"text","text":"Delivery status error describes the reason of a delivery failure"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeliveryStatusError"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatprovider","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ChatProvider","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/title","value":"ZDKChatAttachmentMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/fragments","value":[{"kind":"identifier","text":"ZDKChatAttachmentMessage"}],"op":"replace"},{"value":"ZDKChatProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatProvider"}]}]}]}