{"variants":[{"paths":["\/documentation\/chatproviderssdk\/accountprovider\/getaccount(_:)-3dcew"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider\/getAccount(_:)-3dcew","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAccount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","text":"Account"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]}],"abstract":[{"type":"text","text":"Gets the current state of the "},{"type":"codeVoice","code":"Account"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"ChatProvidersSDK"}],"externalID":"s:16ChatProvidersSDK15AccountProviderC03getD0yyys6ResultOyAA0D0Cs5Error_pGcF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getAccount","kind":"identifier"},{"text":"((","kind":"text"},{"text":"Result","preciseIdentifier":"s:s6ResultO","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Account","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","title":"getAccount(_:)"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider/getAccount(_:)-3dcew":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getAccount"},{"text":"((","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":", "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider\/getAccount(_:)-3dcew","url":"\/documentation\/chatproviderssdk\/accountprovider\/getaccount(_:)-3dcew","title":"getAccount(_:)","type":"topic","abstract":[{"type":"text","text":"Gets the current state of the "},{"type":"codeVoice","code":"Account"},{"type":"text","text":"."}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountProvider"}],"title":"AccountProvider","navigatorTitle":[{"kind":"identifier","text":"AccountProvider"}],"type":"topic","abstract":[{"type":"codeVoice","code":"ZDKChatAccountProvider"},{"type":"text","text":" gives the ability to observe account updates."}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/accountprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"role":"symbol","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"ZDKChatAccount","type":"codeVoice"},{"text":" model stores information about the chat account,","type":"text"},{"text":" ","type":"text"},{"text":"such as the current ","type":"text"},{"type":"codeVoice","code":"accountStatus"},{"text":" and the list of ","type":"text"},{"type":"codeVoice","code":"Department"},{"type":"text","text":"s associated with the account"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","navigatorTitle":[{"kind":"identifier","text":"Account"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Account"}],"url":"\/documentation\/chatproviderssdk\/account","title":"Account","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/title","value":"ZDKChatAccountProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatAccountProvider"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title","op":"replace","value":"ZDKChatAccount"},{"op":"replace","value":[{"text":"ZDKChatAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments"}]}]}