{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider\/observeAccount(identifier:_:)-2krhs"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"observeAccount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"text":", (","kind":"text"},{"text":"Account","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","kind":"typeIdentifier"}],"symbolKind":"method","title":"observeAccount(identifier:_:)","modules":[{"name":"ChatProvidersSDK"}],"externalID":"s:16ChatProvidersSDK15AccountProviderC07observeD010identifier_AA16ObservationTokenCAA20ObservableIdentifierO_yAA0D0CctF","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"observeAccount"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","text":"ObservableIdentifier"},{"kind":"text","text":" = .uuid(), "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","text":"Account"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"inlineContent":[{"type":"text","text":"ObservableIdentifier to be exclusive, or unique"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"block that executes everytime there is an update to the list of ","type":"text"},{"type":"codeVoice","code":"Account"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"code":"ObservationToken","type":"codeVoice"}]}]}],"abstract":[{"text":"Observe account updates","type":"text"}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/accountprovider\/observeaccount(identifier:_:)-2krhs"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservableIdentifier":{"navigatorTitle":[{"text":"ObservableIdentifier","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/observableidentifier","title":"ObservableIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","abstract":[{"text":"Enum to specify how to identify an object that is subscribe to an observable","type":"text"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableIdentifier"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountProvider"}],"title":"AccountProvider","navigatorTitle":[{"kind":"identifier","text":"AccountProvider"}],"type":"topic","abstract":[{"type":"codeVoice","code":"ZDKChatAccountProvider"},{"type":"text","text":" gives the ability to observe account updates."}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/accountprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"role":"symbol","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"ZDKChatAccount","type":"codeVoice"},{"text":" model stores information about the chat account,","type":"text"},{"text":" ","type":"text"},{"text":"such as the current ","type":"text"},{"type":"codeVoice","code":"accountStatus"},{"text":" and the list of ","type":"text"},{"type":"codeVoice","code":"Department"},{"type":"text","text":"s associated with the account"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","navigatorTitle":[{"kind":"identifier","text":"Account"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Account"}],"url":"\/documentation\/chatproviderssdk\/account","title":"Account","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"title":"ObservationToken","navigatorTitle":[{"text":"ObservationToken","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Unsubscribe from observers"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/observationtoken"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider/observeAccount(identifier:_:)-2krhs":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeAccount"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","kind":"typeIdentifier","text":"ObservableIdentifier"},{"text":", (","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken","kind":"typeIdentifier"}],"abstract":[{"text":"Observe account updates","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider\/observeAccount(identifier:_:)-2krhs","url":"\/documentation\/chatproviderssdk\/accountprovider\/observeaccount(identifier:_:)-2krhs","title":"observeAccount(identifier:_:)","type":"topic","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/title","value":"ZDKChatAccountProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/fragments","op":"replace","value":[{"text":"ZDKChatAccountProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title","op":"replace","value":"ZDKChatAccount"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments","value":[{"kind":"identifier","text":"ZDKChatAccount"}],"op":"replace"},{"op":"replace","value":"ZDKObservationToken","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title"},{"value":[{"kind":"identifier","text":"ZDKObservationToken"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}