{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Observe changes of the current "},{"type":"codeVoice","code":"VisitorInfo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(identifier:_:)-54w36"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(identifier:_:)-54w36","interfaceLanguage":"swift"},"metadata":{"externalID":"s:16ChatProvidersSDK15ProfileProviderC18observeVisitorInfo10identifier_AA16ObservationTokenCAA20ObservableIdentifierO_yAA0gH0CctF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"observeVisitorInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", ("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"observeVisitorInfo(identifier:_:)","symbolKind":"method","roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"observeVisitorInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","kind":"typeIdentifier","text":"ObservableIdentifier"},{"kind":"text","text":" = .uuid(), "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","kind":"typeIdentifier","text":"VisitorInfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"ObservableIdentifier to be exclusive, or unique","type":"text"}],"type":"paragraph"}],"name":"identifier"},{"content":[{"type":"paragraph","inlineContent":[{"text":"block that executes everytime there is an update to the ","type":"text"},{"type":"codeVoice","code":"VisitorInfo"}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ObservationToken"},{"type":"text","text":" that can cancel the subscription to the "},{"type":"codeVoice","code":"VisitorInfo"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"url":"\/documentation\/chatproviderssdk\/profileprovider","title":"ProfileProvider","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKProfileProvider"},{"type":"text","text":" contain APIs to update information about a visitor."},{"type":"text","text":" "},{"text":"Such as name, email, phone number, tags, and notes related to the visitor and their session.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileProvider"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"url":"\/documentation\/chatproviderssdk\/visitorinfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Visitor information that can be seen in the Chat dashboard"},{"type":"text","text":" "},{"type":"text","text":"Contains "},{"type":"codeVoice","code":"name"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"phoneNumber"}],"title":"VisitorInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisitorInfo","kind":"identifier"}],"navigatorTitle":[{"text":"VisitorInfo","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"kind":"symbol","abstract":[{"type":"text","text":"Unsubscribe from observers"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"title":"ObservationToken"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/observeVisitorInfo(identifier:_:)-54w36":{"kind":"symbol","abstract":[{"text":"Observe changes of the current ","type":"text"},{"type":"codeVoice","code":"VisitorInfo"}],"title":"observeVisitorInfo(identifier:_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/observeVisitorInfo(identifier:_:)-54w36","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeVisitorInfo"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", ("},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","kind":"typeIdentifier","text":"ObservationToken"}],"url":"\/documentation\/chatproviderssdk\/profileprovider\/observevisitorinfo(identifier:_:)-54w36"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservableIdentifier":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ObservableIdentifier","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ObservableIdentifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/observableidentifier","abstract":[{"type":"text","text":"Enum to specify how to identify an object that is subscribe to an observable"}],"title":"ObservableIdentifier","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKProfileProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title"},{"value":[{"kind":"identifier","text":"ZDKProfileProvider"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title","value":"ZDKVisitorInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments","value":[{"text":"ZDKVisitorInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","value":"ZDKObservationToken"},{"value":[{"kind":"identifier","text":"ZDKObservationToken"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments"}]}]}