{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/removeTags(_:completion:)-4n2ur"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider"]]},"metadata":{"symbolKind":"method","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKProfileProvider(im)removeTags:completion:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeTags"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (([","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","platforms":[],"navigatorTitle":[{"text":"removeTags:completion:","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Instance Method","title":"removeTags(_:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/profileprovider\/removetags(_:completion:)-4n2ur"]},{"paths":["\/documentation\/chatproviderssdk\/profileprovider\/removetags(_:completion:)-4n2ur"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeTags","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tags","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider/removeTags(_:completion:)-4n2ur":{"url":"\/documentation\/chatproviderssdk\/profileprovider\/removetags(_:completion:)-4n2ur","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeTags","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ((["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider\/removeTags(_:completion:)-4n2ur","navigatorTitle":[{"text":"removeTags:completion:","kind":"identifier"}],"type":"topic","title":"removeTags(_:completion:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"url":"\/documentation\/chatproviderssdk\/profileprovider","title":"ProfileProvider","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKProfileProvider"},{"type":"text","text":" contain APIs to update information about a visitor."},{"type":"text","text":" "},{"text":"Such as name, email, phone number, tags, and notes related to the visitor and their session.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileProvider"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"removeTags:completion:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeTags:completion:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"removeTags:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"text":"tags","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)","text":"void (^)(NSArray<NSString *> *, NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"removeTags:completion:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1removeTags(_:completion:)-4n2ur\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider~1removeTags(_:completion:)-4n2ur\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeTags:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title","op":"replace","value":"ZDKProfileProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","value":[{"kind":"identifier","text":"ZDKProfileProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}