{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"text":"Agent","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isChatting"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chatId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"department"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","text":"Department"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"logs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","text":"ChatLog","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"queue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"comment"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"rating","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK6RatingO","text":"Rating","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Rating"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-8f7ix","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"]]},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatstate\/init(agents:ischatting:chatid:department:logs:queue:comment:rating:)-8f7ix"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Agent","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"isChatting"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"chatId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"department"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","text":"Department"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"logs"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","text":"ChatLog","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"comment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rating","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:16ChatProvidersSDK6RatingO","kind":"typeIdentifier","text":"Rating"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"init(agents:isChatting:chatId:department:logs:queue:comment:rating:)","externalID":"s:16ChatProvidersSDK0A5StateC6agents10isChatting6chatId10department4logs5queue7comment6ratingACSayAA5AgentCG_SbSSSgAA10DepartmentCSgSayAA0A3LogCGSiSSAA6RatingOtcfc","roleHeading":"Initializer"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department":{"title":"Department","role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/department","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Department"}],"navigatorTitle":[{"text":"Department","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","abstract":[{"type":"text","text":"Department model contains id associated with the department,"},{"type":"text","text":" "},{"text":"the department name, and the current status of the department.","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent":{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKAgent"},{"type":"text","text":" model has information about an agent in a chat session,"},{"type":"text","text":" "},{"type":"text","text":"such as their backend "},{"code":"id","type":"codeVoice"},{"text":" represented as ","type":"text"},{"code":"nick","type":"codeVoice"},{"text":", their display ","type":"text"},{"code":"name","type":"codeVoice"},{"type":"text","text":", their "},{"type":"codeVoice","code":"avatar"},{"type":"text","text":", and if they’re currently typing."}],"role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/agent","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Agent","kind":"identifier"}],"navigatorTitle":[{"text":"Agent","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","title":"Agent"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"navigatorTitle":[{"text":"ChatState","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatstate","abstract":[{"code":"ZDKChatState","type":"codeVoice"},{"text":" is a model representation of the current chat session.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"ChatState","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-8f7ix":{"title":"init(agents:isChatting:chatId:department:logs:queue:comment:rating:)","role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatstate\/init(agents:ischatting:chatid:department:logs:queue:comment:rating:)-8f7ix","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"agents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","text":"Agent"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"isChatting"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"chatId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"department"},{"text":": ","kind":"text"},{"text":"Department","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"logs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatLog","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog"},{"text":"], ","kind":"text"},{"text":"queue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"comment","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"rating"},{"kind":"text","text":": "},{"preciseIdentifier":"s:16ChatProvidersSDK6RatingO","text":"Rating","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-8f7ix","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Rating":{"abstract":[{"text":"A rating that can be assigned to the chat","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/rating","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Rating"}],"navigatorTitle":[{"kind":"identifier","text":"Rating"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Rating","title":"Rating"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Base class for chat log events that may occur in a chat session"}],"title":"ChatLog","url":"\/documentation\/chatproviderssdk\/chatlog","role":"symbol","navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/title","value":"ZDKDepartment","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/fragments","value":[{"kind":"identifier","text":"ZDKDepartment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/title","value":"ZDKAgent"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/fragments","value":[{"kind":"identifier","text":"ZDKAgent"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","value":"ZDKChatState"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatState"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments"},{"op":"replace","value":"ZDKChatLog","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","value":[{"text":"ZDKChatLog","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}