{"metadata":{"role":"symbol","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatParticipant@ZDKChatParticipantSystem","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"system","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"title":"ChatParticipant.system","navigatorTitle":[{"text":"ZDKChatParticipantSystem","kind":"identifier"}],"symbolKind":"case"},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/system","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Message came from chat backend"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"system","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatparticipant\/system"]},{"paths":["\/documentation\/chatproviderssdk\/chatparticipant\/system"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant":{"navigatorTitle":[{"text":"ChatParticipant","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatParticipant"}],"kind":"symbol","abstract":[{"text":"Who sent the message can be user\/agent\/trigger","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatparticipant","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant","title":"ChatParticipant","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/system":{"navigatorTitle":[{"text":"ZDKChatParticipantSystem","kind":"identifier"}],"abstract":[{"text":"Message came from chat backend","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatparticipant\/system","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/system","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"}],"title":"ChatParticipant.system"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKChatParticipantSystem","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"ZDKChatParticipantSystem","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKChatParticipantSystem","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/title","value":"ZDKChatParticipant","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/fragments","value":[{"kind":"identifier","text":"ZDKChatParticipant"}]},{"op":"replace","value":"ZDKChatParticipantSystem","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1system\/title"},{"value":[{"kind":"identifier","text":"ZDKChatParticipantSystem"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1system\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}