{"abstract":[{"type":"text","text":"Message came from the visitor"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatparticipant\/visitor"]},{"paths":["\/documentation\/chatproviderssdk\/chatparticipant\/visitor"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant"]]},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Case","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatParticipant@ZDKChatParticipantVisitor","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visitor","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKChatParticipantVisitor","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"ChatParticipant.visitor"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/visitor","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visitor"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant":{"navigatorTitle":[{"text":"ChatParticipant","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatParticipant"}],"kind":"symbol","abstract":[{"text":"Who sent the message can be user\/agent\/trigger","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatparticipant","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant","title":"ChatParticipant","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/visitor":{"role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatparticipant\/visitor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"visitor","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/visitor","navigatorTitle":[{"text":"ZDKChatParticipantVisitor","kind":"identifier"}],"abstract":[{"type":"text","text":"Message came from the visitor"}],"title":"ChatParticipant.visitor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatParticipantVisitor"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKChatParticipantVisitor","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKChatParticipantVisitor","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/title","value":"ZDKChatParticipant","op":"replace"},{"value":[{"text":"ZDKChatParticipant","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1visitor\/title","op":"replace","value":"ZDKChatParticipantVisitor"},{"value":[{"text":"ZDKChatParticipantVisitor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1visitor\/fragments"}]}]}