{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode"]]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/externaluseridhaschanged"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/externaluseridhaschanged"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"externalUserIdHasChanged"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/externalUserIdHasChanged"},"sections":[],"metadata":{"navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode@ZDKAuthenticationErrorCodeExternalUserIdHasChanged","modules":[{"name":"ChatProvidersSDK"}],"title":"AuthenticationErrorCode.externalUserIdHasChanged","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"externalUserIdHasChanged","kind":"identifier"}],"roleHeading":"Case"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorCode"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","role":"symbol","kind":"symbol","title":"AuthenticationErrorCode","abstract":[{"type":"text","text":"Possible Authentication related error codes"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationErrorCode","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/externalUserIdHasChanged":{"title":"AuthenticationErrorCode.externalUserIdHasChanged","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/externaluseridhaschanged","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"externalUserIdHasChanged"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/externalUserIdHasChanged"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title","value":"ZDKAuthenticationErrorCode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1externalUserIdHasChanged\/title","value":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged"},{"value":[{"text":"ZDKAuthenticationErrorCodeExternalUserIdHasChanged","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1externalUserIdHasChanged\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}