{"variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/internalservererror"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/internalservererror"]}],"metadata":{"externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode@ZDKAuthenticationErrorCodeInternalServerError","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInternalServerError"}],"roleHeading":"Case","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalServerError","kind":"identifier"}],"symbolKind":"case","title":"AuthenticationErrorCode.internalServerError"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalServerError"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalServerError","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode"]]},"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/internalServerError":{"title":"AuthenticationErrorCode.internalServerError","role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/internalservererror","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/internalServerError","navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInternalServerError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerError"}],"abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorCode"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","role":"symbol","kind":"symbol","title":"AuthenticationErrorCode","abstract":[{"type":"text","text":"Possible Authentication related error codes"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationErrorCode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"ZDKAuthenticationErrorCodeInternalServerError","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKAuthenticationErrorCodeInternalServerError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInternalServerError"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKAuthenticationErrorCodeInternalServerError","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1internalServerError\/title"},{"value":[{"text":"ZDKAuthenticationErrorCodeInternalServerError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1internalServerError\/fragments"},{"value":"ZDKAuthenticationErrorCode","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments","value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCode"}],"op":"replace"}]}]}