{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccountkey"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccountkey"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccountKey","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"AuthenticationErrorCode.invalidAccountKey","roleHeading":"Case","externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode@ZDKAuthenticationErrorCodeInvalidAccountKey","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidAccountKey"}],"navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidAccountKey","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidAccountKey","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidAccountKey":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidAccountKey","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKAuthenticationErrorCodeInvalidAccountKey","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidaccountkey","role":"symbol","type":"topic","title":"AuthenticationErrorCode.invalidAccountKey","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidAccountKey"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorCode"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","role":"symbol","kind":"symbol","title":"AuthenticationErrorCode","abstract":[{"type":"text","text":"Possible Authentication related error codes"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationErrorCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"ZDKAuthenticationErrorCodeInvalidAccountKey","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKAuthenticationErrorCodeInvalidAccountKey","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ZDKAuthenticationErrorCodeInvalidAccountKey","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKAuthenticationErrorCodeInvalidAccountKey","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccountKey\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidAccountKey\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeInvalidAccountKey","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title","value":"ZDKAuthenticationErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments","value":[{"text":"ZDKAuthenticationErrorCode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}