{"variants":[{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidname"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidName"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidName"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"title":"AuthenticationErrorCode.invalidName","roleHeading":"Case","externalID":"c:@M@ChatProvidersSDK@E@ZDKAuthenticationErrorCode@ZDKAuthenticationErrorCodeInvalidName","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidName","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidName"}]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","navigatorTitle":[{"kind":"identifier","text":"AuthenticationErrorCode"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","role":"symbol","kind":"symbol","title":"AuthenticationErrorCode","abstract":[{"type":"text","text":"Possible Authentication related error codes"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationErrorCode","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode/invalidName":{"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode\/invalidname","navigatorTitle":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidName"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode\/invalidName","role":"symbol","kind":"symbol","title":"AuthenticationErrorCode.invalidName","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidName","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"ZDKAuthenticationErrorCodeInvalidName","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidName"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKAuthenticationErrorCodeInvalidName"}],"languages":["occ"]}]}},{"op":"replace","value":"ZDKAuthenticationErrorCode","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title"},{"op":"replace","value":[{"text":"ZDKAuthenticationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidName\/title","value":"ZDKAuthenticationErrorCodeInvalidName"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode~1invalidName\/fragments","value":[{"text":"ZDKAuthenticationErrorCodeInvalidName","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}