{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department\/departmentStatus","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"departmentStatus","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment(py)departmentStatus","title":"departmentStatus","platforms":[],"role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"departmentStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ZDKDepartmentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDepartmentStatus"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departmentStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDepartmentStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","kind":"typeIdentifier","text":"ZDKDepartmentStatus"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department"]]},"variants":[{"paths":["\/documentation\/chatproviderssdk\/department\/departmentstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/department\/departmentstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Activity status of the department. ","type":"text"},{"code":"online","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"offline","type":"codeVoice"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"away"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department/departmentStatus":{"navigatorTitle":[{"kind":"identifier","text":"departmentStatus"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departmentStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDepartmentStatus","text":"ZDKDepartmentStatus"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department\/departmentStatus","abstract":[{"type":"text","text":"Activity status of the department. "},{"code":"online","type":"codeVoice"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"offline"},{"text":"\/","type":"text"},{"type":"codeVoice","code":"away"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/department\/departmentstatus","title":"departmentStatus","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department":{"title":"Department","role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/department","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Department"}],"navigatorTitle":[{"text":"Department","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","abstract":[{"type":"text","text":"Department model contains id associated with the department,"},{"type":"text","text":" "},{"text":"the department name, and the current status of the department.","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDepartmentStatus"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus","navigatorTitle":[{"text":"ZDKDepartmentStatus","kind":"identifier"}],"role":"symbol","title":"ZDKDepartmentStatus","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"departmentStatus","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"departmentStatus"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKDepartmentStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDepartmentStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"departmentStatus"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department~1departmentStatus\/title","value":"departmentStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department~1departmentStatus\/fragments","value":[{"kind":"identifier","text":"departmentStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/title","value":"ZDKDepartment","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/fragments","value":[{"kind":"identifier","text":"ZDKDepartment"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/title","value":"ZDKDepartmentStatus","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKDepartmentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/fragments"}]}]}