{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeliveryStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/zdkdeliverystatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/zdkdeliverystatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Delivery Status of the "},{"type":"codeVoice","code":"ChatLog"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeliveryStatus"}],"title":"ZDKDeliveryStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/delivered","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/failed","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/pending"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/rawrepresentable-implementations"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/equatable-implementations"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/delivered":{"role":"symbol","title":"ZDKDeliveryStatus.delivered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delivered"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/delivered","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatusDelivered"}],"url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/delivered"},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/init(rawvalue:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus":{"role":"symbol","title":"ZDKDeliveryStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeliveryStatus"}],"abstract":[{"type":"text","text":"Delivery Status of the "},{"type":"codeVoice","code":"ChatLog"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatus"}],"url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/pending":{"role":"symbol","title":"ZDKDeliveryStatus.pending","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/pending","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatusPending"}],"url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/pending"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus/failed":{"role":"symbol","title":"ZDKDeliveryStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKDeliveryStatusFailed"}],"url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus\/failed"},"doc://com.zendesk.ChatProvidersSDK/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ZDKDeliveryStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKDeliveryStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKDeliveryStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/delivered","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/failed","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus\/pending"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeliveryStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1delivered\/title","value":"ZDKDeliveryStatusDelivered"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1delivered\/fragments","value":[{"kind":"identifier","text":"ZDKDeliveryStatusDelivered"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/title","value":"ZDKDeliveryStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/fragments","value":[{"kind":"identifier","text":"ZDKDeliveryStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1pending\/title","value":"ZDKDeliveryStatusPending"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1pending\/fragments","value":[{"kind":"identifier","text":"ZDKDeliveryStatusPending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1failed\/title","value":"ZDKDeliveryStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus~1failed\/fragments","value":[{"kind":"identifier","text":"ZDKDeliveryStatusFailed"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}