{"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatInfo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Logger","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObserveBehaviour","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObserveBehaviours","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/QueuePosition","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Reachability","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorPath"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatForm","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Log","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LoggerFactory","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Observable","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ReachabilityProtocol"],"title":"Protocols"},{"title":"Structures","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DebugLogger","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DecodeAsString","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ReachabilityAttributes"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DepartmentStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/MimeUtils","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Rating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Foundation"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"metadata":{"externalID":"ChatProvidersSDK","role":"collection","symbolKind":"module","modules":[{"name":"ChatProvidersSDK"}],"roleHeading":"Framework","title":"ChatProvidersSDK"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[[]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Reachability":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Reachability","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Reachability","kind":"identifier"}],"navigatorTitle":[{"text":"Reachability","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/reachability","title":"Reachability","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LoggerFactory":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"LoggerFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LoggerFactory"}],"type":"topic","abstract":[{"type":"text","text":"Factory for obtaining namespaced loggers."}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LoggerFactory","url":"\/documentation\/chatproviderssdk\/loggerfactory","title":"LoggerFactory","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatError":{"navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError","url":"\/documentation\/chatproviderssdk\/chaterror","type":"topic","title":"ChatError","abstract":[{"type":"text","text":"Potential errors returned from the ChatProviderSDK"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"abstract":[{"type":"text","text":"Unsubscribe from observers"}],"type":"topic","navigatorTitle":[{"text":"ObservationToken","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ObservationToken","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","title":"ObservationToken","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"url":"\/documentation\/chatproviderssdk\/chatlogtype","title":"ChatLogType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatLogType","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Log":{"abstract":[{"text":"Simple log interface to allow implementations as preferred.","type":"text"}],"navigatorTitle":[{"text":"Log","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Log","kind":"identifier"}],"type":"topic","role":"symbol","title":"Log","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Log","url":"\/documentation\/chatproviderssdk\/log","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatInfo":{"abstract":[{"type":"codeVoice","code":"ZDKChatInfo"},{"type":"text","text":" contains information about the chat session, such as if there is a chat ongoing."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatInfo","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatinfo","title":"ChatInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatInfo"}],"navigatorTitle":[{"text":"ChatInfo","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/LogLevel":{"title":"LogLevel","url":"\/documentation\/chatproviderssdk\/loglevel","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"kind":"symbol","abstract":[{"text":"Log level enum (Based on Android log vals).","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogLevel"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DeliveryStatusError":{"navigatorTitle":[{"kind":"identifier","text":"DeliveryStatusError"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatusError","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/deliverystatuserror","title":"DeliveryStatusError","abstract":[{"text":"Delivery status error describes the reason of a delivery failure","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeliveryStatusError","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatLogProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatLogProtocol"}],"type":"topic","abstract":[{"text":"Base protocol representation of a ","type":"text"},{"type":"codeVoice","code":"ChatLog"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol","url":"\/documentation\/chatproviderssdk\/chatlogprotocol","title":"ChatLogProtocol","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Loggable":{"navigatorTitle":[{"kind":"identifier","text":"Loggable"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Loggable","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","url":"\/documentation\/chatproviderssdk\/loggable","type":"topic","title":"Loggable","abstract":[{"type":"text","text":"Protocol that conforms"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatErrorDomain":{"fragments":[{"text":"ChatErrorDomain","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatErrorDomain","title":"ChatErrorDomain","url":"\/documentation\/chatproviderssdk\/chaterrordomain","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DeliveryStatus":{"navigatorTitle":[{"text":"DeliveryStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DeliveryStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/deliverystatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DeliveryStatus","abstract":[{"type":"text","text":"Delivery Status of the "},{"code":"ChatLog","type":"codeVoice"}],"type":"topic","title":"DeliveryStatus","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushNotificationsProvider","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKPushNoticiationProvider"},{"type":"text","text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications."}],"type":"topic","kind":"symbol","title":"PushNotificationsProvider","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","navigatorTitle":[{"text":"PushNotificationsProvider","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObserveBehaviour":{"kind":"symbol","abstract":[{"type":"text","text":"A convenience wrapper for the "},{"code":"ObservationToken","type":"codeVoice"},{"text":", that can be used alongside the ","type":"text"},{"type":"codeVoice","code":"ObserveBehaviours"},{"type":"text","text":" class"}],"title":"ObserveBehaviour","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObserveBehaviour","navigatorTitle":[{"text":"ObserveBehaviour","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ObserveBehaviour","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/observebehaviour"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration":{"type":"topic","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAPIConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"ChatAPIConfiguration"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","abstract":[{"text":"A set of configurations that are associated with each chat session.","type":"text"}],"role":"symbol","title":"ChatAPIConfiguration"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"abstract":[{"text":"Represents different states of the","type":"text"},{"type":"codeVoice","code":"ChatSession"}],"type":"topic","navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConnectionStatus","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","kind":"symbol","title":"ConnectionStatus","url":"\/documentation\/chatproviderssdk\/connectionstatus","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","title":"ChatLog","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}],"navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatlog","abstract":[{"type":"text","text":"Base class for chat log events that may occur in a chat session"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DepartmentStatus":{"navigatorTitle":[{"kind":"identifier","text":"DepartmentStatus"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DepartmentStatus","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/departmentstatus","title":"DepartmentStatus","abstract":[{"type":"text","text":"The status of the department."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DepartmentStatus"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatprovider","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"title":"ChatProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ProfileProvider":{"navigatorTitle":[{"kind":"identifier","text":"ProfileProvider"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileProvider"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/profileprovider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","abstract":[{"type":"text","text":"The "},{"code":"ZDKProfileProvider","type":"codeVoice"},{"type":"text","text":" contain APIs to update information about a visitor."},{"text":" ","type":"text"},{"text":"Such as name, email, phone number, tags, and notes related to the visitor and their session.","type":"text"}],"type":"topic","title":"ProfileProvider","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DebugLogger":{"kind":"symbol","url":"\/documentation\/chatproviderssdk\/debuglogger","abstract":[{"text":"Default\/debug logger.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DebugLogger","title":"DebugLogger","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugLogger"}],"navigatorTitle":[{"text":"DebugLogger","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","url":"\/documentation\/chatproviderssdk\/settingsprovider","navigatorTitle":[{"kind":"identifier","text":"SettingsProvider"}],"title":"SettingsProvider","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SettingsProvider","kind":"identifier"}],"abstract":[{"code":"ZDKSettingsProvider","type":"codeVoice"},{"type":"text","text":" gives the ability to observe settings updates."}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationErrorCode":{"kind":"symbol","title":"AuthenticationErrorCode","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AuthenticationErrorCode","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"AuthenticationErrorCode","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/authenticationerrorcode","abstract":[{"type":"text","text":"Possible Authentication related error codes"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Foundation":{"type":"topic","url":"\/documentation\/chatproviderssdk\/foundation","title":"Foundation","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Foundation","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/MimeUtils":{"navigatorTitle":[{"kind":"identifier","text":"MimeUtils"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MimeUtils","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/mimeutils","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/MimeUtils","type":"topic","abstract":[{"text":"Utilities for dealing with MIME types.","type":"text"}],"title":"MimeUtils","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/OfflineForm":{"navigatorTitle":[{"text":"OfflineForm","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/offlineform","title":"OfflineForm","abstract":[{"text":"Offline form is formed from the given fields:","type":"text"},{"text":" ","type":"text"},{"text":"visitor info - name, email, phone","type":"text"},{"type":"text","text":" "},{"type":"text","text":"department - department id"},{"text":" ","type":"text"},{"type":"text","text":"message - visitor’s message"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OfflineForm","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatOptionsMessage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatOptionsMessage","kind":"identifier"}],"navigatorTitle":[{"text":"ChatOptionsMessage","kind":"identifier"}],"type":"topic","abstract":[{"text":"Questions from agent with multiple options that a user can respond with","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","url":"\/documentation\/chatproviderssdk\/chatoptionsmessage","title":"ChatOptionsMessage","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservableIdentifier":{"navigatorTitle":[{"kind":"identifier","text":"ObservableIdentifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ObservableIdentifier","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","url":"\/documentation\/chatproviderssdk\/observableidentifier","type":"topic","title":"ObservableIdentifier","abstract":[{"text":"Enum to specify how to identify an object that is subscribe to an observable","type":"text"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Observable":{"kind":"symbol","abstract":[{"text":"Protocol that allows an object to be observed by other objects.","type":"text"}],"title":"Observable","role":"symbol","url":"\/documentation\/chatproviderssdk\/observable","navigatorTitle":[{"text":"Observable","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Observable","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Observable","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMemberJoin":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMemberJoin","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMemberJoin"}],"type":"topic","abstract":[{"text":"Chat Member Join event","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","url":"\/documentation\/chatproviderssdk\/chatmemberjoin","title":"ChatMemberJoin","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvidersSDKVersionNumber":{"fragments":[{"kind":"identifier","text":"ChatProvidersSDKVersionNumber"}],"type":"topic","abstract":[{"text":"Project version number for ChatProvidersSDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvidersSDKVersionNumber","title":"ChatProvidersSDKVersionNumber","url":"\/documentation\/chatproviderssdk\/chatproviderssdkversionnumber","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AuthenticationError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationError"}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"type":"topic","abstract":[{"text":"Possible Authentication related errors","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationError","title":"AuthenticationError","url":"\/documentation\/chatproviderssdk\/authenticationerror","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant":{"navigatorTitle":[{"kind":"identifier","text":"ChatParticipant"}],"abstract":[{"type":"text","text":"Who sent the message can be user\/agent\/trigger"}],"title":"ChatParticipant","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ChatParticipant","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatparticipant"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKPushNotificationType":{"fragments":[{"text":"ZDKPushNotificationType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKPushNotificationType","url":"\/documentation\/chatproviderssdk\/zdkpushnotificationtype","type":"topic","title":"ZDKPushNotificationType","abstract":[{"text":"Enum representing the different types of notifications that can be received for Chat","type":"text"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ReachabilityAttributes":{"navigatorTitle":[{"text":"ReachabilityAttributes","kind":"identifier"}],"type":"topic","title":"ReachabilityAttributes","abstract":[],"url":"\/documentation\/chatproviderssdk\/reachabilityattributes","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ReachabilityAttributes","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReachabilityAttributes"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","title":"ZDKRating","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKRating","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKRating","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating","abstract":[{"type":"text","text":"A rating that can be assigned to the chat"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","title":"Agent","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Agent"}],"navigatorTitle":[{"text":"Agent","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"ZDKAgent","type":"codeVoice"},{"type":"text","text":" model has information about an agent in a chat session,"},{"type":"text","text":" "},{"text":"such as their backend ","type":"text"},{"type":"codeVoice","code":"id"},{"type":"text","text":" represented as "},{"code":"nick","type":"codeVoice"},{"type":"text","text":", their display "},{"code":"name","type":"codeVoice"},{"text":", their ","type":"text"},{"type":"codeVoice","code":"avatar"},{"type":"text","text":", and if they’re currently typing."}],"type":"topic","url":"\/documentation\/chatproviderssdk\/agent"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionProvider":{"navigatorTitle":[{"kind":"identifier","text":"ConnectionProvider"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionprovider","title":"ConnectionProvider","abstract":[{"type":"codeVoice","code":"ZDKConnectionProvider"},{"text":" gives the ability to observe connection updates.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionProvider","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ReachabilityProtocol":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ReachabilityProtocol","url":"\/documentation\/chatproviderssdk\/reachabilityprotocol","navigatorTitle":[{"kind":"identifier","text":"ReachabilityProtocol"}],"title":"ReachabilityProtocol","kind":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReachabilityProtocol","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMemberLeave":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatMemberLeave","kind":"identifier"}],"navigatorTitle":[{"text":"ChatMemberLeave","kind":"identifier"}],"type":"topic","abstract":[{"text":"Chat Member Leave event","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","title":"ChatMemberLeave","url":"\/documentation\/chatproviderssdk\/chatmemberleave","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"navigatorTitle":[{"kind":"identifier","text":"ChatSettings"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatSettings"},{"text":" model stores information about the chat account’s settings,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"such as the "},{"code":"fileSizeLimit","type":"codeVoice"},{"text":", whether attachments are enabled, and the list of accepted file extensions.","type":"text"}],"role":"symbol","title":"ChatSettings","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSettings"}],"url":"\/documentation\/chatproviderssdk\/chatsettings","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"abstract":[{"code":"Chat","type":"codeVoice"},{"text":" is a singleton class of the ","type":"text"},{"type":"codeVoice","code":"ChatProviderSDK"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chat","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Logger":{"title":"Logger","abstract":[{"type":"text","text":"Singleton access point for logging, inject a LoggerFactory to specify the Logger."}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Logger","type":"topic","kind":"symbol","url":"\/documentation\/chatproviderssdk\/logger","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Logger","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorInfo":{"type":"topic","navigatorTitle":[{"text":"VisitorInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Visitor information that can be seen in the Chat dashboard","type":"text"},{"text":" ","type":"text"},{"text":"Contains ","type":"text"},{"type":"codeVoice","code":"name"},{"text":", ","type":"text"},{"code":"email","type":"codeVoice"},{"type":"text","text":", and "},{"type":"codeVoice","code":"phoneNumber"}],"url":"\/documentation\/chatproviderssdk\/visitorinfo","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"VisitorInfo","kind":"identifier"}],"title":"VisitorInfo"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountProvider":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","url":"\/documentation\/chatproviderssdk\/accountprovider","navigatorTitle":[{"text":"AccountProvider","kind":"identifier"}],"title":"AccountProvider","kind":"symbol","abstract":[{"code":"ZDKChatAccountProvider","type":"codeVoice"},{"type":"text","text":" gives the ability to observe account updates."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccountProvider","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/VisitorPath":{"abstract":[{"type":"text","text":"A Custom Update Event that can be seen in the agent dashboard."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorPath","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/visitorpath","title":"VisitorPath","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VisitorPath","kind":"identifier"}],"navigatorTitle":[{"text":"VisitorPath","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Providers":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","url":"\/documentation\/chatproviderssdk\/providers","navigatorTitle":[{"kind":"identifier","text":"Providers"}],"title":"Providers","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Providers","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ZDKChatProviders"},{"type":"text","text":" is a grouping of all the providers that allow you to, setup for push notifications,"},{"text":" ","type":"text"},{"text":"handle session updates, handle connection state, and interact with the APIs in other ways.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatRatingRequest":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatRatingRequest","kind":"identifier"}],"navigatorTitle":[{"text":"ChatRatingRequest","kind":"identifier"}],"type":"topic","abstract":[{"text":"Chat Rating Request (sent by the agent)","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest","title":"ChatRatingRequest","url":"\/documentation\/chatproviderssdk\/chatratingrequest","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMessage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMessage","kind":"identifier"}],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"type":"topic","abstract":[{"text":"Chat message","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","title":"ChatMessage","url":"\/documentation\/chatproviderssdk\/chatmessage","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAttachmentMessage","kind":"identifier"}],"navigatorTitle":[{"text":"ChatAttachmentMessage","kind":"identifier"}],"type":"topic","abstract":[{"text":"The Chat Log attachment","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","title":"ChatAttachmentMessage","url":"\/documentation\/chatproviderssdk\/chatattachmentmessage","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationData":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationData"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationdata","title":"PushNotificationData","type":"topic","role":"symbol","abstract":[{"code":"PushNotificationData","type":"codeVoice"},{"text":" can be used to gather information about Chat related push notifications","type":"text"}],"navigatorTitle":[{"text":"PushNotificationData","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/QueuePosition":{"navigatorTitle":[{"kind":"identifier","text":"QueuePosition"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/QueuePosition","role":"symbol","url":"\/documentation\/chatproviderssdk\/queueposition","type":"topic","title":"QueuePosition","abstract":[{"code":"ZDKQueuePosition","type":"codeVoice"},{"type":"text","text":" is a model that represents the current queue position of the visitor."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QueuePosition"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/JWTAuthenticator":{"type":"topic","abstract":[{"text":"Protocol that an object that handles authentication should conform to. Called by the ","type":"text"},{"type":"codeVoice","code":"ChatSDK"},{"type":"text","text":" everytime authentication is required."}],"navigatorTitle":[{"kind":"identifier","text":"JWTAuthenticator"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator","kind":"symbol","url":"\/documentation\/chatproviderssdk\/jwtauthenticator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JWTAuthenticator","kind":"identifier"}],"title":"JWTAuthenticator","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvidersSDKVersionString":{"abstract":[{"text":"Project version string for ChatProvidersSDK.","type":"text"}],"fragments":[{"text":"ChatProvidersSDKVersionString","kind":"identifier"}],"title":"ChatProvidersSDKVersionString","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvidersSDKVersionString","type":"topic","url":"\/documentation\/chatproviderssdk\/chatproviderssdkversionstring","kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatForm":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatForm"}],"navigatorTitle":[{"kind":"identifier","text":"ChatForm"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatForm","title":"ChatForm","url":"\/documentation\/chatproviderssdk\/chatform","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/DecodeAsString":{"kind":"symbol","title":"DecodeAsString","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/DecodeAsString","navigatorTitle":[{"text":"DecodeAsString","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DecodeAsString"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/decodeasstring"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","url":"\/documentation\/chatproviderssdk\/account","navigatorTitle":[{"text":"Account","kind":"identifier"}],"title":"Account","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKChatAccount"},{"text":" model stores information about the chat account,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as the current "},{"code":"accountStatus","type":"codeVoice"},{"text":" and the list of ","type":"text"},{"code":"Department","type":"codeVoice"},{"type":"text","text":"s associated with the account"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Account"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","title":"Department","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Department","kind":"identifier"}],"navigatorTitle":[{"text":"Department","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Department model contains id associated with the department,"},{"type":"text","text":" "},{"text":"the department name, and the current status of the department.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/department"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Rating":{"abstract":[{"type":"text","text":"A rating that can be assigned to the chat"}],"title":"Rating","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Rating"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Rating","role":"symbol","url":"\/documentation\/chatproviderssdk\/rating","navigatorTitle":[{"text":"Rating","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachment":{"title":"ChatAttachment","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAttachment"}],"navigatorTitle":[{"kind":"identifier","text":"ChatAttachment"}],"role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKChatAttachment"},{"text":" model, contains information about attachments that were sent or received","type":"text"},{"type":"text","text":" "},{"text":"by the visitor.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatattachment","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObserveBehaviours":{"navigatorTitle":[{"text":"ObserveBehaviours","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ObserveBehaviours","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/observebehaviours","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObserveBehaviours","type":"topic","abstract":[{"text":"A convenience wrapper for a collection of ","type":"text"},{"type":"codeVoice","code":"ObserveBehaviours"},{"text":".","type":"text"}],"title":"ObserveBehaviours","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","title":"ChatState","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatState"}],"type":"topic","abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"text":" is a model representation of the current chat session.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatstate"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatComment":{"navigatorTitle":[{"text":"ChatComment","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatComment","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatcomment","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","type":"topic","abstract":[{"type":"text","text":"Chat comment in relation to a Chat rating."}],"title":"ChatComment","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus":{"url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus","title":"ZDKDepartmentStatus","kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","navigatorTitle":[{"kind":"identifier","text":"ZDKDepartmentStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKDepartmentStatus"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus":{"kind":"symbol","abstract":[{"type":"text","text":"Account Status"}],"title":"AccountStatus","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","navigatorTitle":[{"text":"AccountStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AccountStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/accountstatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatRating":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatRating"}],"navigatorTitle":[{"text":"ChatRating","kind":"identifier"}],"type":"topic","abstract":[{"text":"A Chat rating left by the user after an agent requested it. Can be ","type":"text"},{"code":"none","type":"codeVoice"},{"text":", ","type":"text"},{"code":"good","type":"codeVoice"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"bad"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","url":"\/documentation\/chatproviderssdk\/chatrating","title":"ChatRating","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentError":{"kind":"symbol","abstract":[{"text":"The error of type ","type":"text"},{"type":"codeVoice","code":"ChatAttachmentError"},{"text":" is emitted when file upload has failed.","type":"text"}],"title":"ChatAttachmentError","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatattachmenterror","navigatorTitle":[{"text":"ChatAttachmentError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ChatAttachmentError","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentError","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDeliveryStatus":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","url":"\/documentation\/chatproviderssdk\/zdkdeliverystatus","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Delivery Status of the "},{"type":"codeVoice","code":"ChatLog"}],"navigatorTitle":[{"text":"ZDKDeliveryStatus","kind":"identifier"}],"title":"ZDKDeliveryStatus","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDeliveryStatus"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus":{"abstract":[{"type":"text","text":"Chat session status describes current state of the session"}],"title":"ChatSessionStatus","url":"\/documentation\/chatproviderssdk\/chatsessionstatus","navigatorTitle":[{"kind":"identifier","text":"ChatSessionStatus"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatSessionStatus","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatInfo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Logger","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/OfflineForm","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ProfileProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Providers","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/QueuePosition","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorInfo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/VisitorPath"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/JWTAuthenticator"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatErrorDomain","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvidersSDKVersionNumber","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvidersSDKVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AuthenticationErrorCode","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatError","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/LogLevel","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDeliveryStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKPushNotificationType","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating"]}],"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError\/title","value":"ChatError","op":"replace"},{"value":[{"text":"ChatError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatError\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","op":"replace","value":"ZDKObservationToken"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","value":[{"text":"ZDKObservationToken","kind":"identifier"}],"op":"replace"},{"value":"ZDKChatLogType","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatLogType"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments"},{"value":"ZDKChatInfo","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatInfo\/title"},{"value":[{"kind":"identifier","text":"ZDKChatInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatInfo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel\/title","value":"ZDKChatLogLevel"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogLevel"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1LogLevel\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/title","op":"replace","value":"ZDKPushNotificationsProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/fragments","value":[{"text":"ZDKPushNotificationsProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/title","op":"replace","value":"ZDKChatAPIConfiguration"},{"op":"replace","value":[{"text":"ZDKChatAPIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/fragments"},{"op":"replace","value":"ZDKConnectionStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments","op":"replace","value":[{"text":"ZDKConnectionStatus","kind":"identifier"}]},{"value":"ZDKChatLog","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","value":[{"text":"ZDKChatLog","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","value":"ZDKChatProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"text":"ZDKChatProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/title","value":"ZDKProfileProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ProfileProvider\/fragments","op":"replace","value":[{"text":"ZDKProfileProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/title","value":"ZDKSettingsProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/fragments","value":[{"text":"ZDKSettingsProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/title","value":"ZDKAuthenticationErrorCode","op":"replace"},{"op":"replace","value":[{"text":"ZDKAuthenticationErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AuthenticationErrorCode\/fragments"},{"value":"ZDKOfflineForm","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1OfflineForm\/fragments","value":[{"text":"ZDKOfflineForm","kind":"identifier"}]},{"op":"replace","value":"ZDKChatOptionsMessage","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatOptionsMessage\/title"},{"value":[{"kind":"identifier","text":"ZDKChatOptionsMessage"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatOptionsMessage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberJoin\/title","op":"replace","value":"ZDKChatMemberJoin"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberJoin\/fragments","value":[{"text":"ZDKChatMemberJoin","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/title","value":"ZDKChatParticipant"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/fragments","op":"replace","value":[{"text":"ZDKChatParticipant","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/title","op":"replace","value":"ZDKRating"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/fragments","value":[{"kind":"identifier","text":"ZDKRating"}],"op":"replace"},{"value":"ZDKAgent","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/fragments","value":[{"text":"ZDKAgent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/title","value":"ZDKConnectionProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionProvider\/fragments","op":"replace","value":[{"text":"ZDKConnectionProvider","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberLeave\/title","value":"ZDKChatMemberLeave","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberLeave\/fragments","value":[{"kind":"identifier","text":"ZDKChatMemberLeave"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title","value":"ZDKChatSettings"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments","value":[{"text":"ZDKChatSettings","kind":"identifier"}],"op":"replace"},{"value":"ZDKChat","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]},{"op":"replace","value":"ZDKChatLogger","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Logger\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Logger\/fragments","value":[{"text":"ZDKChatLogger","kind":"identifier"}]},{"op":"replace","value":"ZDKVisitorInfo","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKVisitorInfo"}]},{"value":"ZDKChatAccountProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountProvider\/fragments","value":[{"text":"ZDKChatAccountProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKVisitorPath","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorPath\/title"},{"value":[{"text":"ZDKVisitorPath","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1VisitorPath\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/title","value":"ZDKChatProviders"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Providers\/fragments","value":[{"kind":"identifier","text":"ZDKChatProviders"}]},{"value":"ZDKRatingRequest","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRatingRequest\/title","op":"replace"},{"value":[{"text":"ZDKRatingRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRatingRequest\/fragments"},{"op":"replace","value":"ZDKChatMessage","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/fragments","value":[{"text":"ZDKChatMessage","kind":"identifier"}]},{"op":"replace","value":"ZDKChatAttachmentMessage","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/title"},{"value":[{"text":"ZDKChatAttachmentMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData\/title","value":"ZDKPushNotificationData","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData\/fragments","value":[{"text":"ZDKPushNotificationData","kind":"identifier"}]},{"value":"ZDKQueuePosition","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1QueuePosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1QueuePosition\/fragments","value":[{"text":"ZDKQueuePosition","kind":"identifier"}]},{"value":"ZDKJWTAuthenticator","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1JWTAuthenticator\/fragments","value":[{"kind":"identifier","text":"ZDKJWTAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title","value":"ZDKChatAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments","value":[{"text":"ZDKChatAccount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/title","op":"replace","value":"ZDKDepartment"},{"value":[{"text":"ZDKDepartment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/fragments"},{"value":"ZDKChatAttachment","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachment\/fragments","value":[{"text":"ZDKChatAttachment","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","value":"ZDKChatState"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","value":[{"text":"ZDKChatState","kind":"identifier"}]},{"value":"ZDKChatComment","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatComment\/title","op":"replace"},{"value":[{"text":"ZDKChatComment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatComment\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/title","op":"replace","value":"ZDKDepartmentStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/fragments","value":[{"kind":"identifier","text":"ZDKDepartmentStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/title","value":"ZDKChatAccountStatus"},{"value":[{"text":"ZDKChatAccountStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRating\/title","value":"ZDKChatRating"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRating\/fragments","value":[{"kind":"identifier","text":"ZDKChatRating"}]},{"op":"replace","value":"ZDKDeliveryStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDeliveryStatus\/fragments","value":[{"text":"ZDKDeliveryStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/title","op":"replace","value":"ChatSessionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/fragments","value":[{"text":"ChatSessionStatus","kind":"identifier"}]}]}]}