{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","title":"Account","symbolKind":"class","navigatorTitle":[{"text":"Account","kind":"identifier"}],"roleHeading":"Class","role":"symbol","modules":[{"name":"ChatProvidersSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatAccount) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}]}]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"ZDKChatAccount"},{"type":"text","text":" model stores information about the chat account,"},{"text":" ","type":"text"},{"type":"text","text":"such as the current "},{"type":"codeVoice","code":"accountStatus"},{"type":"text","text":" and the list of "},{"type":"codeVoice","code":"Department"},{"type":"text","text":"s associated with the account"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/account"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/account"]}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/init(accountStatus:departments:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/accountStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/departments","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/description"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/containsDepartment(with:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/isEqual(_:)"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/initial"],"title":"Type Properties"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/accountStatus":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"accountStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AccountStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/accountStatus","type":"topic","title":"accountStatus","navigatorTitle":[{"text":"accountStatus","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/accountstatus","abstract":[{"type":"text","text":"The current status of the "},{"type":"codeVoice","code":"Account"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/departments":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"departments","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Department","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/departments","type":"topic","title":"departments","navigatorTitle":[{"text":"departments","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/departments","abstract":[{"type":"codeVoice","code":"[Department]"},{"type":"text","text":" in the chat instance"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/description","type":"topic","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/description","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/isEqual(_:)","type":"topic","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/isequal(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/init(accountStatus:departments:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accountStatus","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AccountStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus"},{"kind":"text","text":", "},{"text":"departments","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Department","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment"},{"text":"]?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/init(accountStatus:departments:)","type":"topic","title":"init(accountStatus:departments:)","navigatorTitle":[{"text":"initWithAccountStatus:departments:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/init(accountstatus:departments:)","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/containsDepartment(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"containsDepartment"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/containsDepartment(with:)","type":"topic","title":"containsDepartment(with:)","navigatorTitle":[{"text":"containsDepartmentWith:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/containsdepartment(with:)","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/initial":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initial"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount","text":"Account"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/initial","type":"topic","title":"initial","role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/initial","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account","type":"topic","title":"Account","navigatorTitle":[{"text":"Account","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatAccount"},{"type":"text","text":" model stores information about the chat account,"},{"type":"text","text":" "},{"text":"such as the current ","type":"text"},{"type":"codeVoice","code":"accountStatus"},{"text":" and the list of ","type":"text"},{"type":"codeVoice","code":"Department"},{"type":"text","text":"s associated with the account"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/debugDescription":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/debugDescription","type":"topic","title":"debugDescription","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/debugdescription","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ZDKChatAccount"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKChatAccount","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKChatAccount","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/accountStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/departments","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/description"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/containsDepartment(with:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/init(accountStatus:departments:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKChatAccount","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1accountStatus\/title","value":"accountStatus"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1accountStatus\/fragments","op":"replace","value":[{"text":"accountStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1departments\/title","value":"departments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1departments\/fragments","value":[{"text":"departments","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1description\/title","op":"replace","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1description\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1init(accountStatus:departments:)\/title","value":"initWithAccountStatus:departments:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1init(accountStatus:departments:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAccountStatus:departments:","kind":"identifier"}]},{"value":"containsDepartmentWith:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1containsDepartment(with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1containsDepartment(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"containsDepartmentWith:","kind":"identifier"}]},{"value":"ZDKChatAccount","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments","op":"replace","value":[{"text":"ZDKChatAccount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1debugDescription\/title","op":"replace","value":"debugDescription"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1debugDescription\/fragments","value":[{"text":"debugDescription","kind":"identifier"}],"op":"replace"}]}]}