{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/Se","doc:\/\/com.zendesk.ChatProvidersSDK\/SE","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The "},{"code":"ZDKAgent","type":"codeVoice"},{"text":" model has information about an agent in a chat session,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as their backend "},{"type":"codeVoice","code":"id"},{"type":"text","text":" represented as "},{"type":"codeVoice","code":"nick"},{"type":"text","text":", their display "},{"code":"name","type":"codeVoice"},{"text":", their ","type":"text"},{"type":"codeVoice","code":"avatar"},{"type":"text","text":", and if they’re currently typing."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKAgent) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Agent","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/agent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/agent"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/init(avatar:nick:displayName:isTyping:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/avatar","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/displayName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/isTyping","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/nick"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/isEqual(_:)"]}],"metadata":{"title":"Agent","symbolKind":"class","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Agent"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Agent"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent"},"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/avatar":{"type":"topic","abstract":[{"type":"text","text":"The URL of the agent’s avatar if it’s present"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/avatar","title":"avatar","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"avatar","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"avatar","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/agent\/avatar","role":"symbol","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/init(from:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/init(from:)","title":"init(from:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/chatproviderssdk\/agent\/init(from:)","role":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/init(avatar:nick:displayName:isTyping:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/init(avatar:nick:displayName:isTyping:)","title":"init(avatar:nick:displayName:isTyping:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"avatar","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"nick","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTyping"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithAvatar:nick:displayName:isTyping:","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/agent\/init(avatar:nick:displayname:istyping:)","role":"symbol","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/nick":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nick","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/nick","type":"topic","title":"nick","navigatorTitle":[{"kind":"identifier","text":"nick"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/agent\/nick","abstract":[{"text":"ID associated with the agent","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/isEqual(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/isEqual(_:)","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/chatproviderssdk\/agent\/isequal(_:)","role":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/description":{"kind":"symbol","abstract":[],"title":"description","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/chatproviderssdk\/agent\/description"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/debugDescription":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/debugDescription","title":"debugDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/agent\/debugdescription","role":"symbol","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/Se":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/isTyping":{"type":"topic","abstract":[{"type":"text","text":"Whether the agent is currently typing in the chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/isTyping","title":"isTyping","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTyping","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isTyping"}],"url":"\/documentation\/chatproviderssdk\/agent\/istyping","role":"symbol","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent/displayName":{"kind":"symbol","abstract":[{"text":"The display name of the agent","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/displayName","title":"displayName","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"displayName","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/agent\/displayname","role":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/SE":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent":{"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKAgent"},{"type":"text","text":" model has information about an agent in a chat session,"},{"text":" ","type":"text"},{"text":"such as their backend ","type":"text"},{"type":"codeVoice","code":"id"},{"type":"text","text":" represented as "},{"type":"codeVoice","code":"nick"},{"text":", their display ","type":"text"},{"type":"codeVoice","code":"name"},{"text":", their ","type":"text"},{"type":"codeVoice","code":"avatar"},{"type":"text","text":", and if they’re currently typing."}],"title":"Agent","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Agent"}],"navigatorTitle":[{"text":"Agent","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/agent"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKAgent","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKAgent"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ZDKAgent","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/avatar","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/displayName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/isTyping","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/nick"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/init(avatar:nick:displayName:isTyping:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent\/isEqual(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKAgent"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1avatar\/title","value":"avatar"},{"value":[{"text":"avatar","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1avatar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1init(avatar:nick:displayName:isTyping:)\/title","op":"replace","value":"initWithAvatar:nick:displayName:isTyping:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAvatar:nick:displayName:isTyping:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1init(avatar:nick:displayName:isTyping:)\/fragments"},{"value":"nick","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1nick\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1nick\/fragments","op":"replace","value":[{"text":"nick","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1debugDescription\/title","value":"debugDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1debugDescription\/fragments","value":[{"kind":"identifier","text":"debugDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1isTyping\/title","value":"isTyping"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1isTyping\/fragments","op":"replace","value":[{"kind":"identifier","text":"isTyping"}]},{"value":"displayName","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1displayName\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent~1displayName\/fragments","value":[{"text":"displayName","kind":"identifier"}],"op":"replace"},{"value":"ZDKAgent","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/fragments","value":[{"text":"ZDKAgent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}