{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration"]},{"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatAPIConfiguration) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatAPIConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Default values","level":2,"anchor":"Default-values","type":"heading"},{"code":["visitorPathOne = nil \/\/ \"Direct Path\"","visitorPathTwo = \"Zendesk Chat SDK v\\(VersionNumber)\"","visitorPathTwoValue = nil","tags = []","department = nil","visitorInfo = nil"],"type":"codeListing","syntax":"swift"}],"kind":"content"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/department","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/departmentId","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/departmentName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/tags","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorInfo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathOne","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwoValue"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/isEqual(_:)"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration"},"abstract":[{"type":"text","text":"A set of configurations that are associated with each chat session."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ChatAPIConfiguration"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAPIConfiguration","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"title":"ChatAPIConfiguration","roleHeading":"Class","symbolKind":"class","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration"},"references":{"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/visitorPathOne":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visitorPathOne"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathOne","type":"topic","title":"visitorPathOne","navigatorTitle":[{"text":"visitorPathOne","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathone","abstract":[{"text":"This string will be placed in the first line of the visitor path.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to “Direct Path” if not specified.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/department":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/department","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/department","navigatorTitle":[{"text":"department","kind":"identifier"}],"title":"department","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"department","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"deprecated":true,"abstract":[{"text":"The department to be set ","type":"text"},{"type":"codeVoice","code":"by name"},{"text":" when a chat starts.","type":"text"},{"text":" ","type":"text"},{"text":"default is ","type":"text"},{"code":"nil","type":"codeVoice"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/visitorPathTwoValue":{"abstract":[{"text":"This string can be found when hovering over the second line of the visitor path.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwoValue","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visitorPathTwoValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"visitorPathTwoValue"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathtwovalue","title":"visitorPathTwoValue","type":"topic","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/departmentName":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/departmentName","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"departmentName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"departmentName"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/departmentname","title":"departmentName","type":"topic","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/isEqual(_:)":{"abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/isequal(_:)","title":"isEqual(_:)","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/isEqual(_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/tags":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tags"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/tags","type":"topic","title":"tags","navigatorTitle":[{"text":"tags","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/tags","abstract":[{"type":"text","text":"The tags to be set when a chat starts."}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/visitorInfo":{"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorinfo","title":"visitorInfo","abstract":[{"text":"Set the visitor info.","type":"text"},{"text":" ","type":"text"},{"text":"Default is ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":". Pass through fields as empty strings to clear info.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorInfo","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visitorInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKVisitorInfo","text":"VisitorInfo","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"visitorInfo"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration","type":"topic","title":"ChatAPIConfiguration","navigatorTitle":[{"text":"ChatAPIConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAPIConfiguration","kind":"identifier"}],"abstract":[{"text":"A set of configurations that are associated with each chat session.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/init()","abstract":[{"type":"text","text":"Default initializer"}],"kind":"symbol","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/init()"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/departmentId":{"abstract":[{"type":"text","text":"The department to be set "},{"type":"codeVoice","code":"by Id"},{"text":" when a chat starts.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"default is "},{"code":"nil","type":"codeVoice"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/departmentId","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"departmentId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"departmentId"}],"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/departmentid","title":"departmentId","type":"topic","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/visitorPathTwo":{"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/visitorpathtwo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visitorPathTwo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"visitorPathTwo"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwo","role":"symbol","abstract":[{"type":"text","text":"This string will be placed in the second line of the visitor path."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to “Zendesk Chat SDK v(ChatProvidersSDKVersionNumber)”"}],"title":"visitorPathTwo"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"ZDKChatAPIConfiguration","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"ZDKChatAPIConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"ZDKChatAPIConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/department","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/departmentId","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/departmentName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/tags","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorInfo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathOne","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/visitorPathTwoValue"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/init()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/isEqual(_:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKChatAPIConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"visitorPathOne","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathOne\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathOne\/fragments","op":"replace","value":[{"text":"visitorPathOne","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1department\/title","value":"department","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1department\/fragments","op":"replace","value":[{"text":"department","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathTwoValue\/title","value":"visitorPathTwoValue"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathTwoValue\/fragments","value":[{"kind":"identifier","text":"visitorPathTwoValue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1departmentName\/title","value":"departmentName"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1departmentName\/fragments","value":[{"kind":"identifier","text":"departmentName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1tags\/title","op":"replace","value":"tags"},{"value":[{"kind":"identifier","text":"tags"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1tags\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorInfo\/title","value":"visitorInfo"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorInfo\/fragments","op":"replace","value":[{"text":"visitorInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/title","value":"ZDKChatAPIConfiguration"},{"value":[{"text":"ZDKChatAPIConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1init()\/title","value":"init","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1init()\/fragments"},{"op":"replace","value":"departmentId","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1departmentId\/title"},{"value":[{"text":"departmentId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1departmentId\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathTwo\/title","op":"replace","value":"visitorPathTwo"},{"value":[{"kind":"identifier","text":"visitorPathTwo"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1visitorPathTwo\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}