{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKChatLog) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}],"languages":["swift"]}]},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Different LogTypes","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"code":"ChatMessage","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"ChatAttachment"},{"type":"text","text":",  "},{"type":"codeVoice","code":"ChatMemberJoin"},{"type":"text","text":", "},{"code":"ChatMemberLeave","type":"codeVoice"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatlog"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlog"]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/createdByVisitor","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/createdTimestamp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/deliveryStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/displayName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/id","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/lastModifiedTimestamp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/nick","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/participant","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/status","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/type"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/isEqual(_:)"],"title":"Instance Methods"}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol","doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"title":"ChatLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatLog"}],"symbolKind":"class","role":"symbol","roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Base class for chat log events that may occur in a chat session"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/deliveryStatus":{"url":"\/documentation\/chatproviderssdk\/chatlog\/deliverystatus","kind":"symbol","role":"symbol","abstract":[],"title":"deliveryStatus","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deliveryStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKDeliveryStatus","text":"ZDKDeliveryStatus","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/deliveryStatus","navigatorTitle":[{"text":"deliveryStatus","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/description":{"kind":"symbol","abstract":[{"type":"text","text":"A textual representation of this instance."}],"title":"description","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/chatproviderssdk\/chatlog\/description"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/participant":{"navigatorTitle":[{"text":"participant","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatlog\/participant","title":"participant","abstract":[{"text":"Who sent the message can be user\/agent\/trigger","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"participant"},{"text":": ","kind":"text"},{"text":"ChatParticipant","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatParticipant","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/participant","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatComment":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatComment","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","type":"topic","url":"\/documentation\/chatproviderssdk\/chatcomment","navigatorTitle":[{"kind":"identifier","text":"ChatComment"}],"abstract":[{"type":"text","text":"Chat comment in relation to a Chat rating."}],"title":"ChatComment"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/id":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/id","abstract":[{"text":"ID","type":"text"}],"role":"symbol","title":"id","type":"topic","navigatorTitle":[{"text":"id","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatlog\/id"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","kind":"symbol","navigatorTitle":[{"text":"ChatAttachmentMessage","kind":"identifier"}],"abstract":[{"text":"The Chat Log attachment","type":"text"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatattachmentmessage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAttachmentMessage"}],"title":"ChatAttachmentMessage"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/nick":{"title":"nick","abstract":[{"text":"Identifier associated with the sender. Used to distinguish ","type":"text"},{"type":"codeVoice","code":"sender"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/nick","role":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatlog\/nick","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"nick"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nick"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"type":"topic","abstract":[{"text":"Base class for chat log events that may occur in a chat session","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatlog","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"title":"ChatLog","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/displayName":{"abstract":[{"text":"Display Name","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"displayName"}],"url":"\/documentation\/chatproviderssdk\/chatlog\/displayname","title":"displayName","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/displayName"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatRating":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatRating","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","type":"topic","url":"\/documentation\/chatproviderssdk\/chatrating","navigatorTitle":[{"text":"ChatRating","kind":"identifier"}],"abstract":[{"type":"text","text":"A Chat rating left by the user after an agent requested it. Can be "},{"type":"codeVoice","code":"none"},{"text":", ","type":"text"},{"code":"good","type":"codeVoice"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"bad"}],"title":"ChatRating"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/type":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatlog\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/type","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatLogType","text":"ChatLogType","kind":"typeIdentifier"}],"abstract":[{"text":"The type of event the log is","type":"text"}],"title":"type","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMessage":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","type":"topic","url":"\/documentation\/chatproviderssdk\/chatmessage","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"abstract":[{"type":"text","text":"Chat message"}],"title":"ChatMessage"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/createdTimestamp":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/createdTimestamp","title":"createdTimestamp","type":"topic","url":"\/documentation\/chatproviderssdk\/chatlog\/createdtimestamp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createdTimestamp","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"}],"navigatorTitle":[{"text":"createdTimestamp","kind":"identifier"}],"abstract":[{"type":"text","text":"Timestamp of when the message was sent"}],"kind":"symbol","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/status":{"url":"\/documentation\/chatproviderssdk\/chatlog\/status","kind":"symbol","role":"symbol","abstract":[{"text":"Log is marked as failed when it’s delivery failed","type":"text"}],"title":"status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"s:16ChatProvidersSDK14DeliveryStatusO","text":"DeliveryStatus","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/status","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/createdByVisitor":{"navigatorTitle":[{"kind":"identifier","text":"createdByVisitor"}],"url":"\/documentation\/chatproviderssdk\/chatlog\/createdbyvisitor","title":"createdByVisitor","abstract":[{"type":"text","text":"If the log was created by visitor"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createdByVisitor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/createdByVisitor","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatRatingRequest":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatRatingRequest","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest","type":"topic","url":"\/documentation\/chatproviderssdk\/chatratingrequest","navigatorTitle":[{"text":"ChatRatingRequest","kind":"identifier"}],"abstract":[{"text":"Chat Rating Request (sent by the agent)","type":"text"}],"title":"ChatRatingRequest"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMemberJoin":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMemberJoin","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","type":"topic","url":"\/documentation\/chatproviderssdk\/chatmemberjoin","navigatorTitle":[{"kind":"identifier","text":"ChatMemberJoin"}],"abstract":[{"text":"Chat Member Join event","type":"text"}],"title":"ChatMemberJoin"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatLogProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol","type":"topic","title":"ChatLogProtocol","navigatorTitle":[{"kind":"identifier","text":"ChatLogProtocol"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatlogprotocol","abstract":[{"type":"text","text":"Base protocol representation of a "},{"type":"codeVoice","code":"ChatLog"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/lastModifiedTimestamp":{"type":"topic","abstract":[{"text":"Timestamp of when the message was modified","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatlog\/lastmodifiedtimestamp","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/lastModifiedTimestamp","navigatorTitle":[{"text":"lastModifiedTimestamp","kind":"identifier"}],"title":"lastModifiedTimestamp","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"lastModifiedTimestamp","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatMemberLeave":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatMemberLeave","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","type":"topic","url":"\/documentation\/chatproviderssdk\/chatmemberleave","navigatorTitle":[{"text":"ChatMemberLeave","kind":"identifier"}],"title":"ChatMemberLeave","abstract":[{"text":"Chat Member Leave event","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/isEqual(_:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Returns a Boolean value that indicates whether the receiver and a given object are equal."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatlog\/isequal(_:)","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatOptionsMessage":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatOptionsMessage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","type":"topic","url":"\/documentation\/chatproviderssdk\/chatoptionsmessage","navigatorTitle":[{"text":"ChatOptionsMessage","kind":"identifier"}],"abstract":[{"text":"Questions from agent with multiple options that a user can respond with","type":"text"}],"title":"ChatOptionsMessage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatLog"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKChatLog","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatLog"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/createdByVisitor","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/createdTimestamp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/deliveryStatus","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/displayName","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/id","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/lastModifiedTimestamp","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/nick","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/participant","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/type"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/isEqual(_:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Inherited By","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatComment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberJoin","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMemberLeave","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatOptionsMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatRatingRequest"],"type":"inheritedBy","kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKChatLog"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1deliveryStatus\/title","value":"deliveryStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1deliveryStatus\/fragments","value":[{"kind":"identifier","text":"deliveryStatus"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1description\/title","op":"replace","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1description\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1participant\/title","value":"participant","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1participant\/fragments","op":"replace","value":[{"text":"participant","kind":"identifier"}]},{"op":"replace","value":"ZDKChatComment","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatComment\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatComment\/fragments","value":[{"text":"ZDKChatComment","kind":"identifier"}],"op":"replace"},{"value":"id","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1id\/title"},{"op":"replace","value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1id\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/title","op":"replace","value":"ZDKChatAttachmentMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/fragments","op":"replace","value":[{"text":"ZDKChatAttachmentMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1nick\/title","value":"nick","op":"replace"},{"value":[{"text":"nick","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1nick\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title","value":"ZDKChatLog","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","value":[{"text":"ZDKChatLog","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1displayName\/title","value":"displayName","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1displayName\/fragments","op":"replace","value":[{"text":"displayName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRating\/title","op":"replace","value":"ZDKChatRating"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRating\/fragments","value":[{"kind":"identifier","text":"ZDKChatRating"}],"op":"replace"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1type\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"value":"ZDKChatMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/title"},{"value":[{"text":"ZDKChatMessage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMessage\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1createdTimestamp\/title","value":"createdTimestamp","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1createdTimestamp\/fragments","value":[{"text":"createdTimestamp","kind":"identifier"}],"op":"replace"},{"value":"createdByVisitor","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1createdByVisitor\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1createdByVisitor\/fragments","op":"replace","value":[{"text":"createdByVisitor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRatingRequest\/title","value":"ZDKRatingRequest"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatRatingRequest\/fragments","op":"replace","value":[{"text":"ZDKRatingRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberJoin\/title","value":"ZDKChatMemberJoin"},{"value":[{"kind":"identifier","text":"ZDKChatMemberJoin"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberJoin\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1lastModifiedTimestamp\/title","value":"lastModifiedTimestamp","op":"replace"},{"value":[{"kind":"identifier","text":"lastModifiedTimestamp"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1lastModifiedTimestamp\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberLeave\/title","value":"ZDKChatMemberLeave","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatMemberLeave\/fragments","op":"replace","value":[{"text":"ZDKChatMemberLeave","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1isEqual(_:)\/fragments","op":"replace"},{"value":"ZDKChatOptionsMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatOptionsMessage\/title"},{"value":[{"kind":"identifier","text":"ZDKChatOptionsMessage"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatOptionsMessage\/fragments"}]}]}