{"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatSettings","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","role":"symbol","navigatorTitle":[{"text":"ChatSettings","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"title":"ChatSettings"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/Se","doc:\/\/com.zendesk.ChatProvidersSDK\/SE","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/init(from:)"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/fileSizeLimit","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isFileSendingEnabled","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/supportedFileTypes"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isEqual(_:)"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/initial"],"title":"Type Properties"}],"sections":[],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatSettings"},{"text":" model stores information about the chat account’s settings,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"such as the "},{"code":"fileSizeLimit","type":"codeVoice"},{"type":"text","text":", whether attachments are enabled, and the list of accepted file extensions."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKChatSettings) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatSettings","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatsettings"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatsettings"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isEqual(_:)","url":"\/documentation\/chatproviderssdk\/chatsettings\/isequal(_:)","title":"isEqual(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)":{"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fileSizeLimit"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isFileSendingEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"supportedFileTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings\/init(filesizelimit:isfilesendingenabled:supportedfiletypes:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)","title":"init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/init(from:)","type":"topic","title":"init(from:)","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings\/init(from:)","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/fileSizeLimit":{"abstract":[{"type":"text","text":"File size limit is 20 MB"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"fileSizeLimit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileSizeLimit"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings\/filesizelimit","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/fileSizeLimit","title":"fileSizeLimit"},"doc://com.zendesk.ChatProvidersSDK/Se":{"title":"Swift.Decodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/Se"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SE"},"doc://com.zendesk.ChatProvidersSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatSettings","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","type":"topic","title":"ChatSettings","navigatorTitle":[{"kind":"identifier","text":"ChatSettings"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings","abstract":[{"text":"The ","type":"text"},{"code":"ZDKChatSettings","type":"codeVoice"},{"type":"text","text":" model stores information about the chat account’s settings,"},{"type":"text","text":" "},{"text":"such as the ","type":"text"},{"code":"fileSizeLimit","type":"codeVoice"},{"type":"text","text":", whether attachments are enabled, and the list of accepted file extensions."}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/initial":{"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initial","kind":"identifier"},{"kind":"text","text":": "},{"text":"ChatSettings","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initial"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings\/initial","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/initial","title":"initial"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/debugDescription":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings\/debugdescription","title":"debugDescription","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/debugDescription"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/description":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings\/description","title":"description","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/description"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/supportedFileTypes":{"abstract":[{"type":"text","text":"Lists array of supported file types - png, jpg, jpeg"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"supportedFileTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"type":"topic","navigatorTitle":[{"text":"supportedFileTypes","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/chatproviderssdk\/chatsettings\/supportedfiletypes","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/supportedFileTypes","title":"supportedFileTypes"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings/isFileSendingEnabled":{"abstract":[{"type":"text","text":"if true, sending the attachments is available"}],"title":"isFileSendingEnabled","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFileSendingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isFileSendingEnabled","url":"\/documentation\/chatproviderssdk\/chatsettings\/isfilesendingenabled","navigatorTitle":[{"kind":"identifier","text":"isFileSendingEnabled"}]},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ZDKChatSettings","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatSettings"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ZDKChatSettings"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/debugDescription","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/fileSizeLimit","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isFileSendingEnabled","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/supportedFileTypes"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/isEqual(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings\/initial"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKChatSettings"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1isEqual(_:)\/fragments"},{"op":"replace","value":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFileSizeLimit:isFileSendingEnabled:supportedFileTypes:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1init(fileSizeLimit:isFileSendingEnabled:supportedFileTypes:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1fileSizeLimit\/title","value":"fileSizeLimit"},{"op":"replace","value":[{"kind":"identifier","text":"fileSizeLimit"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1fileSizeLimit\/fragments"},{"value":"ZDKChatSettings","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments","value":[{"text":"ZDKChatSettings","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1initial\/title","value":"initial","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1initial\/fragments","value":[{"kind":"identifier","text":"initial"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1debugDescription\/title","value":"debugDescription"},{"value":[{"text":"debugDescription","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1debugDescription\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1description\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1description\/fragments"},{"op":"replace","value":"supportedFileTypes","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1supportedFileTypes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1supportedFileTypes\/fragments","value":[{"kind":"identifier","text":"supportedFileTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1isFileSendingEnabled\/title","value":"isFileSendingEnabled"},{"value":[{"kind":"identifier","text":"isFileSendingEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings~1isFileSendingEnabled\/fragments"}]}]}