{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol","doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The Chat Log attachment"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/attachment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/message","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/url"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/isEqual(_:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatAttachmentMessage) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatAttachmentMessage","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"metadata":{"roleHeading":"Class","title":"ChatAttachmentMessage","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAttachmentMessage"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachmentMessage","navigatorTitle":[{"text":"ChatAttachmentMessage","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatattachmentmessage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatattachmentmessage"]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage/message":{"kind":"symbol","abstract":[],"title":"message","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","navigatorTitle":[{"text":"message","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatattachmentmessage\/message","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/message"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"type":"topic","abstract":[{"text":"Base class for chat log events that may occur in a chat session","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatlog","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"title":"ChatLog","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage/attachment":{"kind":"symbol","abstract":[{"type":"text","text":"Underlying attachment model"}],"title":"attachment","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"attachment","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatAttachment","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachment"}],"role":"symbol","navigatorTitle":[{"text":"attachment","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatattachmentmessage\/attachment","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/attachment"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage/url":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/url","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"url"}],"abstract":[{"type":"text","text":"Returns the "},{"type":"codeVoice","code":"URL"},{"type":"text","text":" associated with the attachment. Preferring remote over local. Nil if neither exist."}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatattachmentmessage\/url","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"title":"url"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage/isEqual(_:)":{"type":"topic","url":"\/documentation\/chatproviderssdk\/chatattachmentmessage\/isequal(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether the receiver and a given object are equal.","type":"text"}],"kind":"symbol","title":"isEqual(_:)","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatLogProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogProtocol","type":"topic","title":"ChatLogProtocol","navigatorTitle":[{"kind":"identifier","text":"ChatLogProtocol"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatlogprotocol","abstract":[{"type":"text","text":"Base protocol representation of a "},{"type":"codeVoice","code":"ChatLog"}],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAttachmentMessage":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage","kind":"symbol","navigatorTitle":[{"text":"ChatAttachmentMessage","kind":"identifier"}],"abstract":[{"text":"The Chat Log attachment","type":"text"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatattachmentmessage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAttachmentMessage"}],"title":"ChatAttachmentMessage"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKChatAttachmentMessage","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKChatAttachmentMessage","kind":"identifier"}]},{"value":[{"text":"ZDKChatAttachmentMessage","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/attachment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/message","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/url"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAttachmentMessage\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ZDKChatAttachmentMessage","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","kind":"typeIdentifier","text":"ZDKChatLog"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1message\/title","value":"message","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1message\/fragments","value":[{"kind":"identifier","text":"message"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title","value":"ZDKChatLog","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","value":[{"text":"ZDKChatLog","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1attachment\/title","op":"replace","value":"attachment"},{"value":[{"kind":"identifier","text":"attachment"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1attachment\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1url\/title","value":"url","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1url\/fragments","op":"replace","value":[{"text":"url","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage~1isEqual(_:)\/fragments"},{"value":"ZDKChatAttachmentMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAttachmentMessage\/fragments","value":[{"text":"ZDKChatAttachmentMessage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}