{"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connected","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connecting","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/disconnected","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/failed","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/reconnecting","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/unreachable"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/description","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/isConnected"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"metadata":{"navigatorTitle":[{"text":"ConnectionStatus","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionStatus"}],"roleHeading":"Enumeration","modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKConnectionStatus","symbolKind":"enum","title":"ConnectionStatus"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKConnectionStatus) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionStatus"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/connectionstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/connectionstatus"]}],"abstract":[{"type":"text","text":"Represents different states of the"},{"type":"codeVoice","code":"ChatSession"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/isConnected":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isConnected","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/isConnected","title":"isConnected","role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionstatus\/isconnected"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/RawRepresentable-Implementations":{"type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/chatproviderssdk\/connectionstatus\/rawrepresentable-implementations"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/connectionstatus\/init(rawvalue:)","role":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/init(rawValue:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/connecting":{"type":"topic","abstract":[{"type":"text","text":"Indicating the client is trying to connect to the backend."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connecting"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connecting","title":"ConnectionStatus.connecting","role":"symbol","navigatorTitle":[{"text":"ZDKConnectionStatusConnecting","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/connecting"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConnectionStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionStatus"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionstatus","abstract":[{"type":"text","text":"Represents different states of the"},{"type":"codeVoice","code":"ChatSession"}],"title":"ConnectionStatus","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/connected":{"type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"ChatSession","type":"codeVoice"},{"type":"text","text":" has connected to the backend and is ready to send\/receive messages."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connected"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connected","title":"ConnectionStatus.connected","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/connected"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/reconnecting":{"type":"topic","abstract":[{"type":"text","text":"The "},{"code":"ChatSession","type":"codeVoice"},{"type":"text","text":" is trying to reconnect to a chat that was already in session."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reconnecting"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/reconnecting","title":"ConnectionStatus.reconnecting","role":"symbol","navigatorTitle":[{"text":"ZDKConnectionStatusReconnecting","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/reconnecting"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/failed":{"type":"topic","abstract":[{"text":"Failed to reconnect to the web-socket","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/failed","title":"ConnectionStatus.failed","role":"symbol","navigatorTitle":[{"text":"ZDKConnectionStatusFailed","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/failed"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/Equatable-Implementations":{"type":"topic","abstract":[],"kind":"article","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/chatproviderssdk\/connectionstatus\/equatable-implementations"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/connectionstatus\/description","abstract":[],"title":"description","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/description"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/disconnected":{"type":"topic","abstract":[{"type":"text","text":"The "},{"code":"ChatSession","type":"codeVoice"},{"type":"text","text":" has disconnected. Can be caused by network connection, or a user ending"},{"text":" ","type":"text"},{"text":"the session with ","type":"text"},{"code":"ChatSession.disconnect()","type":"codeVoice"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disconnected"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/disconnected","title":"ConnectionStatus.disconnected","role":"symbol","navigatorTitle":[{"text":"ZDKConnectionStatusDisconnected","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/disconnected"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ConnectionStatus/unreachable":{"type":"topic","abstract":[{"type":"text","text":"The internet connectivity appears to be offline"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreachable"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/unreachable","title":"ConnectionStatus.unreachable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKConnectionStatusUnreachable"}],"url":"\/documentation\/chatproviderssdk\/connectionstatus\/unreachable"},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"ZDKConnectionStatus","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connected","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/connecting","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/disconnected","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/failed","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/reconnecting","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ConnectionStatus\/unreachable"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKConnectionStatus"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1connecting\/title","value":"ZDKConnectionStatusConnecting"},{"value":[{"kind":"identifier","text":"ZDKConnectionStatusConnecting"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1connecting\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/title","value":"ZDKConnectionStatus","op":"replace"},{"value":[{"text":"ZDKConnectionStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1connected\/title","value":"ZDKConnectionStatusConnected","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKConnectionStatusConnected"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1connected\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1reconnecting\/title","value":"ZDKConnectionStatusReconnecting","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1reconnecting\/fragments","value":[{"text":"ZDKConnectionStatusReconnecting","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1failed\/title","value":"ZDKConnectionStatusFailed"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1failed\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKConnectionStatusFailed"}]},{"value":"ZDKConnectionStatusDisconnected","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1disconnected\/title"},{"value":[{"text":"ZDKConnectionStatusDisconnected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1disconnected\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1unreachable\/title","op":"replace","value":"ZDKConnectionStatusUnreachable"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ConnectionStatus~1unreachable\/fragments","value":[{"text":"ZDKConnectionStatusUnreachable","kind":"identifier"}]}]}]}