{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/chatproviderssdk\/loggable"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable\/log-4blb5"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable\/log-3pgya"],"title":"Type Properties"}],"relationshipsSections":[{"type":"conformingTypes","title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Loggable","kind":"identifier"},{"text":" : AnyObject","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Protocol that conforms"}],"metadata":{"roleHeading":"Protocol","externalID":"s:16ChatProvidersSDK8LoggableP","modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","navigatorTitle":[{"text":"Loggable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Loggable","kind":"identifier"}],"symbolKind":"protocol","title":"Loggable"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Loggable/log-3pgya":{"url":"\/documentation\/chatproviderssdk\/loggable\/log-3pgya","title":"log","required":true,"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Log","preciseIdentifier":"s:16ChatProvidersSDK3LogP"}],"type":"topic","defaultImplementations":2,"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable\/log-3pgya","abstract":[],"kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Loggable/log-4blb5":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable\/log-4blb5","kind":"symbol","required":true,"abstract":[],"type":"topic","title":"log","url":"\/documentation\/chatproviderssdk\/loggable\/log-4blb5","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"log"},{"kind":"text","text":": "},{"text":"Log","preciseIdentifier":"s:16ChatProvidersSDK3LogP","kind":"typeIdentifier"}],"defaultImplementations":2},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Chat","kind":"identifier"}],"navigatorTitle":[{"text":"Chat","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"Chat"},{"type":"text","text":" is a singleton class of the "},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/chatproviderssdk\/chat","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","role":"symbol","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"url":"\/documentation\/chatproviderssdk\/chatprovider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}],"title":"ChatProvider","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatProvider","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationsProvider":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationsProvider","kind":"symbol","url":"\/documentation\/chatproviderssdk\/pushnotificationsprovider","navigatorTitle":[{"text":"PushNotificationsProvider","kind":"identifier"}],"title":"PushNotificationsProvider","abstract":[{"text":"The ","type":"text"},{"code":"ZDKPushNoticiationProvider","type":"codeVoice"},{"type":"text","text":" provides APIs to subscribe to, and handle Zendesk Chat’s Push Notifications."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PushNotificationsProvider","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Loggable":{"type":"topic","title":"Loggable","url":"\/documentation\/chatproviderssdk\/loggable","role":"symbol","abstract":[{"type":"text","text":"Protocol that conforms"}],"navigatorTitle":[{"text":"Loggable","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Loggable","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title","value":"ZDKChat","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","op":"replace","value":[{"text":"ZDKChat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","value":"ZDKChatProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/title","op":"replace","value":"ZDKPushNotificationsProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationsProvider\/fragments","value":[{"kind":"identifier","text":"ZDKPushNotificationsProvider"}]}]}]}