{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus\/ended"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatsessionstatus\/ended"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus"]]},"abstract":[{"type":"text","text":"Chat session has ended"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ChatSessionStatusEnded"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ended","kind":"identifier"}],"title":"ChatSessionStatus.ended","externalID":"c:@M@ChatProvidersSDK@E@ChatSessionStatus@ChatSessionStatusEnded"},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ended","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"ended","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus/ended":{"title":"ChatSessionStatus.ended","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ended"}],"navigatorTitle":[{"text":"ChatSessionStatusEnded","kind":"identifier"}],"abstract":[{"type":"text","text":"Chat session has ended"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus\/ended","type":"topic","kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatsessionstatus\/ended"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSessionStatus":{"title":"ChatSessionStatus","role":"symbol","abstract":[{"type":"text","text":"Chat session status describes current state of the session"}],"url":"\/documentation\/chatproviderssdk\/chatsessionstatus","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSessionStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatSessionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ChatSessionStatus","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"ChatSessionStatusEnded","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ChatSessionStatusEnded","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ChatSessionStatusEnded"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ended\/title","value":"ChatSessionStatusEnded"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus~1ended\/fragments","value":[{"kind":"identifier","text":"ChatSessionStatusEnded"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/title","value":"ChatSessionStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSessionStatus\/fragments","value":[{"text":"ChatSessionStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}