{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData\/PushNotificationType","preciseIdentifier":"s:16ChatProvidersSDK20PushNotificationDataC0dE4TypeO","text":"PushNotificationType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/pushnotificationdata\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/pushnotificationdata\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"type of "},{"type":"codeVoice","code":"PushNotification"},{"type":"text","text":", can be either "},{"type":"codeVoice","code":"chatEnded"},{"type":"text","text":" or "},{"type":"codeVoice","code":"message"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationType","preciseIdentifier":"s:16ChatProvidersSDK20PushNotificationDataC0dE4TypeO"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationData(py)type","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationData/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PushNotificationType","preciseIdentifier":"s:16ChatProvidersSDK20PushNotificationDataC0dE4TypeO"}],"abstract":[{"type":"text","text":"type of "},{"type":"codeVoice","code":"PushNotification"},{"type":"text","text":", can be either "},{"type":"codeVoice","code":"chatEnded"},{"type":"text","text":" or "},{"type":"codeVoice","code":"message"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationdata\/type"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKPushNotificationType":{"role":"symbol","title":"ZDKPushNotificationType","fragments":[{"kind":"identifier","text":"ZDKPushNotificationType"}],"abstract":[{"type":"text","text":"Enum representing the different types of notifications that can be received for Chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKPushNotificationType","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkpushnotificationtype"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationData":{"role":"symbol","title":"PushNotificationData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationData"}],"abstract":[{"type":"codeVoice","code":"PushNotificationData"},{"type":"text","text":" can be used to gather information about Chat related push notifications"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationData"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationdata"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/PushNotificationData/PushNotificationType":{"role":"symbol","title":"PushNotificationData.PushNotificationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotificationType"}],"abstract":[{"type":"text","text":"Enum representing the different types of notifications that can be received for Chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/PushNotificationData\/PushNotificationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PushNotificationType"}],"url":"\/documentation\/chatproviderssdk\/pushnotificationdata\/pushnotificationtype"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKPushNotificationType","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKPushNotificationType","text":"ZDKPushNotificationType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData\/title","value":"ZDKPushNotificationData"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1PushNotificationData\/fragments","value":[{"kind":"identifier","text":"ZDKPushNotificationData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}