{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatlogtype"]}],"kind":"symbol","abstract":[{"text":"An enum of the message types that can be in sent\/received in a chat session","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@ChatProvidersSDK@E@ZDKChatLogType","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"text":"ChatLogType","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatLogType"}],"title":"ChatLogType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKChatLogType) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLogType"}]}]}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/attachmentMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatComment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRatingRequest","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberJoin","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberLeave","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/message","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/optionsMessage"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"sections":[],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/chatRatingRequest":{"kind":"symbol","abstract":[{"type":"text","text":"Agent requested a rating"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeChatRatingRequest"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRatingRequest","title":"ChatLogType.chatRatingRequest","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"chatRatingRequest","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/chatratingrequest"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/memberLeave":{"kind":"symbol","abstract":[{"type":"text","text":"Member left the channel"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeMemberLeave"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberLeave","title":"ChatLogType.memberLeave","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"memberLeave"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/memberleave"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/Equatable-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/chatproviderssdk\/chatlogtype\/equatable-implementations"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/chatComment":{"kind":"symbol","abstract":[{"type":"text","text":"Visitor left a comment about the chat"}],"navigatorTitle":[{"text":"ZDKChatLogTypeChatComment","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatComment","title":"ChatLogType.chatComment","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatComment"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/chatcomment"},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/optionsMessage":{"kind":"symbol","abstract":[{"type":"text","text":"Multiple-choice option message"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeOptionsMessage"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/optionsMessage","title":"ChatLogType.optionsMessage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"optionsMessage","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/optionsmessage"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/init(rawValue:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/init(rawValue:)","title":"init(rawValue:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/init(rawvalue:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/message":{"kind":"symbol","abstract":[{"text":"Chat message","type":"text"}],"navigatorTitle":[{"text":"ZDKChatLogTypeMessage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/message","title":"ChatLogType.message","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/message"},"doc://com.zendesk.ChatProvidersSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/attachmentMessage":{"kind":"symbol","abstract":[{"text":"Chat attachment message","type":"text"}],"navigatorTitle":[{"text":"ZDKChatLogTypeAttachmentMessage","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/attachmentMessage","title":"ChatLogType.attachmentMessage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"attachmentMessage","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/attachmentmessage"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/chatRating":{"kind":"symbol","abstract":[{"text":"Visitor left a rating","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeChatRating"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRating","title":"ChatLogType.chatRating","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"chatRating","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype\/chatrating"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"url":"\/documentation\/chatproviderssdk\/chatlogtype","title":"ChatLogType","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatLogType","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/RawRepresentable-Implementations","type":"topic","kind":"article","url":"\/documentation\/chatproviderssdk\/chatlogtype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType/memberJoin":{"title":"ChatLogType.memberJoin","url":"\/documentation\/chatproviderssdk\/chatlogtype\/memberjoin","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKChatLogTypeMemberJoin"}],"kind":"symbol","abstract":[{"text":"Member joined the channel","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberJoin","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"memberJoin"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"ZDKChatLogType","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKChatLogType","kind":"identifier"}]},{"value":[{"text":"ZDKChatLogType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/attachmentMessage","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatComment","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRating","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/chatRatingRequest","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberJoin","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/memberLeave","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/message","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType\/optionsMessage"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKChatLogType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRatingRequest\/title","value":"ZDKChatLogTypeChatRatingRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRatingRequest\/fragments","value":[{"text":"ZDKChatLogTypeChatRatingRequest","kind":"identifier"}]},{"value":"ZDKChatLogTypeMemberLeave","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberLeave\/title"},{"op":"replace","value":[{"text":"ZDKChatLogTypeMemberLeave","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberLeave\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatComment\/title","value":"ZDKChatLogTypeChatComment"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatComment\/fragments","op":"replace","value":[{"text":"ZDKChatLogTypeChatComment","kind":"identifier"}]},{"value":"ZDKChatLogTypeOptionsMessage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1optionsMessage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1optionsMessage\/fragments","value":[{"text":"ZDKChatLogTypeOptionsMessage","kind":"identifier"}]},{"op":"replace","value":"ZDKChatLogTypeMessage","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1message\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1message\/fragments","value":[{"text":"ZDKChatLogTypeMessage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1attachmentMessage\/title","value":"ZDKChatLogTypeAttachmentMessage"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1attachmentMessage\/fragments","op":"replace","value":[{"text":"ZDKChatLogTypeAttachmentMessage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRating\/title","op":"replace","value":"ZDKChatLogTypeChatRating"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1chatRating\/fragments","value":[{"kind":"identifier","text":"ZDKChatLogTypeChatRating"}],"op":"replace"},{"value":"ZDKChatLogType","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatLogType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberJoin\/title","value":"ZDKChatLogTypeMemberJoin"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType~1memberJoin\/fragments","value":[{"text":"ZDKChatLogTypeMemberJoin","kind":"identifier"}]}]}]}