{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"abstract":[{"type":"text","text":"Who sent the message can be user\/agent\/trigger"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"attribute","text":"@objc"},{"text":"(ZDKChatParticipant) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatParticipant","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatparticipant"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatparticipant"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"ChatParticipant","externalID":"c:@M@ChatProvidersSDK@E@ZDKChatParticipant","role":"symbol","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChatParticipant"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatParticipant","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/agent","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/system","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/trigger","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/visitor"]},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/description"],"title":"Instance Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/s12CaseIterableP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY","doc:\/\/com.zendesk.ChatProvidersSDK\/s8SendableP"],"type":"conformsTo"}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant":{"navigatorTitle":[{"kind":"identifier","text":"ChatParticipant"}],"abstract":[{"type":"text","text":"Who sent the message can be user\/agent\/trigger"}],"title":"ChatParticipant","kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ChatParticipant","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatparticipant"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/description":{"kind":"symbol","title":"description","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chatparticipant\/description"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/agent":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"agent"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatParticipantAgent"}],"type":"topic","abstract":[{"text":"Message came from an agent","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/agent","url":"\/documentation\/chatproviderssdk\/chatparticipant\/agent","title":"ChatParticipant.agent","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/Equatable-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/Equatable-Implementations","url":"\/documentation\/chatproviderssdk\/chatparticipant\/equatable-implementations","title":"Equatable Implementations","kind":"article"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s8SendableP","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/visitor":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"visitor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatParticipantVisitor"}],"type":"topic","abstract":[{"text":"Message came from the visitor","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/visitor","title":"ChatParticipant.visitor","url":"\/documentation\/chatproviderssdk\/chatparticipant\/visitor","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/init(rawValue:)","url":"\/documentation\/chatproviderssdk\/chatparticipant\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/trigger":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"trigger","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatParticipantTrigger"}],"type":"topic","abstract":[{"text":"Message came from an automated trigger","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/trigger","title":"ChatParticipant.trigger","url":"\/documentation\/chatproviderssdk\/chatparticipant\/trigger","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/system":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"system"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatParticipantSystem"}],"type":"topic","abstract":[{"text":"Message came from chat backend","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/system","title":"ChatParticipant.system","url":"\/documentation\/chatproviderssdk\/chatparticipant\/system","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatParticipant/RawRepresentable-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/chatproviderssdk\/chatparticipant\/rawrepresentable-implementations","kind":"article"},"doc://com.zendesk.ChatProvidersSDK/s12CaseIterableP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s12CaseIterableP","title":"Swift.CaseIterable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatParticipant"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"ZDKChatParticipant","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKChatParticipant","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/agent","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/system","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/trigger","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatParticipant\/visitor"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKChatParticipant","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"ZDKChatParticipant","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKChatParticipant"}]},{"value":"ZDKChatParticipantAgent","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1agent\/title","op":"replace"},{"value":[{"text":"ZDKChatParticipantAgent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1agent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1visitor\/title","value":"ZDKChatParticipantVisitor"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1visitor\/fragments","value":[{"text":"ZDKChatParticipantVisitor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1trigger\/title","op":"replace","value":"ZDKChatParticipantTrigger"},{"value":[{"text":"ZDKChatParticipantTrigger","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1trigger\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1system\/title","op":"replace","value":"ZDKChatParticipantSystem"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatParticipant~1system\/fragments","value":[{"kind":"identifier","text":"ZDKChatParticipantSystem"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}