{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships"}],"abstract":[{"code":"Chat","type":"codeVoice"},{"text":" is a singleton class of the ","type":"text"},{"code":"ChatProviderSDK","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"navigatorTitle":[{"text":"Chat","kind":"identifier"}],"modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat","title":"Chat"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKChat) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It needs to be intialized with an "},{"type":"codeVoice","code":"accountKey"},{"type":"text","text":" before using any of the Chat APIs."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"accountKey"},{"text":" can be retrieved from the Zendesk Chat dashboard.","type":"text"}]},{"syntax":"swift","type":"codeListing","code":["Chat.initialize(accountKey: accountKey)"]}]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountKey","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/appId","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/chatProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/providers","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/pushNotificationsProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/clearCache()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/setIdentity(authenticator:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationAuthenticationFailed","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationChatEnded","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationMessageReceived","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/chatProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/instance","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/pushNotificationsProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.type.property"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/didReceiveRemoteNotification(_:in:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/initialize(accountKey:appId:queue:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/initialize(accountKey:queue:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/registerPushToken(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/registerPushTokenString(_:)"]},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/Loggable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chat"]},{"paths":["\/documentation\/chatproviderssdk\/chat"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/pushNotificationsProvider-swift.type.property":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushNotificationsProvider"},{"text":": ","kind":"text"},{"text":"PushNotificationsProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"pushNotificationsProvider","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Push Notifications Provider"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/pushNotificationsProvider-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/pushnotificationsprovider-swift.type.property","title":"pushNotificationsProvider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/NotificationAuthenticationFailed":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationAuthenticationFailed"},{"kind":"text","text":": "},{"text":"NSNotification","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName","text":"Name"}],"navigatorTitle":[{"text":"NotificationAuthenticationFailed","kind":"identifier"}],"abstract":[{"type":"text","text":"This notification is called when the user authentication failed."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationAuthenticationFailed","title":"NotificationAuthenticationFailed","url":"\/documentation\/chatproviderssdk\/chat\/notificationauthenticationfailed","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/configuration-swift.property":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatAPIConfiguration","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"type":"topic","abstract":[{"type":"text","text":"Set configuration to start "},{"type":"codeVoice","code":"Chat"},{"type":"text","text":" with pre-configured "},{"code":"department","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"visitorInfo"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"tags"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.property","url":"\/documentation\/chatproviderssdk\/chat\/configuration-swift.property","title":"configuration","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/hasIdentity-swift.type.property":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasIdentity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"hasIdentity","kind":"identifier"}],"abstract":[{"text":"Whether a user is authenticated.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.type.property","title":"hasIdentity","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/resetIdentity(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetIdentity","kind":"identifier"},{"text":"((() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"resetIdentity:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Resets the visitor data to a clean state allowing a new visitor to chat"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity(_:)","url":"\/documentation\/chatproviderssdk\/chat\/resetidentity(_:)","title":"resetIdentity(_:)","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/Loggable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/Loggable-Implementations","url":"\/documentation\/chatproviderssdk\/chat\/loggable-implementations","title":"Loggable Implementations","kind":"article"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/chatProvider-swift.type.property":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider","text":"ChatProvider"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"chatProvider"}],"type":"topic","abstract":[{"text":"Chat Provider","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/chatProvider-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/chatprovider-swift.type.property","title":"chatProvider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/didReceiveRemoteNotification(_:in:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didReceiveRemoteNotification","kind":"identifier"},{"kind":"text","text":"(["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}],"abstract":[{"text":"Pass the received remote notification to ","type":"text"},{"code":"didReceiveRemoteNotification","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the push notification belongs to Zendesk Chat, the push notification will be processed accordingly"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/didReceiveRemoteNotification(_:in:)","url":"\/documentation\/chatproviderssdk\/chat\/didreceiveremotenotification(_:in:)","title":"didReceiveRemoteNotification(_:in:)","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/accountProvider-swift.type.property":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider","text":"AccountProvider"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"accountProvider","kind":"identifier"}],"type":"topic","abstract":[{"text":"Account Provider","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/accountprovider-swift.type.property","title":"accountProvider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat":{"abstract":[{"code":"Chat","type":"codeVoice"},{"text":" is a singleton class of the ","type":"text"},{"type":"codeVoice","code":"ChatProviderSDK"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chat","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Chat"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat","title":"Chat"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/providers":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"providers"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProviders","kind":"typeIdentifier","text":"Providers"}],"navigatorTitle":[{"text":"providers","kind":"identifier"}],"abstract":[{"type":"text","text":"Grouping of Zendesk Chat’s providers"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/providers","title":"providers","url":"\/documentation\/chatproviderssdk\/chat\/providers","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/NotificationMessageReceived":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationMessageReceived","abstract":[{"text":"Called when ","type":"text"},{"type":"codeVoice","code":"Chat"},{"text":" receives push notification with message","type":"text"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationMessageReceived"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@NSNotificationName","text":"Name","kind":"typeIdentifier"}],"url":"\/documentation\/chatproviderssdk\/chat\/notificationmessagereceived","title":"NotificationMessageReceived","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NotificationMessageReceived"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/configuration-swift.type.property":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"text":"ChatAPIConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Set configuration to start ","type":"text"},{"code":"Chat","type":"codeVoice"},{"text":" with pre-configured ","type":"text"},{"type":"codeVoice","code":"department"},{"text":", ","type":"text"},{"code":"visitorInfo","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"tags"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/configuration-swift.type.property","title":"configuration","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/NotificationChatEnded":{"navigatorTitle":[{"kind":"identifier","text":"NotificationChatEnded"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationChatEnded"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"text":".","kind":"text"},{"text":"Name","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSNotificationName"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/notificationchatended","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationChatEnded","abstract":[{"type":"text","text":"This notification is called when "},{"type":"codeVoice","code":"Chat"},{"text":" session did end","type":"text"}],"title":"NotificationChatEnded","type":"topic","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/settingsProvider-swift.property":{"navigatorTitle":[{"text":"settingsProvider","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"settingsProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","text":"SettingsProvider"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/settingsprovider-swift.property","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.property","type":"topic","abstract":[{"text":"Settings Provider","type":"text"}],"title":"settingsProvider","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/profileProvider-swift.property":{"navigatorTitle":[{"text":"profileProvider","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"profileProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider","kind":"typeIdentifier","text":"ProfileProvider"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/profileprovider-swift.property","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.property","abstract":[{"text":"Profile Provider","type":"text"}],"type":"topic","title":"profileProvider","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/resetIdentity()":{"navigatorTitle":[{"text":"resetIdentity","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetIdentity","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/chatproviderssdk\/chat\/resetidentity()","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity()","type":"topic","abstract":[{"text":"Resets the visitor data to a clean state allowing a new visitor to chat","type":"text"}],"title":"resetIdentity()","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/setIdentity(authenticator:)":{"navigatorTitle":[{"text":"setIdentityWithAuthenticator:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setIdentity","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"authenticator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(pl)ZDKJWTAuthenticator","text":"JWTAuthenticator"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/setidentity(authenticator:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/setIdentity(authenticator:)","abstract":[{"type":"text","text":"Set the authenticated user’s identity"}],"type":"topic","title":"setIdentity(authenticator:)","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/accountKey":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountKey","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","role":"symbol","title":"accountKey","url":"\/documentation\/chatproviderssdk\/chat\/accountkey","abstract":[{"text":"Account key","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accountKey"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/initialize(accountKey:queue:)":{"abstract":[{"type":"text","text":"Initializes chat with Chat’s accountkey"}],"navigatorTitle":[{"text":"initializeWithAccountKey:queue:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"queue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"initialize(accountKey:queue:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/initialize(accountKey:queue:)","url":"\/documentation\/chatproviderssdk\/chat\/initialize(accountkey:queue:)","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/clearCache()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"type":"topic","abstract":[{"text":"Clears the cache","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Call this method when leaving the conversation screen"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/clearCache()","url":"\/documentation\/chatproviderssdk\/chat\/clearcache()","title":"clearCache()","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/pushNotificationsProvider-swift.property":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pushNotificationsProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKPushNotificationsProvider","text":"PushNotificationsProvider"}],"navigatorTitle":[{"text":"pushNotificationsProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"Push Notifications Provider"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/pushNotificationsProvider-swift.property","url":"\/documentation\/chatproviderssdk\/chat\/pushnotificationsprovider-swift.property","title":"pushNotificationsProvider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/connectionProvider-swift.property":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"connectionProvider","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConnectionProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider"}],"navigatorTitle":[{"kind":"identifier","text":"connectionProvider"}],"type":"topic","abstract":[{"type":"text","text":"Connection Provider"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.property","url":"\/documentation\/chatproviderssdk\/chat\/connectionprovider-swift.property","title":"connectionProvider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Loggable":{"navigatorTitle":[{"kind":"identifier","text":"Loggable"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"Loggable","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","url":"\/documentation\/chatproviderssdk\/loggable","type":"topic","title":"Loggable","abstract":[{"type":"text","text":"Protocol that conforms"}],"role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/chatProvider-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatProvider"},{"text":": ","kind":"text"},{"text":"ChatProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider"}],"navigatorTitle":[{"kind":"identifier","text":"chatProvider"}],"type":"topic","abstract":[{"text":"Chat Provider","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/chatProvider-swift.property","url":"\/documentation\/chatproviderssdk\/chat\/chatprovider-swift.property","title":"chatProvider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/appId":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"appId","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"App id"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/appId","url":"\/documentation\/chatproviderssdk\/chat\/appid","title":"appId","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/registerPushTokenString(_:)":{"abstract":[{"text":"Sends push token to server","type":"text"}],"navigatorTitle":[{"text":"registerPushTokenString:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerPushTokenString","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"registerPushTokenString(_:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/registerPushTokenString(_:)","url":"\/documentation\/chatproviderssdk\/chat\/registerpushtokenstring(_:)","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/instance":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instance"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChat","text":"Chat","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"instance"}],"type":"topic","abstract":[{"type":"text","text":"Static instance of the Chat provider"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/instance","url":"\/documentation\/chatproviderssdk\/chat\/instance","title":"instance","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/initialize(accountKey:appId:queue:)":{"navigatorTitle":[{"text":"initializeWithAccountKey:appId:queue:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accountKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"appId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/initialize(accountkey:appid:queue:)","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/initialize(accountKey:appId:queue:)","type":"topic","abstract":[{"text":"Initializes chat with Chat’s accountkey","type":"text"}],"title":"initialize(accountKey:appId:queue:)","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/accountProvider-swift.property":{"abstract":[{"text":"Account Provider","type":"text"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/chat\/accountprovider-swift.property","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"accountProvider","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccountProvider","text":"AccountProvider","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.property","title":"accountProvider"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/connectionProvider-swift.type.property":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"connectionProvider","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKConnectionProvider","kind":"typeIdentifier","text":"ConnectionProvider"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"connectionProvider"}],"type":"topic","abstract":[{"text":"Connection Provider","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.type.property","url":"\/documentation\/chatproviderssdk\/chat\/connectionprovider-swift.type.property","title":"connectionProvider","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/registerPushToken(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerPushToken"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"registerPushToken:"}],"type":"topic","abstract":[{"text":"Sends push token to server","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/registerPushToken(_:)","url":"\/documentation\/chatproviderssdk\/chat\/registerpushtoken(_:)","title":"registerPushToken(_:)","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/hasIdentity-swift.property":{"navigatorTitle":[{"text":"hasIdentity","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasIdentity","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/hasidentity-swift.property","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.property","type":"topic","abstract":[{"type":"text","text":"Whether a user is authenticated."}],"title":"hasIdentity","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/settingsProvider-swift.type.property":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Settings Provider","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chat\/settingsprovider-swift.type.property","title":"settingsProvider","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"settingsProvider","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKSettingsProvider","text":"SettingsProvider","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"settingsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.type.property"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Chat/profileProvider-swift.type.property":{"navigatorTitle":[{"kind":"identifier","text":"profileProvider"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"profileProvider","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKProfileProvider","text":"ProfileProvider"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/chat\/profileprovider-swift.type.property","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.type.property","type":"topic","abstract":[{"type":"text","text":"Profile Provider"}],"title":"profileProvider","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKChat","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}],"op":"replace"},{"op":"replace","value":[{"text":"ZDKChat","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountKey","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/appId","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/chatProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/providers","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/pushNotificationsProvider-swift.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/clearCache()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/resetIdentity(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/setIdentity(authenticator:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationAuthenticationFailed","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationChatEnded","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/NotificationMessageReceived","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/accountProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/chatProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/configuration-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/connectionProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/hasIdentity-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/instance","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/profileProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/pushNotificationsProvider-swift.type.property","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/settingsProvider-swift.type.property"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/didReceiveRemoteNotification(_:in:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/initialize(accountKey:appId:queue:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/initialize(accountKey:queue:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/registerPushToken(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Chat\/registerPushTokenString(_:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKChat","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"pushNotificationsProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1pushNotificationsProvider-swift.type.property\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1pushNotificationsProvider-swift.type.property\/fragments","value":[{"kind":"identifier","text":"pushNotificationsProvider"}],"op":"replace"},{"value":"NotificationAuthenticationFailed","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationAuthenticationFailed\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationAuthenticationFailed\/fragments","value":[{"text":"NotificationAuthenticationFailed","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.property\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.property\/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.type.property\/title","value":"hasIdentity","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.type.property\/fragments","value":[{"text":"hasIdentity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity(_:)\/title","value":"resetIdentity:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetIdentity:"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1chatProvider-swift.type.property\/title","op":"replace","value":"chatProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1chatProvider-swift.type.property\/fragments","value":[{"text":"chatProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1didReceiveRemoteNotification(_:in:)\/title","op":"replace","value":"didReceiveRemoteNotification:in:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1didReceiveRemoteNotification(_:in:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"didReceiveRemoteNotification:in:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountProvider-swift.type.property\/title","value":"accountProvider","op":"replace"},{"value":[{"text":"accountProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountProvider-swift.type.property\/fragments","op":"replace"},{"op":"replace","value":"ZDKChat","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat\/fragments","value":[{"kind":"identifier","text":"ZDKChat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1providers\/title","value":"providers"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1providers\/fragments","value":[{"text":"providers","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationMessageReceived\/title","value":"NotificationMessageReceived","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationMessageReceived\/fragments","op":"replace","value":[{"text":"NotificationMessageReceived","kind":"identifier"}]},{"value":"configuration","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.type.property\/title","op":"replace"},{"value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1configuration-swift.type.property\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationChatEnded\/title","value":"NotificationChatEnded"},{"op":"replace","value":[{"kind":"identifier","text":"NotificationChatEnded"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1NotificationChatEnded\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1settingsProvider-swift.property\/title","op":"replace","value":"settingsProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1settingsProvider-swift.property\/fragments","value":[{"text":"settingsProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1profileProvider-swift.property\/title","value":"profileProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1profileProvider-swift.property\/fragments","value":[{"kind":"identifier","text":"profileProvider"}],"op":"replace"},{"value":"resetIdentity","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1resetIdentity()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetIdentity"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1setIdentity(authenticator:)\/title","op":"replace","value":"setIdentityWithAuthenticator:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1setIdentity(authenticator:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"setIdentityWithAuthenticator:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountKey\/title","value":"accountKey","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountKey\/fragments","value":[{"text":"accountKey","kind":"identifier"}],"op":"replace"},{"value":"initializeWithAccountKey:queue:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1initialize(accountKey:queue:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithAccountKey:queue:"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1initialize(accountKey:queue:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1clearCache()\/title","value":"clearCache"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1clearCache()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearCache"}]},{"value":"pushNotificationsProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1pushNotificationsProvider-swift.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1pushNotificationsProvider-swift.property\/fragments","value":[{"kind":"identifier","text":"pushNotificationsProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1connectionProvider-swift.property\/title","value":"connectionProvider"},{"value":[{"text":"connectionProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1connectionProvider-swift.property\/fragments","op":"replace"},{"op":"replace","value":"chatProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1chatProvider-swift.property\/title"},{"value":[{"text":"chatProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1chatProvider-swift.property\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1appId\/title","value":"appId"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1appId\/fragments","op":"replace","value":[{"text":"appId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1registerPushTokenString(_:)\/title","op":"replace","value":"registerPushTokenString:"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1registerPushTokenString(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"registerPushTokenString:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1instance\/title","value":"instance","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1instance\/fragments","value":[{"text":"instance","kind":"identifier"}]},{"op":"replace","value":"initializeWithAccountKey:appId:queue:","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1initialize(accountKey:appId:queue:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeWithAccountKey:appId:queue:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1initialize(accountKey:appId:queue:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountProvider-swift.property\/title","value":"accountProvider"},{"op":"replace","value":[{"text":"accountProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1accountProvider-swift.property\/fragments"},{"value":"connectionProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1connectionProvider-swift.type.property\/title"},{"op":"replace","value":[{"kind":"identifier","text":"connectionProvider"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1connectionProvider-swift.type.property\/fragments"},{"value":"registerPushToken:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1registerPushToken(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"registerPushToken:"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1registerPushToken(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.property\/title","op":"replace","value":"hasIdentity"},{"value":[{"kind":"identifier","text":"hasIdentity"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1hasIdentity-swift.property\/fragments","op":"replace"},{"value":"settingsProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1settingsProvider-swift.type.property\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1settingsProvider-swift.type.property\/fragments","value":[{"text":"settingsProvider","kind":"identifier"}]},{"value":"profileProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1profileProvider-swift.type.property\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"profileProvider"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Chat~1profileProvider-swift.type.property\/fragments"}]}]}