{"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"symbolKind":"enum","externalID":"c:@M@ChatProvidersSDK@E@ZDKRating","roleHeading":"Enumeration","title":"ZDKRating","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKRating"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKRating"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ZDKRating","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/zdkrating"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/zdkrating"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","interfaceLanguage":"swift"},"abstract":[{"text":"A rating that can be assigned to the chat","type":"text"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/bad","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/good","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/none"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/description"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/Equatable-Implementations","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH","doc:\/\/com.zendesk.ChatProvidersSDK\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating\/equatable-implementations","abstract":[],"role":"collectionGroup"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating\/init(rawvalue:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.zendesk.ChatProvidersSDK/SH":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating\/rawrepresentable-implementations","kind":"article","role":"collectionGroup"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/description":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/chatproviderssdk\/zdkrating\/description","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/description","abstract":[{"type":"text","text":"String representation of the rating"}],"type":"topic","title":"description","role":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/good":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"good"}],"title":"ZDKRating.good","url":"\/documentation\/chatproviderssdk\/zdkrating\/good","navigatorTitle":[{"text":"ZDKRatingGood","kind":"identifier"}],"type":"topic","abstract":[{"text":"good","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/good","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/SY":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","title":"ZDKRating","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ZDKRating","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKRating","kind":"identifier"}],"type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating","abstract":[{"type":"text","text":"A rating that can be assigned to the chat"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/none":{"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/none","title":"ZDKRating.none","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating\/none","abstract":[{"text":"No rating assigned yet","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"text":"ZDKRatingNone","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating/bad":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/bad","abstract":[{"text":"bad","type":"text"}],"title":"ZDKRating.bad","type":"topic","url":"\/documentation\/chatproviderssdk\/zdkrating\/bad","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bad","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKRatingBad"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKRating","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"ZDKRating","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKRating","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/bad","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/good","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating\/none"],"title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRating"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ZDKRatingGood","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1good\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKRatingGood"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1good\/fragments"},{"op":"replace","value":"ZDKRating","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/fragments","value":[{"text":"ZDKRating","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1none\/title","value":"ZDKRatingNone"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1none\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKRatingNone"}]},{"op":"replace","value":"ZDKRatingBad","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1bad\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating~1bad\/fragments","value":[{"kind":"identifier","text":"ZDKRatingBad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}