{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKChatProvider) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatProvider"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It provides APIs to:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"proactively request a chat"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"send messages"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"handle failed messages (retry\/delete)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"set the visitors’ typing indicator"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"end the chat"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP","doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ChatProvidersSDK\/SQ","doc:\/\/com.zendesk.ChatProvidersSDK\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatProvider"}],"title":"ChatProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatProvider","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/chatState"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/deleteFailedMessage(withId:completion:)-71j9f","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/deleteFailedMessage(withId:completion:)-8naqu","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/endChat(_:)-4b8vu","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/endChat(_:)-7tsip","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/getChatInfo(_:)-8xt3m","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/getChatInfo(_:)-9fam3","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-3wak7","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-4bipl","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/requestChat()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedFile(withId:onProgress:completion:)-4tvqy","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedFile(withId:onProgress:completion:)-4z0rj","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedMessage(withId:completion:)-1b013","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedMessage(withId:completion:)-9aoa6","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatComment(_:completion:)-1kx2x","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatComment(_:completion:)-7xsqo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatRating(_:completion:)-2slpv","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatRating(_:completion:)-7hhpe","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendEmailTranscript(_:completion:)-19wpq","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendEmailTranscript(_:completion:)-9rc9j","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendFile(url:onProgress:completion:)-5tgc5","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendFile(url:onProgress:completion:)-6mbcj","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendMessage(_:completion:)-2p7mo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendMessage(_:completion:)-2xxz7","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-1si17","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-3ds3o","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendTyping(isTyping:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-2i2ki","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-8oowl","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-9xul0","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartmentByIdentifier(_:completion:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/Loggable-Implementations"],"generated":true}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/resendFailedFile(withId:onProgress:completion:)-4z0rj":{"role":"symbol","title":"resendFailedFile(withId:onProgress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendFailedFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onProgress"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedFile(withId:onProgress:completion:)-4z0rj","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resendFailedFileWithId:onProgress:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/resendfailedfile(withid:onprogress:completion:)-4z0rj"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendOfflineForm(_:completion:)-3ds3o":{"role":"symbol","title":"sendOfflineForm(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendOfflineForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-3ds3o","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendOfflineForm:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendofflineform(_:completion:)-3ds3o"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendChatComment(_:completion:)-7xsqo":{"role":"symbol","title":"sendChatComment(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendChatComment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatComment(_:completion:)-7xsqo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendChatComment:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendchatcomment(_:completion:)-7xsqo"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/chatState":{"role":"symbol","title":"chatState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"}],"abstract":[{"type":"text","text":"Current chat state. Defaults to "},{"type":"codeVoice","code":"ChatState.initial"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/chatState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chatState"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/chatstate"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendOfflineForm(_:completion:)-1si17":{"role":"symbol","title":"sendOfflineForm(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendOfflineForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"OfflineForm","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKOfflineForm"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Sends an offline form from the current visitor."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-1si17","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendofflineform(_:completion:)-1si17"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendFile(url:onProgress:completion:)-6mbcj":{"role":"symbol","title":"sendFile(url:onProgress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onProgress"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ChatAttachmentMessage","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachmentMessage"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Send an attachment message."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendFile(url:onProgress:completion:)-6mbcj","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendfile(url:onprogress:completion:)-6mbcj"},"doc://com.zendesk.ChatProvidersSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(pl)NSObject"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/setDepartment(_:completion:)-8oowl":{"role":"symbol","title":"setDepartment(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDepartment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-8oowl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDepartment:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/setdepartment(_:completion:)-8oowl"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendFile(url:onProgress:completion:)-5tgc5":{"role":"symbol","title":"sendFile(url:onProgress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onProgress"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatAttachmentMessage","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAttachmentMessage"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendFile(url:onProgress:completion:)-5tgc5","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendFileWithUrl:onProgress:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendfile(url:onprogress:completion:)-5tgc5"},"doc://com.zendesk.ChatProvidersSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/getChatInfo(_:)-9fam3":{"role":"symbol","title":"getChatInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChatInfo"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"ChatInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatInfo"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/getChatInfo(_:)-9fam3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getChatInfo:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/getchatinfo(_:)-9fam3"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Loggable":{"role":"symbol","title":"Loggable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Loggable"}],"abstract":[{"type":"text","text":"Protocol that conforms"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Loggable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Loggable"}],"url":"\/documentation\/chatproviderssdk\/loggable"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendChatRating(_:completion:)-7hhpe":{"role":"symbol","title":"sendChatRating(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendChatRating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatRating(_:completion:)-7hhpe","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendChatRating:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendchatrating(_:completion:)-7hhpe"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendMessage(_:completion:)-2p7mo":{"role":"symbol","title":"sendMessage(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Send a chat message"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendMessage(_:completion:)-2p7mo","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendmessage(_:completion:)-2p7mo"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/setDepartment(_:completion:)-2i2ki":{"role":"symbol","title":"setDepartment(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDepartment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set the department by name for the next chat session."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-2i2ki","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/setdepartment(_:completion:)-2i2ki"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/resendFailedMessage(withId:completion:)-1b013":{"role":"symbol","title":"resendFailedMessage(withId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendFailedMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedMessage(withId:completion:)-1b013","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resendFailedMessageWithId:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/resendfailedmessage(withid:completion:)-1b013"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/deleteFailedMessage(withId:completion:)-8naqu":{"role":"symbol","title":"deleteFailedMessage(withId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteFailedMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Delete failed message identified by given message id."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/deleteFailedMessage(withId:completion:)-8naqu","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/deletefailedmessage(withid:completion:)-8naqu"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider":{"role":"symbol","title":"ChatProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatProvider"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatProvider"},{"type":"text","text":" provides APIs to interact and observe the current Chat session."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatProvider"}],"url":"\/documentation\/chatproviderssdk\/chatprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/observeChatState(identifier:_:)-3wak7":{"role":"symbol","title":"observeChatState(identifier:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-3wak7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeChatStateWithIdentifier::"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(identifier:_:)-3wak7"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/endChat(_:)-4b8vu":{"role":"symbol","title":"endChat(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endChat"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/endChat(_:)-4b8vu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"endChat:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/endchat(_:)-4b8vu"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendTyping(isTyping:)":{"role":"symbol","title":"sendTyping(isTyping:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendTyping"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isTyping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Let’s the agent know when the visitor is typing."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendTyping(isTyping:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendTypingWithIsTyping:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendtyping(istyping:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/setDepartmentByIdentifier(_:completion:)":{"role":"symbol","title":"setDepartmentByIdentifier(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDepartmentByIdentifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set the department by Id for the next chat session."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartmentByIdentifier(_:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/setdepartmentbyidentifier(_:completion:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/Loggable-Implementations":{"role":"collectionGroup","title":"Loggable Implementations","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/Loggable-Implementations","kind":"article","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/loggable-implementations"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendEmailTranscript(_:completion:)-19wpq":{"role":"symbol","title":"sendEmailTranscript(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendEmailTranscript"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Schedules an email containing the chat transcript to be sent to email when the chat has ended."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendEmailTranscript(_:completion:)-19wpq","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendemailtranscript(_:completion:)-19wpq"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/observeChatState(_:)":{"role":"symbol","title":"observeChatState(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeChatState:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/deleteFailedMessage(withId:completion:)-71j9f":{"role":"symbol","title":"deleteFailedMessage(withId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteFailedMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/deleteFailedMessage(withId:completion:)-71j9f","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteFailedMessageWithId:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/deletefailedmessage(withid:completion:)-71j9f"},"doc://com.zendesk.ChatProvidersSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"},"doc://com.zendesk.ChatProvidersSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SQ"},"doc://com.zendesk.ChatProvidersSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s7CVarArgP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/endChat(_:)-7tsip":{"role":"symbol","title":"endChat(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"endChat"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Ends the chat and closes the socket connection"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/endChat(_:)-7tsip","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/endchat(_:)-7tsip"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/resendFailedMessage(withId:completion:)-9aoa6":{"role":"symbol","title":"resendFailedMessage(withId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendFailedMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Resend failed message identified by given message id"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedMessage(withId:completion:)-9aoa6","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/resendfailedmessage(withid:completion:)-9aoa6"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/resendFailedFile(withId:onProgress:completion:)-4tvqy":{"role":"symbol","title":"resendFailedFile(withId:onProgress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resendFailedFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onProgress"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Resend attachment identified by given message id"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedFile(withId:onProgress:completion:)-4tvqy","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/resendfailedfile(withid:onprogress:completion:)-4tvqy"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/setDepartment(_:completion:)-9xul0":{"role":"symbol","title":"setDepartment(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDepartment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-9xul0","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDepartment:_:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/setdepartment(_:completion:)-9xul0"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendEmailTranscript(_:completion:)-9rc9j":{"role":"symbol","title":"sendEmailTranscript(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendEmailTranscript"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendEmailTranscript(_:completion:)-9rc9j","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendEmailTranscript:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendemailtranscript(_:completion:)-9rc9j"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/getChatInfo(_:)-8xt3m":{"role":"symbol","title":"getChatInfo(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChatInfo"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ChatInfo","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatInfo"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get information about the state of the current chat."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/getChatInfo(_:)-8xt3m","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/getchatinfo(_:)-8xt3m"},"doc://com.zendesk.ChatProvidersSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/SH"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/observeChatState(identifier:_:)-4bipl":{"role":"symbol","title":"observeChatState(identifier:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ObservableIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":", ("},{"kind":"typeIdentifier","text":"ChatState","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"abstract":[{"type":"text","text":"Observe changes of the current chat’s state"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-4bipl","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/observechatstate(identifier:_:)-4bipl"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendMessage(_:completion:)-2xxz7":{"role":"symbol","title":"sendMessage(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendMessage(_:completion:)-2xxz7","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendMessage:completion:"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/sendmessage(_:completion:)-2xxz7"},"doc://com.zendesk.ChatProvidersSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendChatRating(_:completion:)-2slpv":{"role":"symbol","title":"sendChatRating(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendChatRating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Rating","preciseIdentifier":"s:16ChatProvidersSDK6RatingO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Rating","preciseIdentifier":"s:16ChatProvidersSDK6RatingO"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Send a chat "},{"type":"codeVoice","code":"Rating"},{"type":"text","text":" for the active session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatRating(_:completion:)-2slpv","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendchatrating(_:completion:)-2slpv"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/requestChat()":{"deprecated":true,"role":"symbol","title":"requestChat()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestChat"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Proactively lets an agent know that the user wants to chat."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/requestChat()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestChat"}],"url":"\/documentation\/chatproviderssdk\/chatprovider\/requestchat()"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatProvider/sendChatComment(_:completion:)-1kx2x":{"role":"symbol","title":"sendChatComment(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendChatComment"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"DeliveryStatusError","preciseIdentifier":"s:16ChatProvidersSDK19DeliveryStatusErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Send a comment about the current chat session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatComment(_:completion:)-1kx2x","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk\/chatprovider\/sendchatcomment(_:completion:)-1kx2x"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKChatProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKChatProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/chatState"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/deleteFailedMessage(withId:completion:)-71j9f","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/endChat(_:)-4b8vu","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/getChatInfo(_:)-9fam3","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(_:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/observeChatState(identifier:_:)-3wak7","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/requestChat()","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedFile(withId:onProgress:completion:)-4z0rj","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/resendFailedMessage(withId:completion:)-1b013","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatComment(_:completion:)-7xsqo","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendChatRating(_:completion:)-7hhpe","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendEmailTranscript(_:completion:)-9rc9j","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendFile(url:onProgress:completion:)-5tgc5","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendMessage(_:completion:)-2xxz7","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendOfflineForm(_:completion:)-3ds3o","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/sendTyping(isTyping:)","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-8oowl","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatProvider\/setDepartment(_:completion:)-9xul0"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.ChatProvidersSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKChatProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1resendFailedFile(withId:onProgress:completion:)-4z0rj\/title","value":"resendFailedFileWithId:onProgress:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1resendFailedFile(withId:onProgress:completion:)-4z0rj\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resendFailedFileWithId:onProgress:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendOfflineForm(_:completion:)-3ds3o\/title","value":"sendOfflineForm:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendOfflineForm(_:completion:)-3ds3o\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendOfflineForm:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendChatComment(_:completion:)-7xsqo\/title","value":"sendChatComment:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendChatComment(_:completion:)-7xsqo\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendChatComment:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1chatState\/title","value":"chatState"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1chatState\/fragments","value":[{"kind":"identifier","text":"chatState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1setDepartment(_:completion:)-8oowl\/title","value":"setDepartment:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1setDepartment(_:completion:)-8oowl\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDepartment:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendFile(url:onProgress:completion:)-5tgc5\/title","value":"sendFileWithUrl:onProgress:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendFile(url:onProgress:completion:)-5tgc5\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFileWithUrl:onProgress:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1getChatInfo(_:)-9fam3\/title","value":"getChatInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1getChatInfo(_:)-9fam3\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getChatInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendChatRating(_:completion:)-7hhpe\/title","value":"sendChatRating:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendChatRating(_:completion:)-7hhpe\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendChatRating:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1resendFailedMessage(withId:completion:)-1b013\/title","value":"resendFailedMessageWithId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1resendFailedMessage(withId:completion:)-1b013\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resendFailedMessageWithId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/title","value":"ZDKChatProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider\/fragments","value":[{"kind":"identifier","text":"ZDKChatProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1observeChatState(identifier:_:)-3wak7\/title","value":"observeChatStateWithIdentifier::"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1observeChatState(identifier:_:)-3wak7\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeChatStateWithIdentifier::"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1endChat(_:)-4b8vu\/title","value":"endChat:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1endChat(_:)-4b8vu\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endChat:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendTyping(isTyping:)\/title","value":"sendTypingWithIsTyping:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendTyping(isTyping:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendTypingWithIsTyping:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1observeChatState(_:)\/title","value":"observeChatState:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1observeChatState(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeChatState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1deleteFailedMessage(withId:completion:)-71j9f\/title","value":"deleteFailedMessageWithId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1deleteFailedMessage(withId:completion:)-71j9f\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteFailedMessageWithId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1setDepartment(_:completion:)-9xul0\/title","value":"setDepartment:_:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1setDepartment(_:completion:)-9xul0\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDepartment:_:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendEmailTranscript(_:completion:)-9rc9j\/title","value":"sendEmailTranscript:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendEmailTranscript(_:completion:)-9rc9j\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendEmailTranscript:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendMessage(_:completion:)-2xxz7\/title","value":"sendMessage:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1sendMessage(_:completion:)-2xxz7\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendMessage:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1requestChat()\/title","value":"requestChat"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatProvider~1requestChat()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}