{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","text":"ChatSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservationToken"},{"type":"text","text":" that can cancel the subscription to the "},{"type":"codeVoice","code":"ChatSettings"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specify how to handle the "},{"type":"codeVoice","code":"ChatSettings"},{"type":"text","text":" via closure."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Observe chat settings model"}],"kind":"symbol","metadata":{"modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"observeChatSettings:"}],"role":"symbol","title":"observeChatSettings(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatSettings"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"ChatSettings","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"symbolKind":"method","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKSettingsProvider(im)observeChatSettings:","extendedModule":"ChatProvidersSDK","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"role":"symbol","title":"ChatSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSettings"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatSettings"},{"type":"text","text":" model stores information about the chat account’s settings,"},{"type":"text","text":" "},{"type":"text","text":"such as the "},{"type":"codeVoice","code":"fileSizeLimit"},{"type":"text","text":", whether attachments are enabled, and the list of accepted file extensions."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatSettings"}],"url":"\/documentation\/chatproviderssdk\/chatsettings"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider/observeChatSettings(_:)":{"role":"symbol","title":"observeChatSettings(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatSettings"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"ChatSettings","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"abstract":[{"type":"text","text":"Observe chat settings model"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"observeChatSettings:"}],"url":"\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(_:)"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider":{"role":"symbol","title":"SettingsProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsProvider"}],"abstract":[{"type":"codeVoice","code":"ZDKSettingsProvider"},{"type":"text","text":" gives the ability to observe settings updates."}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsProvider"}],"url":"\/documentation\/chatproviderssdk\/settingsprovider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"role":"symbol","title":"ObservationToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"abstract":[{"type":"text","text":"Unsubscribe from observers"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"url":"\/documentation\/chatproviderssdk\/observationtoken"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"observeChatSettings:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeChatSettings:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ZDKObservationToken"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"observeChatSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ZDKChatSettings *)","preciseIdentifier":"c:BFv(#*$@M@ChatProvidersSDK@objc(cs)ZDKChatSettings)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title","value":"ZDKChatSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments","value":[{"kind":"identifier","text":"ZDKChatSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(_:)\/title","value":"observeChatSettings:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider~1observeChatSettings(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"observeChatSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/title","value":"ZDKSettingsProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/fragments","value":[{"kind":"identifier","text":"ZDKSettingsProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title","value":"ZDKObservationToken"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","value":[{"kind":"identifier","text":"ZDKObservationToken"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}