{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-9o16i"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"observeChatSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"kind":"text","text":" = .uuid(), "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","text":"ChatSettings"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ObservationToken","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"text":"ObservableIdentifier to be exclusive, or unique","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specify how to handle the "},{"type":"codeVoice","code":"ChatSettings"},{"type":"text","text":" via closure."}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ObservationToken"},{"type":"text","text":" that can cancel the subscription to the "},{"code":"ChatSettings","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider"]]},"metadata":{"role":"symbol","title":"observeChatSettings(identifier:_:)","symbolKind":"method","modules":[{"name":"ChatProvidersSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"observeChatSettings"},{"text":"(","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ObservableIdentifier","kind":"typeIdentifier","preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO"},{"text":", (","kind":"text"},{"text":"ChatSettings","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken","text":"ObservationToken","kind":"typeIdentifier"}],"externalID":"s:16ChatProvidersSDK16SettingsProviderC07observeaD010identifier_AA16ObservationTokenCAA20ObservableIdentifierO_yAA0aD0CctF","roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(identifier:_:)-9o16i"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"text":"Observe chat settings model","type":"text"}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider/observeChatSettings(identifier:_:)-9o16i":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"observeChatSettings","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:16ChatProvidersSDK20ObservableIdentifierO","kind":"typeIdentifier","text":"ObservableIdentifier"},{"text":", (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatSettings","text":"ChatSettings"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"ObservationToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKObservationToken"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider\/observeChatSettings(identifier:_:)-9o16i","title":"observeChatSettings(identifier:_:)","kind":"symbol","url":"\/documentation\/chatproviderssdk\/settingsprovider\/observechatsettings(identifier:_:)-9o16i","type":"topic","abstract":[{"text":"Observe chat settings model","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservableIdentifier":{"title":"ObservableIdentifier","url":"\/documentation\/chatproviderssdk\/observableidentifier","navigatorTitle":[{"kind":"identifier","text":"ObservableIdentifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservableIdentifier","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ObservableIdentifier","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Enum to specify how to identify an object that is subscribe to an observable"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/SettingsProvider":{"role":"symbol","url":"\/documentation\/chatproviderssdk\/settingsprovider","navigatorTitle":[{"kind":"identifier","text":"SettingsProvider"}],"abstract":[{"type":"codeVoice","code":"ZDKSettingsProvider"},{"text":" gives the ability to observe settings updates.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SettingsProvider","kind":"identifier"}],"kind":"symbol","type":"topic","title":"SettingsProvider","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/SettingsProvider"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ObservationToken":{"title":"ObservationToken","url":"\/documentation\/chatproviderssdk\/observationtoken","navigatorTitle":[{"kind":"identifier","text":"ObservationToken"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ObservationToken","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservationToken"}],"kind":"symbol","abstract":[{"text":"Unsubscribe from observers","type":"text"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatSettings":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatSettings","kind":"symbol","navigatorTitle":[{"text":"ChatSettings","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatSettings"}],"title":"ChatSettings","abstract":[{"type":"text","text":"The "},{"code":"ZDKChatSettings","type":"codeVoice"},{"text":" model stores information about the chat account’s settings,","type":"text"},{"text":" ","type":"text"},{"text":"such as the ","type":"text"},{"type":"codeVoice","code":"fileSizeLimit"},{"text":", whether attachments are enabled, and the list of accepted file extensions.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/chatsettings","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ZDKSettingsProvider","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/title"},{"op":"replace","value":[{"text":"ZDKSettingsProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1SettingsProvider\/fragments"},{"value":"ZDKObservationToken","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/title"},{"value":[{"text":"ZDKObservationToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ObservationToken\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/title","value":"ZDKChatSettings"},{"value":[{"text":"ZDKChatSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatSettings\/fragments"}]}]}