{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"agents","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","text":"Agent"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isChatting"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chatId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"department"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","text":"Department","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"logs"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","text":"ChatLog"},{"text":"], ","kind":"text"},{"text":"queue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"comment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rating"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","text":"ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatstate\/init(agents:ischatting:chatid:department:logs:queue:comment:rating:)-2metd"]},{"paths":["\/documentation\/chatproviderssdk\/chatstate\/init(agents:ischatting:chatid:department:logs:queue:comment:rating:)-2metd"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"agents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent","text":"Agent"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"isChatting"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"chatId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"department","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Department","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"logs"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog","kind":"typeIdentifier","text":"ChatLog"},{"text":"], ","kind":"text"},{"text":"queue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"comment","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"rating"},{"text":": ","kind":"text"},{"text":"ZDKRating","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:"}],"platforms":[],"role":"symbol","externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKChatState(im)initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:","modules":[{"name":"ChatProvidersSDK"}],"title":"init(agents:isChatting:chatId:department:logs:queue:comment:rating:)","roleHeading":"Initializer","symbolKind":"init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Department"}],"title":"Department","abstract":[{"type":"text","text":"Department model contains id associated with the department,"},{"type":"text","text":" "},{"text":"the department name, and the current status of the department.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","type":"topic","navigatorTitle":[{"text":"Department","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/department"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","abstract":[{"type":"text","text":"Base class for chat log events that may occur in a chat session"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatLog","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLog"}],"role":"symbol","url":"\/documentation\/chatproviderssdk\/chatlog","title":"ChatLog"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"type":"text","text":" is a model representation of the current chat session."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatState"}],"type":"topic","title":"ChatState","url":"\/documentation\/chatproviderssdk\/chatstate","role":"symbol","navigatorTitle":[{"text":"ChatState","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Agent":{"navigatorTitle":[{"text":"Agent","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Agent","title":"Agent","type":"topic","role":"symbol","url":"\/documentation\/chatproviderssdk\/agent","abstract":[{"text":"The ","type":"text"},{"code":"ZDKAgent","type":"codeVoice"},{"text":" model has information about an agent in a chat session,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"such as their backend "},{"code":"id","type":"codeVoice"},{"type":"text","text":" represented as "},{"code":"nick","type":"codeVoice"},{"text":", their display ","type":"text"},{"code":"name","type":"codeVoice"},{"text":", their ","type":"text"},{"type":"codeVoice","code":"avatar"},{"type":"text","text":", and if they’re currently typing."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Agent"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"agents"},{"kind":"text","text":": ["},{"text":"Agent","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKAgent"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isChatting"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"chatId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"department","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier","text":"Department"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"logs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatLog","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog"},{"kind":"text","text":"], "},{"text":"queue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"comment","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"rating","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating"},{"text":")","kind":"text"}],"abstract":[],"title":"init(agents:isChatting:chatId:department:logs:queue:comment:rating:)","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd","kind":"symbol","url":"\/documentation\/chatproviderssdk\/chatstate\/init(agents:ischatting:chatid:department:logs:queue:comment:rating:)-2metd","navigatorTitle":[{"kind":"identifier","text":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:"}],"type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKRating":{"role":"symbol","title":"ZDKRating","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKRating"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKRating"}],"url":"\/documentation\/chatproviderssdk\/zdkrating","kind":"symbol","abstract":[{"text":"A rating that can be assigned to the chat","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAgents:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKAgent *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"agents"},{"kind":"text","text":" "},{"kind":"identifier","text":"isChatting:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isChatting"},{"kind":"text","text":" "},{"text":"chatId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"chatId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"department:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKDepartment","kind":"typeIdentifier","text":"ZDKDepartment"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"department"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKChatLog *>"},{"kind":"text","text":" *) "},{"text":"logs","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"queue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"queue","kind":"internalParam"},{"kind":"text","text":" "},{"text":"comment:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"comment","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rating:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKRating","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKRating","text":"ZDKRating"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"rating"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKDepartment","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/title","op":"replace"},{"value":[{"text":"ZDKDepartment","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/fragments","op":"replace"},{"value":"ZDKChatLog","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","op":"replace","value":[{"text":"ZDKChatLog","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","value":"ZDKChatState"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","value":[{"kind":"identifier","text":"ZDKChatState"}],"op":"replace"},{"value":"ZDKAgent","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Agent\/fragments","value":[{"text":"ZDKAgent","kind":"identifier"}]},{"value":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAgents:isChatting:chatId:department:logs:queue:comment:rating:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1init(agents:isChatting:chatId:department:logs:queue:comment:rating:)-2metd\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/title","value":"ZDKRating"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKRating"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKRating\/fragments"}]}]}