{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/queuePosition"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"queuePosition","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/QueuePosition","text":"QueuePosition","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKQueuePosition"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatstate\/queueposition"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/chatstate\/queueposition"]}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queuePosition","kind":"identifier"},{"kind":"text","text":": "},{"text":"QueuePosition","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKQueuePosition","kind":"typeIdentifier"}],"title":"queuePosition","symbolKind":"property","navigatorTitle":[{"text":"queuePosition","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatState(py)queuePosition","roleHeading":"Instance Property","modules":[{"name":"ChatProvidersSDK"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Queue position","type":"text"}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/QueuePosition":{"title":"QueuePosition","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QueuePosition","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/QueuePosition","navigatorTitle":[{"text":"QueuePosition","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"ZDKQueuePosition"},{"type":"text","text":" is a model that represents the current queue position of the visitor."}],"url":"\/documentation\/chatproviderssdk\/queueposition","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState","abstract":[{"type":"codeVoice","code":"ZDKChatState"},{"type":"text","text":" is a model representation of the current chat session."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatState"}],"type":"topic","title":"ChatState","url":"\/documentation\/chatproviderssdk\/chatstate","role":"symbol","navigatorTitle":[{"text":"ChatState","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"title":"ChatProvidersSDK","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","type":"topic","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatState/queuePosition":{"kind":"symbol","abstract":[{"type":"text","text":"Queue position"}],"type":"topic","role":"symbol","title":"queuePosition","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatState\/queuePosition","url":"\/documentation\/chatproviderssdk\/chatstate\/queueposition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"queuePosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"QueuePosition","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKQueuePosition","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"queuePosition"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"queuePosition"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"queuePosition","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/QueuePosition","text":"ZDKQueuePosition","preciseIdentifier":"c:@M@ChatProvidersSDK@objc(cs)ZDKQueuePosition"},{"kind":"text","text":" * "},{"text":"queuePosition","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1QueuePosition\/title","op":"replace","value":"ZDKQueuePosition"},{"value":[{"text":"ZDKQueuePosition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1QueuePosition\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/title","op":"replace","value":"ZDKChatState"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState\/fragments","value":[{"text":"ZDKChatState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1queuePosition\/title","op":"replace","value":"queuePosition"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatState~1queuePosition\/fragments","op":"replace","value":[{"text":"queuePosition","kind":"identifier"}]}]}]}