{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/accountStatus"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/account\/accountstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/account\/accountstatus"]}],"abstract":[{"type":"text","text":"The current status of the "},{"code":"Account","type":"codeVoice"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus","text":"AccountStatus"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AccountStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus"}],"modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"text":"accountStatus","kind":"identifier"}],"externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAccount(py)accountStatus","symbolKind":"property","title":"accountStatus","roleHeading":"Instance Property","role":"symbol"},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus":{"abstract":[{"text":"Account Status","type":"text"}],"navigatorTitle":[{"text":"AccountStatus","kind":"identifier"}],"title":"AccountStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","role":"symbol","url":"\/documentation\/chatproviderssdk\/accountstatus","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AccountStatus","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account/accountStatus":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountStatus"},{"text":": ","kind":"text"},{"text":"AccountStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account\/accountStatus","type":"topic","navigatorTitle":[{"text":"accountStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"The current status of the "},{"type":"codeVoice","code":"Account"}],"title":"accountStatus","role":"symbol","url":"\/documentation\/chatproviderssdk\/account\/accountstatus"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Account":{"role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ZDKChatAccount"},{"type":"text","text":" model stores information about the chat account,"},{"type":"text","text":" "},{"type":"text","text":"such as the current "},{"type":"codeVoice","code":"accountStatus"},{"text":" and the list of ","type":"text"},{"code":"Department","type":"codeVoice"},{"type":"text","text":"s associated with the account"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Account"}],"type":"topic","title":"Account","url":"\/documentation\/chatproviderssdk\/account","navigatorTitle":[{"kind":"identifier","text":"Account"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Account"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"accountStatus"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountStatus"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKChatAccountStatus","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus"},{"kind":"text","text":" "},{"text":"accountStatus","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"ZDKChatAccountStatus","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/fragments","value":[{"text":"ZDKChatAccountStatus","kind":"identifier"}],"op":"replace"},{"value":"accountStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1accountStatus\/title","op":"replace"},{"op":"replace","value":[{"text":"accountStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account~1accountStatus\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/title","op":"replace","value":"ZDKChatAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Account\/fragments","value":[{"kind":"identifier","text":"ZDKChatAccount"}]}]}]}