{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","title":"debugDescription","roleHeading":"Instance Property","modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@CM@ChatProvidersSDK@objc(cs)ZDKDepartment(py)debugDescription","navigatorTitle":[{"kind":"identifier","text":"debugDescription"}],"symbolKind":"property"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department\/debugDescription","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/department\/debugdescription"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/department\/debugdescription"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department/debugDescription":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department\/debugDescription","kind":"symbol","navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"url":"\/documentation\/chatproviderssdk\/department\/debugdescription","type":"topic","title":"debugDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"debugDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","kind":"symbol"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/Department":{"role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/Department","title":"Department","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Department","kind":"identifier"}],"navigatorTitle":[{"text":"Department","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Department model contains id associated with the department,"},{"type":"text","text":" "},{"text":"the department name, and the current status of the department.","type":"text"}],"url":"\/documentation\/chatproviderssdk\/department"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"debugDescription"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"debugDescription","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"debugDescription","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department~1debugDescription\/title","value":"debugDescription","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"debugDescription"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department~1debugDescription\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/title","op":"replace","value":"ZDKDepartment"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1Department\/fragments","value":[{"kind":"identifier","text":"ZDKDepartment"}],"op":"replace"}]}]}