{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"online","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/accountstatus\/online"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chatproviderssdk\/accountstatus\/online"]}],"kind":"symbol","metadata":{"title":"AccountStatus.online","symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ZDKChatAccountStatusOnline","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"online"}],"modules":[{"name":"ChatProvidersSDK"}],"externalID":"c:@M@ChatProvidersSDK@E@ZDKChatAccountStatus@ZDKChatAccountStatusOnline"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus"]]},"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/online","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus":{"url":"\/documentation\/chatproviderssdk\/accountstatus","kind":"symbol","role":"symbol","title":"AccountStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountStatus"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus","navigatorTitle":[{"text":"AccountStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Account Status"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"role":"collection","type":"topic","title":"ChatProvidersSDK","kind":"symbol","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/AccountStatus/online":{"kind":"symbol","abstract":[],"title":"AccountStatus.online","type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/AccountStatus\/online","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"online"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKChatAccountStatusOnline"}],"url":"\/documentation\/chatproviderssdk\/accountstatus\/online"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ZDKChatAccountStatusOnline"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKChatAccountStatusOnline","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKChatAccountStatusOnline","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"ZDKChatAccountStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKChatAccountStatus"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus~1online\/title","value":"ZDKChatAccountStatusOnline"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1AccountStatus~1online\/fragments","value":[{"text":"ZDKChatAccountStatusOnline","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}