{"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus\/online","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"online","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"online","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"ZDKDepartmentStatusOnline","kind":"identifier"}],"title":"ZDKDepartmentStatus.online","externalID":"c:@M@ChatProvidersSDK@E@ZDKDepartmentStatus@ZDKDepartmentStatusOnline","modules":[{"name":"ChatProvidersSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/online"]},{"paths":["\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/online"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus/online":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"online","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ZDKDepartmentStatusOnline","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus\/online","title":"ZDKDepartmentStatus.online","url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus\/online","type":"topic"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ZDKDepartmentStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKDepartmentStatus"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ZDKDepartmentStatus","url":"\/documentation\/chatproviderssdk\/zdkdepartmentstatus","navigatorTitle":[{"text":"ZDKDepartmentStatus","kind":"identifier"}],"role":"symbol","title":"ZDKDepartmentStatus","abstract":[]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","abstract":[],"kind":"symbol","title":"ChatProvidersSDK","url":"\/documentation\/chatproviderssdk","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"ZDKDepartmentStatusOnline","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKDepartmentStatusOnline"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKDepartmentStatusOnline","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKDepartmentStatusOnline","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus~1online\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus~1online\/fragments","value":[{"text":"ZDKDepartmentStatusOnline","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKDepartmentStatus","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ZDKDepartmentStatus\/fragments","op":"replace","value":[{"text":"ZDKDepartmentStatus","kind":"identifier"}]}]}]}