{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatLogType","text":"ChatLogType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/chatproviderssdk\/chatlog\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chatproviderssdk\/chatlog\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of event the log is"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatLogType","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatLogType"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatLog(py)type","modules":[{"name":"ChatProvidersSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog"]]},"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLogType":{"role":"symbol","title":"ChatLogType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatLogType"}],"abstract":[{"type":"text","text":"An enum of the message types that can be in sent\/received in a chat session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatLogType"}],"url":"\/documentation\/chatproviderssdk\/chatlogtype"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog":{"role":"symbol","title":"ChatLog","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatLog"}],"abstract":[{"type":"text","text":"Base class for chat log events that may occur in a chat session"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatLog"}],"url":"\/documentation\/chatproviderssdk\/chatlog"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"role":"collection","title":"ChatProvidersSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","kind":"symbol","type":"topic","url":"\/documentation\/chatproviderssdk"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatLog/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatLogType","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatLogType"}],"abstract":[{"type":"text","text":"The type of event the log is"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLog\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/chatproviderssdk\/chatlog\/type"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatLogType","preciseIdentifier":"c:@M@ChatProvidersSDK@E@ZDKChatLogType","text":"ZDKChatLogType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/title","value":"ZDKChatLogType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLogType\/fragments","value":[{"kind":"identifier","text":"ZDKChatLogType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/title","value":"ZDKChatLog"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog\/fragments","value":[{"kind":"identifier","text":"ZDKChatLog"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatLog~1type\/fragments","value":[{"kind":"identifier","text":"type"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}