{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/init()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Default initializer"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK","doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}]}],"metadata":{"modules":[{"name":"ChatProvidersSDK"}],"role":"symbol","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"title":"init()","externalID":"c:@M@ChatProvidersSDK@objc(cs)ZDKChatAPIConfiguration(im)init","symbolKind":"init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration\/init()"]},{"paths":["\/documentation\/chatproviderssdk\/chatapiconfiguration\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration/init()":{"url":"\/documentation\/chatproviderssdk\/chatapiconfiguration\/init()","role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration\/init()","abstract":[{"text":"Default initializer","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK":{"url":"\/documentation\/chatproviderssdk","type":"topic","title":"ChatProvidersSDK","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK"},"doc://com.zendesk.ChatProvidersSDK/documentation/ChatProvidersSDK/ChatAPIConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatAPIConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ChatProvidersSDK\/documentation\/ChatProvidersSDK\/ChatAPIConfiguration","title":"ChatAPIConfiguration","url":"\/documentation\/chatproviderssdk\/chatapiconfiguration","type":"topic","abstract":[{"text":"A set of configurations that are associated with each chat session.","type":"text"}],"navigatorTitle":[{"text":"ChatAPIConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/title","value":"ZDKChatAPIConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKChatAPIConfiguration"}],"path":"\/references\/doc:~1~1com.zendesk.ChatProvidersSDK~1documentation~1ChatProvidersSDK~1ChatAPIConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}